/* tslint:disable */
/* eslint-disable */
/**
 * ISI WFS EAI
 * ISI WFS EAI - Service zum Abfragen von Geoinformationen des WFS
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    GeometryDto,
    GeometryDtoFromJSON,
    GeometryDtoFromJSONTyped,
    GeometryDtoToJSON,
} from './GeometryDto';
import {
    StadtbezirkDto,
    StadtbezirkDtoFromJSON,
    StadtbezirkDtoFromJSONTyped,
    StadtbezirkDtoToJSON,
} from './StadtbezirkDto';

/**
 * 
 * @export
 * @interface StadtbezirkFeatureDto
 */
export interface StadtbezirkFeatureDto {
    /**
     * 
     * @type {string}
     * @memberof StadtbezirkFeatureDto
     */
    type?: string;
    /**
     * 
     * @type {GeometryDto}
     * @memberof StadtbezirkFeatureDto
     */
    geometry?: GeometryDto;
    /**
     * 
     * @type {StadtbezirkDto}
     * @memberof StadtbezirkFeatureDto
     */
    properties?: StadtbezirkDto;
}

export function StadtbezirkFeatureDtoFromJSON(json: any): StadtbezirkFeatureDto {
    return StadtbezirkFeatureDtoFromJSONTyped(json, false);
}

export function StadtbezirkFeatureDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StadtbezirkFeatureDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'geometry': !exists(json, 'geometry') ? undefined : GeometryDtoFromJSON(json['geometry']),
        'properties': !exists(json, 'properties') ? undefined : StadtbezirkDtoFromJSON(json['properties']),
    };
}

export function StadtbezirkFeatureDtoToJSON(value?: StadtbezirkFeatureDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'geometry': GeometryDtoToJSON(value.geometry),
        'properties': StadtbezirkDtoToJSON(value.properties),
    };
}

