/* tslint:disable */
/* eslint-disable */
/**
 * ISI WFS EAI
 * ISI WFS EAI - Service zum Abfragen von Geoinformationen des WFS
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StadtbezirkDto
 */
export interface StadtbezirkDto {
    /**
     * 
     * @type {number}
     * @memberof StadtbezirkDto
     */
    objectId?: number;
    /**
     * 
     * @type {string}
     * @memberof StadtbezirkDto
     */
    stadtbezirkNummer?: string;
    /**
     * 
     * @type {string}
     * @memberof StadtbezirkDto
     */
    name?: string;
    /**
     * 
     * @type {number}
     * @memberof StadtbezirkDto
     */
    flaecheQm?: number;
    /**
     * 
     * @type {number}
     * @memberof StadtbezirkDto
     */
    xcoordinate?: number;
    /**
     * 
     * @type {number}
     * @memberof StadtbezirkDto
     */
    ycoordinate?: number;
}

export function StadtbezirkDtoFromJSON(json: any): StadtbezirkDto {
    return StadtbezirkDtoFromJSONTyped(json, false);
}

export function StadtbezirkDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StadtbezirkDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'objectId': !exists(json, 'objectId') ? undefined : json['objectId'],
        'stadtbezirkNummer': !exists(json, 'stadtbezirkNummer') ? undefined : json['stadtbezirkNummer'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'flaecheQm': !exists(json, 'flaecheQm') ? undefined : json['flaecheQm'],
        'xcoordinate': !exists(json, 'xcoordinate') ? undefined : json['xcoordinate'],
        'ycoordinate': !exists(json, 'ycoordinate') ? undefined : json['ycoordinate'],
    };
}

export function StadtbezirkDtoToJSON(value?: StadtbezirkDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'objectId': value.objectId,
        'stadtbezirkNummer': value.stadtbezirkNummer,
        'name': value.name,
        'flaecheQm': value.flaecheQm,
        'xcoordinate': value.xcoordinate,
        'ycoordinate': value.ycoordinate,
    };
}

