/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AbfrageInBearbeitungSachbearbeitungDto,
    AbfrageInBearbeitungSachbearbeitungDtoFromJSON,
    AbfrageInBearbeitungSachbearbeitungDtoFromJSONTyped,
    AbfrageInBearbeitungSachbearbeitungDtoToJSON,
} from './AbfrageInBearbeitungSachbearbeitungDto';
import {
    AbfragevarianteBauleitplanverfahrenInBearbeitungSachbearbeitungDto,
    AbfragevarianteBauleitplanverfahrenInBearbeitungSachbearbeitungDtoFromJSON,
    AbfragevarianteBauleitplanverfahrenInBearbeitungSachbearbeitungDtoFromJSONTyped,
    AbfragevarianteBauleitplanverfahrenInBearbeitungSachbearbeitungDtoToJSON,
} from './AbfragevarianteBauleitplanverfahrenInBearbeitungSachbearbeitungDto';
import {
    AbfragevarianteBauleitplanverfahrenSachbearbeitungInBearbeitungSachbearbeitungDto,
    AbfragevarianteBauleitplanverfahrenSachbearbeitungInBearbeitungSachbearbeitungDtoFromJSON,
    AbfragevarianteBauleitplanverfahrenSachbearbeitungInBearbeitungSachbearbeitungDtoFromJSONTyped,
    AbfragevarianteBauleitplanverfahrenSachbearbeitungInBearbeitungSachbearbeitungDtoToJSON,
} from './AbfragevarianteBauleitplanverfahrenSachbearbeitungInBearbeitungSachbearbeitungDto';
import {
    BauleitplanverfahrenInBearbeitungSachbearbeitungDtoAllOf,
    BauleitplanverfahrenInBearbeitungSachbearbeitungDtoAllOfFromJSON,
    BauleitplanverfahrenInBearbeitungSachbearbeitungDtoAllOfFromJSONTyped,
    BauleitplanverfahrenInBearbeitungSachbearbeitungDtoAllOfToJSON,
} from './BauleitplanverfahrenInBearbeitungSachbearbeitungDtoAllOf';

/**
 * 
 * @export
 * @interface BauleitplanverfahrenInBearbeitungSachbearbeitungDto
 */
export interface BauleitplanverfahrenInBearbeitungSachbearbeitungDto extends AbfrageInBearbeitungSachbearbeitungDto {
    /**
     * 
     * @type {Array<AbfragevarianteBauleitplanverfahrenSachbearbeitungInBearbeitungSachbearbeitungDto>}
     * @memberof BauleitplanverfahrenInBearbeitungSachbearbeitungDto
     */
    abfragevarianten: Array<AbfragevarianteBauleitplanverfahrenSachbearbeitungInBearbeitungSachbearbeitungDto>;
    /**
     * 
     * @type {Array<AbfragevarianteBauleitplanverfahrenInBearbeitungSachbearbeitungDto>}
     * @memberof BauleitplanverfahrenInBearbeitungSachbearbeitungDto
     */
    abfragevariantenSachbearbeitung: Array<AbfragevarianteBauleitplanverfahrenInBearbeitungSachbearbeitungDto>;
}



export function BauleitplanverfahrenInBearbeitungSachbearbeitungDtoFromJSON(json: any): BauleitplanverfahrenInBearbeitungSachbearbeitungDto {
    return BauleitplanverfahrenInBearbeitungSachbearbeitungDtoFromJSONTyped(json, false);
}

export function BauleitplanverfahrenInBearbeitungSachbearbeitungDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BauleitplanverfahrenInBearbeitungSachbearbeitungDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        ...AbfrageInBearbeitungSachbearbeitungDtoFromJSONTyped(json, ignoreDiscriminator),
        'abfragevarianten': ((json['abfragevarianten'] as Array<any>).map(AbfragevarianteBauleitplanverfahrenSachbearbeitungInBearbeitungSachbearbeitungDtoFromJSON)),
        'abfragevariantenSachbearbeitung': ((json['abfragevariantenSachbearbeitung'] as Array<any>).map(AbfragevarianteBauleitplanverfahrenInBearbeitungSachbearbeitungDtoFromJSON)),
    };
}

export function BauleitplanverfahrenInBearbeitungSachbearbeitungDtoToJSON(value?: BauleitplanverfahrenInBearbeitungSachbearbeitungDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...AbfrageInBearbeitungSachbearbeitungDtoToJSON(value),
        'abfragevarianten': ((value.abfragevarianten as Array<any>).map(AbfragevarianteBauleitplanverfahrenSachbearbeitungInBearbeitungSachbearbeitungDtoToJSON)),
        'abfragevariantenSachbearbeitung': ((value.abfragevariantenSachbearbeitung as Array<any>).map(AbfragevarianteBauleitplanverfahrenInBearbeitungSachbearbeitungDtoToJSON)),
    };
}

