/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { AbfrageStartBearbeitungDto } from './AbfrageStartBearbeitungDto';
import {
    AbfrageStartBearbeitungDtoFromJSON,
    AbfrageStartBearbeitungDtoFromJSONTyped,
    AbfrageStartBearbeitungDtoToJSON,
} from './AbfrageStartBearbeitungDto';
import type { AbfragevarianteBauleitplanverfahrenSachbearbeitungStartBearbeitungDto } from './AbfragevarianteBauleitplanverfahrenSachbearbeitungStartBearbeitungDto';
import {
    AbfragevarianteBauleitplanverfahrenSachbearbeitungStartBearbeitungDtoFromJSON,
    AbfragevarianteBauleitplanverfahrenSachbearbeitungStartBearbeitungDtoFromJSONTyped,
    AbfragevarianteBauleitplanverfahrenSachbearbeitungStartBearbeitungDtoToJSON,
} from './AbfragevarianteBauleitplanverfahrenSachbearbeitungStartBearbeitungDto';
import type { AbfragevarianteBauleitplanverfahrenStartBearbeitungDto } from './AbfragevarianteBauleitplanverfahrenStartBearbeitungDto';
import {
    AbfragevarianteBauleitplanverfahrenStartBearbeitungDtoFromJSON,
    AbfragevarianteBauleitplanverfahrenStartBearbeitungDtoFromJSONTyped,
    AbfragevarianteBauleitplanverfahrenStartBearbeitungDtoToJSON,
} from './AbfragevarianteBauleitplanverfahrenStartBearbeitungDto';
import type { VerortungMultiPolygonDto } from './VerortungMultiPolygonDto';
import {
    VerortungMultiPolygonDtoFromJSON,
    VerortungMultiPolygonDtoFromJSONTyped,
    VerortungMultiPolygonDtoToJSON,
} from './VerortungMultiPolygonDto';

import {
} from './';

/**
 * 
 * @export
 * @interface BauleitplanverfahrenStartBearbeitungDto
 */
export interface BauleitplanverfahrenStartBearbeitungDto extends AbfrageStartBearbeitungDto {
    /**
     * 
     * @type {VerortungMultiPolygonDto}
     * @memberof BauleitplanverfahrenStartBearbeitungDto
     */
    verortung?: VerortungMultiPolygonDto;
    /**
     * 
     * @type {Array<AbfragevarianteBauleitplanverfahrenSachbearbeitungStartBearbeitungDto>}
     * @memberof BauleitplanverfahrenStartBearbeitungDto
     */
    abfragevariantenBauleitplanverfahren: Array<AbfragevarianteBauleitplanverfahrenSachbearbeitungStartBearbeitungDto>;
    /**
     * 
     * @type {Array<AbfragevarianteBauleitplanverfahrenStartBearbeitungDto>}
     * @memberof BauleitplanverfahrenStartBearbeitungDto
     */
    abfragevariantenSachbearbeitungBauleitplanverfahren: Array<AbfragevarianteBauleitplanverfahrenStartBearbeitungDto>;
}



/**
 * Check if a given object implements the BauleitplanverfahrenStartBearbeitungDto interface.
 */
export function instanceOfBauleitplanverfahrenStartBearbeitungDto(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "abfragevariantenBauleitplanverfahren" in value;
    isInstance = isInstance && "abfragevariantenSachbearbeitungBauleitplanverfahren" in value;

    return isInstance;
}

export function BauleitplanverfahrenStartBearbeitungDtoFromJSON(json: any): BauleitplanverfahrenStartBearbeitungDto {
    return BauleitplanverfahrenStartBearbeitungDtoFromJSONTyped(json, false);
}

export function BauleitplanverfahrenStartBearbeitungDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BauleitplanverfahrenStartBearbeitungDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
    }
    return {
        ...AbfrageStartBearbeitungDtoFromJSONTyped(json, ignoreDiscriminator),
        'verortung': !exists(json, 'verortung') ? undefined : VerortungMultiPolygonDtoFromJSON(json['verortung']),
        'abfragevariantenBauleitplanverfahren': ((json['abfragevariantenBauleitplanverfahren'] as Array<any>).map(AbfragevarianteBauleitplanverfahrenSachbearbeitungStartBearbeitungDtoFromJSON)),
        'abfragevariantenSachbearbeitungBauleitplanverfahren': ((json['abfragevariantenSachbearbeitungBauleitplanverfahren'] as Array<any>).map(AbfragevarianteBauleitplanverfahrenStartBearbeitungDtoFromJSON)),
    };
}

export function BauleitplanverfahrenStartBearbeitungDtoToJSON(value?: BauleitplanverfahrenStartBearbeitungDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...AbfrageStartBearbeitungDtoToJSON(value),
        'verortung': VerortungMultiPolygonDtoToJSON(value.verortung),
        'abfragevariantenBauleitplanverfahren': ((value.abfragevariantenBauleitplanverfahren as Array<any>).map(AbfragevarianteBauleitplanverfahrenSachbearbeitungStartBearbeitungDtoToJSON)),
        'abfragevariantenSachbearbeitungBauleitplanverfahren': ((value.abfragevariantenSachbearbeitungBauleitplanverfahren as Array<any>).map(AbfragevarianteBauleitplanverfahrenStartBearbeitungDtoToJSON)),
    };
}

