/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { LangfristigerPlanungsursaechlicherBedarf } from './LangfristigerPlanungsursaechlicherBedarf';
import {
    LangfristigerPlanungsursaechlicherBedarfFromJSON,
    LangfristigerPlanungsursaechlicherBedarfFromJSONTyped,
    LangfristigerPlanungsursaechlicherBedarfToJSON,
} from './LangfristigerPlanungsursaechlicherBedarf';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
} from './Link';

/**
 * 
 * @export
 * @interface EntityModelAbfragevarianteWeiteresVerfahren
 */
export interface EntityModelAbfragevarianteWeiteresVerfahren {
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    createdDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    lastModifiedDateTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    abfragevariantenNr?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    name?: string;
    /**
     * 
     * @type {Date}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    satzungsbeschluss?: Date;
    /**
     * 
     * @type {Array<string>}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    wesentlicheRechtsgrundlage?: Array<EntityModelAbfragevarianteWeiteresVerfahrenWesentlicheRechtsgrundlageEnum>;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    wesentlicheRechtsgrundlageFreieEingabe?: string;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    realisierungVon?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    gfWohnenGesamt?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    gfWohnenBaurechtlichGenehmigt?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    gfWohnenBaurechtlichFestgesetzt?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    gfWohnenSobonUrsaechlich?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    gfWohnenBestandswohnbaurecht?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    gfWohnenSonderwohnformen?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    gfWohnenStudentischesWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    gfWohnenSeniorinnenWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    gfWohnenGenossenschaftlichesWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    gfWohnenPlanungsursaechlich?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    weGesamt?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    weBaurechtlichGenehmigt?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    weBaurechtlichFestgesetzt?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    weSonderwohnformen?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    weStudentischesWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    weSeniorinnenWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    weGenossenschaftlichesWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    weWeiteresNichtInfrastrukturrelevantesWohnen?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    sobonOrientierungswertJahr?: EntityModelAbfragevarianteWeiteresVerfahrenSobonOrientierungswertJahrEnum;
    /**
     * 
     * @type {Date}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    stammdatenGueltigAb?: Date;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    anmerkung?: string;
    /**
     * 
     * @type {LangfristigerPlanungsursaechlicherBedarf}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    langfristigerPlanungsursaechlicherBedarf?: LangfristigerPlanungsursaechlicherBedarf;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    artAbfragevariante?: EntityModelAbfragevarianteWeiteresVerfahrenArtAbfragevarianteEnum;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof EntityModelAbfragevarianteWeiteresVerfahren
     */
    links?: { [key: string]: Link; };
}


/**
 * @export
 */
export const EntityModelAbfragevarianteWeiteresVerfahrenWesentlicheRechtsgrundlageEnum = {
    QualifizierterBebauungsplan: 'QUALIFIZIERTER_BEBAUUNGSPLAN',
    VorhabensbezogenerBebauungsplan: 'VORHABENSBEZOGENER_BEBAUUNGSPLAN',
    EinfacherBebauungsplanParagraph30: 'EINFACHER_BEBAUUNGSPLAN_PARAGRAPH_30',
    EinfacherBebauungsplanParagraph30Ivm3435: 'EINFACHER_BEBAUUNGSPLAN_PARAGRAPH_30_IVM_34_35',
    SektoralerBebauungsplanParagraph9: 'SEKTORALER_BEBAUUNGSPLAN_PARAGRAPH_9',
    SektoralerBebauungsplanParagraph30Ivm3435: 'SEKTORALER_BEBAUUNGSPLAN_PARAGRAPH_30_IVM_34_35',
    Innenbereich: 'INNENBEREICH',
    Aussenbereich: 'AUSSENBEREICH',
    Befreiung: 'BEFREIUNG',
    InfoFehlt: 'INFO_FEHLT',
    FreieEingabe: 'FREIE_EINGABE'
} as const;
export type EntityModelAbfragevarianteWeiteresVerfahrenWesentlicheRechtsgrundlageEnum = typeof EntityModelAbfragevarianteWeiteresVerfahrenWesentlicheRechtsgrundlageEnum[keyof typeof EntityModelAbfragevarianteWeiteresVerfahrenWesentlicheRechtsgrundlageEnum];

/**
 * @export
 */
export const EntityModelAbfragevarianteWeiteresVerfahrenSobonOrientierungswertJahrEnum = {
    Unspecified: 'UNSPECIFIED',
    Jahr2014: 'JAHR_2014',
    Jahr2017: 'JAHR_2017',
    Jahr2022: 'JAHR_2022',
    Standortabfrage: 'STANDORTABFRAGE'
} as const;
export type EntityModelAbfragevarianteWeiteresVerfahrenSobonOrientierungswertJahrEnum = typeof EntityModelAbfragevarianteWeiteresVerfahrenSobonOrientierungswertJahrEnum[keyof typeof EntityModelAbfragevarianteWeiteresVerfahrenSobonOrientierungswertJahrEnum];

/**
 * @export
 */
export const EntityModelAbfragevarianteWeiteresVerfahrenArtAbfragevarianteEnum = {
    Unspecified: 'UNSPECIFIED',
    Bauleitplanverfahren: 'BAULEITPLANVERFAHREN',
    Baugenehmigungsverfahren: 'BAUGENEHMIGUNGSVERFAHREN',
    WeiteresVerfahren: 'WEITERES_VERFAHREN'
} as const;
export type EntityModelAbfragevarianteWeiteresVerfahrenArtAbfragevarianteEnum = typeof EntityModelAbfragevarianteWeiteresVerfahrenArtAbfragevarianteEnum[keyof typeof EntityModelAbfragevarianteWeiteresVerfahrenArtAbfragevarianteEnum];


/**
 * Check if a given object implements the EntityModelAbfragevarianteWeiteresVerfahren interface.
 */
export function instanceOfEntityModelAbfragevarianteWeiteresVerfahren(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function EntityModelAbfragevarianteWeiteresVerfahrenFromJSON(json: any): EntityModelAbfragevarianteWeiteresVerfahren {
    return EntityModelAbfragevarianteWeiteresVerfahrenFromJSONTyped(json, false);
}

export function EntityModelAbfragevarianteWeiteresVerfahrenFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityModelAbfragevarianteWeiteresVerfahren {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'version': !exists(json, 'version') ? undefined : json['version'],
        'createdDateTime': !exists(json, 'createdDateTime') ? undefined : (new Date(json['createdDateTime'])),
        'lastModifiedDateTime': !exists(json, 'lastModifiedDateTime') ? undefined : (new Date(json['lastModifiedDateTime'])),
        'abfragevariantenNr': !exists(json, 'abfragevariantenNr') ? undefined : json['abfragevariantenNr'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'satzungsbeschluss': !exists(json, 'satzungsbeschluss') ? undefined : (new Date(json['satzungsbeschluss'])),
        'wesentlicheRechtsgrundlage': !exists(json, 'wesentlicheRechtsgrundlage') ? undefined : json['wesentlicheRechtsgrundlage'],
        'wesentlicheRechtsgrundlageFreieEingabe': !exists(json, 'wesentlicheRechtsgrundlageFreieEingabe') ? undefined : json['wesentlicheRechtsgrundlageFreieEingabe'],
        'realisierungVon': !exists(json, 'realisierungVon') ? undefined : json['realisierungVon'],
        'gfWohnenGesamt': !exists(json, 'gfWohnenGesamt') ? undefined : json['gfWohnenGesamt'],
        'gfWohnenBaurechtlichGenehmigt': !exists(json, 'gfWohnenBaurechtlichGenehmigt') ? undefined : json['gfWohnenBaurechtlichGenehmigt'],
        'gfWohnenBaurechtlichFestgesetzt': !exists(json, 'gfWohnenBaurechtlichFestgesetzt') ? undefined : json['gfWohnenBaurechtlichFestgesetzt'],
        'gfWohnenSobonUrsaechlich': !exists(json, 'gfWohnenSobonUrsaechlich') ? undefined : json['gfWohnenSobonUrsaechlich'],
        'gfWohnenBestandswohnbaurecht': !exists(json, 'gfWohnenBestandswohnbaurecht') ? undefined : json['gfWohnenBestandswohnbaurecht'],
        'gfWohnenSonderwohnformen': !exists(json, 'gfWohnenSonderwohnformen') ? undefined : json['gfWohnenSonderwohnformen'],
        'gfWohnenStudentischesWohnen': !exists(json, 'gfWohnenStudentischesWohnen') ? undefined : json['gfWohnenStudentischesWohnen'],
        'gfWohnenSeniorinnenWohnen': !exists(json, 'gfWohnenSeniorinnenWohnen') ? undefined : json['gfWohnenSeniorinnenWohnen'],
        'gfWohnenGenossenschaftlichesWohnen': !exists(json, 'gfWohnenGenossenschaftlichesWohnen') ? undefined : json['gfWohnenGenossenschaftlichesWohnen'],
        'gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen': !exists(json, 'gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen') ? undefined : json['gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen'],
        'gfWohnenPlanungsursaechlich': !exists(json, 'gfWohnenPlanungsursaechlich') ? undefined : json['gfWohnenPlanungsursaechlich'],
        'weGesamt': !exists(json, 'weGesamt') ? undefined : json['weGesamt'],
        'weBaurechtlichGenehmigt': !exists(json, 'weBaurechtlichGenehmigt') ? undefined : json['weBaurechtlichGenehmigt'],
        'weBaurechtlichFestgesetzt': !exists(json, 'weBaurechtlichFestgesetzt') ? undefined : json['weBaurechtlichFestgesetzt'],
        'weSonderwohnformen': !exists(json, 'weSonderwohnformen') ? undefined : json['weSonderwohnformen'],
        'weStudentischesWohnen': !exists(json, 'weStudentischesWohnen') ? undefined : json['weStudentischesWohnen'],
        'weSeniorinnenWohnen': !exists(json, 'weSeniorinnenWohnen') ? undefined : json['weSeniorinnenWohnen'],
        'weGenossenschaftlichesWohnen': !exists(json, 'weGenossenschaftlichesWohnen') ? undefined : json['weGenossenschaftlichesWohnen'],
        'weWeiteresNichtInfrastrukturrelevantesWohnen': !exists(json, 'weWeiteresNichtInfrastrukturrelevantesWohnen') ? undefined : json['weWeiteresNichtInfrastrukturrelevantesWohnen'],
        'sobonOrientierungswertJahr': !exists(json, 'sobonOrientierungswertJahr') ? undefined : json['sobonOrientierungswertJahr'],
        'stammdatenGueltigAb': !exists(json, 'stammdatenGueltigAb') ? undefined : (new Date(json['stammdatenGueltigAb'])),
        'anmerkung': !exists(json, 'anmerkung') ? undefined : json['anmerkung'],
        'langfristigerPlanungsursaechlicherBedarf': !exists(json, 'langfristigerPlanungsursaechlicherBedarf') ? undefined : LangfristigerPlanungsursaechlicherBedarfFromJSON(json['langfristigerPlanungsursaechlicherBedarf']),
        'artAbfragevariante': !exists(json, 'artAbfragevariante') ? undefined : json['artAbfragevariante'],
        'links': !exists(json, '_links') ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function EntityModelAbfragevarianteWeiteresVerfahrenToJSON(value?: EntityModelAbfragevarianteWeiteresVerfahren | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'version': value.version,
        'createdDateTime': value.createdDateTime === undefined ? undefined : (value.createdDateTime.toISOString()),
        'lastModifiedDateTime': value.lastModifiedDateTime === undefined ? undefined : (value.lastModifiedDateTime.toISOString()),
        'abfragevariantenNr': value.abfragevariantenNr,
        'name': value.name,
        'satzungsbeschluss': value.satzungsbeschluss === undefined ? undefined : (value.satzungsbeschluss.toISOString().substr(0,10)),
        'wesentlicheRechtsgrundlage': value.wesentlicheRechtsgrundlage,
        'wesentlicheRechtsgrundlageFreieEingabe': value.wesentlicheRechtsgrundlageFreieEingabe,
        'realisierungVon': value.realisierungVon,
        'gfWohnenGesamt': value.gfWohnenGesamt,
        'gfWohnenBaurechtlichGenehmigt': value.gfWohnenBaurechtlichGenehmigt,
        'gfWohnenBaurechtlichFestgesetzt': value.gfWohnenBaurechtlichFestgesetzt,
        'gfWohnenSobonUrsaechlich': value.gfWohnenSobonUrsaechlich,
        'gfWohnenBestandswohnbaurecht': value.gfWohnenBestandswohnbaurecht,
        'gfWohnenSonderwohnformen': value.gfWohnenSonderwohnformen,
        'gfWohnenStudentischesWohnen': value.gfWohnenStudentischesWohnen,
        'gfWohnenSeniorinnenWohnen': value.gfWohnenSeniorinnenWohnen,
        'gfWohnenGenossenschaftlichesWohnen': value.gfWohnenGenossenschaftlichesWohnen,
        'gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen': value.gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen,
        'gfWohnenPlanungsursaechlich': value.gfWohnenPlanungsursaechlich,
        'weGesamt': value.weGesamt,
        'weBaurechtlichGenehmigt': value.weBaurechtlichGenehmigt,
        'weBaurechtlichFestgesetzt': value.weBaurechtlichFestgesetzt,
        'weSonderwohnformen': value.weSonderwohnformen,
        'weStudentischesWohnen': value.weStudentischesWohnen,
        'weSeniorinnenWohnen': value.weSeniorinnenWohnen,
        'weGenossenschaftlichesWohnen': value.weGenossenschaftlichesWohnen,
        'weWeiteresNichtInfrastrukturrelevantesWohnen': value.weWeiteresNichtInfrastrukturrelevantesWohnen,
        'sobonOrientierungswertJahr': value.sobonOrientierungswertJahr,
        'stammdatenGueltigAb': value.stammdatenGueltigAb === undefined ? undefined : (value.stammdatenGueltigAb.toISOString().substr(0,10)),
        'anmerkung': value.anmerkung,
        'langfristigerPlanungsursaechlicherBedarf': LangfristigerPlanungsursaechlicherBedarfToJSON(value.langfristigerPlanungsursaechlicherBedarf),
        'artAbfragevariante': value.artAbfragevariante,
        '_links': value.links === undefined ? undefined : (mapValues(value.links, LinkToJSON)),
    };
}

