/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MultiPolygonGeometry } from './MultiPolygonGeometry';
import {
    MultiPolygonGeometryFromJSON,
    MultiPolygonGeometryFromJSONTyped,
    MultiPolygonGeometryToJSON,
    MultiPolygonGeometryToJSONTyped,
} from './MultiPolygonGeometry';

/**
 * 
 * @export
 * @interface Flurstueck
 */
export interface Flurstueck {
    /**
     * 
     * @type {string}
     * @memberof Flurstueck
     */
    nummer?: string;
    /**
     * 
     * @type {number}
     * @memberof Flurstueck
     */
    flaecheQm?: number;
    /**
     * 
     * @type {number}
     * @memberof Flurstueck
     */
    zaehler?: number;
    /**
     * 
     * @type {number}
     * @memberof Flurstueck
     */
    nenner?: number;
    /**
     * 
     * @type {number}
     * @memberof Flurstueck
     */
    eigentumsart?: number;
    /**
     * 
     * @type {string}
     * @memberof Flurstueck
     */
    eigentumsartBedeutung?: string;
    /**
     * 
     * @type {number}
     * @memberof Flurstueck
     */
    gemarkungNummer?: number;
    /**
     * 
     * @type {MultiPolygonGeometry}
     * @memberof Flurstueck
     */
    multiPolygon?: MultiPolygonGeometry;
}

/**
 * Check if a given object implements the Flurstueck interface.
 */
export function instanceOfFlurstueck(value: object): value is Flurstueck {
    return true;
}

export function FlurstueckFromJSON(json: any): Flurstueck {
    return FlurstueckFromJSONTyped(json, false);
}

export function FlurstueckFromJSONTyped(json: any, ignoreDiscriminator: boolean): Flurstueck {
    if (json == null) {
        return json;
    }
    return {
        
        'nummer': json['nummer'] == null ? undefined : json['nummer'],
        'flaecheQm': json['flaecheQm'] == null ? undefined : json['flaecheQm'],
        'zaehler': json['zaehler'] == null ? undefined : json['zaehler'],
        'nenner': json['nenner'] == null ? undefined : json['nenner'],
        'eigentumsart': json['eigentumsart'] == null ? undefined : json['eigentumsart'],
        'eigentumsartBedeutung': json['eigentumsartBedeutung'] == null ? undefined : json['eigentumsartBedeutung'],
        'gemarkungNummer': json['gemarkungNummer'] == null ? undefined : json['gemarkungNummer'],
        'multiPolygon': json['multiPolygon'] == null ? undefined : MultiPolygonGeometryFromJSON(json['multiPolygon']),
    };
}

export function FlurstueckToJSON(json: any): Flurstueck {
    return FlurstueckToJSONTyped(json, false);
}

export function FlurstueckToJSONTyped(value?: Flurstueck | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'nummer': value['nummer'],
        'flaecheQm': value['flaecheQm'],
        'zaehler': value['zaehler'],
        'nenner': value['nenner'],
        'eigentumsart': value['eigentumsart'],
        'eigentumsartBedeutung': value['eigentumsartBedeutung'],
        'gemarkungNummer': value['gemarkungNummer'],
        'multiPolygon': MultiPolygonGeometryToJSON(value['multiPolygon']),
    };
}

