/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { SearchResultDto } from './SearchResultDto';
import {
    SearchResultDtoFromJSON,
    SearchResultDtoFromJSONTyped,
    SearchResultDtoToJSON,
} from './SearchResultDto';

import {
} from './';

/**
 * 
 * @export
 * @interface InfrastruktureinrichtungSearchResultDto
 */
export interface InfrastruktureinrichtungSearchResultDto extends SearchResultDto {
    /**
     * 
     * @type {string}
     * @memberof InfrastruktureinrichtungSearchResultDto
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof InfrastruktureinrichtungSearchResultDto
     */
    nameEinrichtung?: string;
    /**
     * 
     * @type {string}
     * @memberof InfrastruktureinrichtungSearchResultDto
     */
    infrastruktureinrichtungTyp?: InfrastruktureinrichtungSearchResultDtoInfrastruktureinrichtungTypEnum;
}


/**
 * @export
 */
export const InfrastruktureinrichtungSearchResultDtoInfrastruktureinrichtungTypEnum = {
    Unspecified: 'UNSPECIFIED',
    Kinderkrippe: 'KINDERKRIPPE',
    Kindergarten: 'KINDERGARTEN',
    GsNachmittagBetreuung: 'GS_NACHMITTAG_BETREUUNG',
    HausFuerKinder: 'HAUS_FUER_KINDER',
    Grundschule: 'GRUNDSCHULE',
    Mittelschule: 'MITTELSCHULE'
} as const;
export type InfrastruktureinrichtungSearchResultDtoInfrastruktureinrichtungTypEnum = typeof InfrastruktureinrichtungSearchResultDtoInfrastruktureinrichtungTypEnum[keyof typeof InfrastruktureinrichtungSearchResultDtoInfrastruktureinrichtungTypEnum];


/**
 * Check if a given object implements the InfrastruktureinrichtungSearchResultDto interface.
 */
export function instanceOfInfrastruktureinrichtungSearchResultDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function InfrastruktureinrichtungSearchResultDtoFromJSON(json: any): InfrastruktureinrichtungSearchResultDto {
    return InfrastruktureinrichtungSearchResultDtoFromJSONTyped(json, false);
}

export function InfrastruktureinrichtungSearchResultDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): InfrastruktureinrichtungSearchResultDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    if (!ignoreDiscriminator) {
    }
    return {
        ...SearchResultDtoFromJSONTyped(json, ignoreDiscriminator),
        'id': !exists(json, 'id') ? undefined : json['id'],
        'nameEinrichtung': !exists(json, 'nameEinrichtung') ? undefined : json['nameEinrichtung'],
        'infrastruktureinrichtungTyp': !exists(json, 'infrastruktureinrichtungTyp') ? undefined : json['infrastruktureinrichtungTyp'],
    };
}

export function InfrastruktureinrichtungSearchResultDtoToJSON(value?: InfrastruktureinrichtungSearchResultDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        ...SearchResultDtoToJSON(value),
        'id': value.id,
        'nameEinrichtung': value.nameEinrichtung,
        'infrastruktureinrichtungTyp': value.infrastruktureinrichtungTyp,
    };
}

