/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Serivce für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KindergartenDtoAllOf
 */
export interface KindergartenDtoAllOf {
    /**
     * 
     * @type {number}
     * @memberof KindergartenDtoAllOf
     */
    anzahlKindergartenPlaetze?: number;
    /**
     * 
     * @type {number}
     * @memberof KindergartenDtoAllOf
     */
    anzahlKindergartenGruppen?: number;
    /**
     * 
     * @type {number}
     * @memberof KindergartenDtoAllOf
     */
    wohnungsnaheKindergartenPlaetze?: number;
}

export function KindergartenDtoAllOfFromJSON(json: any): KindergartenDtoAllOf {
    return KindergartenDtoAllOfFromJSONTyped(json, false);
}

export function KindergartenDtoAllOfFromJSONTyped(json: any, ignoreDiscriminator: boolean): KindergartenDtoAllOf {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'anzahlKindergartenPlaetze': !exists(json, 'anzahlKindergartenPlaetze') ? undefined : json['anzahlKindergartenPlaetze'],
        'anzahlKindergartenGruppen': !exists(json, 'anzahlKindergartenGruppen') ? undefined : json['anzahlKindergartenGruppen'],
        'wohnungsnaheKindergartenPlaetze': !exists(json, 'wohnungsnaheKindergartenPlaetze') ? undefined : json['wohnungsnaheKindergartenPlaetze'],
    };
}

export function KindergartenDtoAllOfToJSON(value?: KindergartenDtoAllOf | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'anzahlKindergartenPlaetze': value.anzahlKindergartenPlaetze,
        'anzahlKindergartenGruppen': value.anzahlKindergartenGruppen,
        'wohnungsnaheKindergartenPlaetze': value.wohnungsnaheKindergartenPlaetze,
    };
}

