/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Serivce für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from "../runtime";
import {
  InfrastruktureinrichtungDto,
  InfrastruktureinrichtungDtoFromJSON,
  InfrastruktureinrichtungDtoFromJSONTyped,
  InfrastruktureinrichtungDtoToJSON,
} from "./InfrastruktureinrichtungDto";

/**
 *
 * @export
 * @interface KindergartenDto
 */
export interface KindergartenDto {
  /**
   *
   * @type {string}
   * @memberof KindergartenDto
   */
  id?: string;
  /**
   *
   * @type {number}
   * @memberof KindergartenDto
   */
  version?: number;
  /**
   *
   * @type {Date}
   * @memberof KindergartenDto
   */
  createdDateTime?: Date;
  /**
   *
   * @type {Date}
   * @memberof KindergartenDto
   */
  lastModifiedDateTime?: Date;
  /**
   *
   * @type {InfrastruktureinrichtungDto}
   * @memberof KindergartenDto
   */
  infrastruktureinrichtung: InfrastruktureinrichtungDto;
  /**
   *
   * @type {number}
   * @memberof KindergartenDto
   */
  anzahlKindergartenPlaetze: number;
  /**
   *
   * @type {number}
   * @memberof KindergartenDto
   */
  anzahlKindergartenGruppen: number;
  /**
   *
   * @type {number}
   * @memberof KindergartenDto
   */
  wohnungsnaheKindergartenPlaetze?: number;
}

export function KindergartenDtoFromJSON(json: any): KindergartenDto {
  return KindergartenDtoFromJSONTyped(json, false);
}

export function KindergartenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): KindergartenDto {
  if (json === undefined || json === null) {
    return json;
  }
  return {
    id: !exists(json, "id") ? undefined : json["id"],
    version: !exists(json, "version") ? undefined : json["version"],
    createdDateTime: !exists(json, "createdDateTime") ? undefined : new Date(json["createdDateTime"]),
    lastModifiedDateTime: !exists(json, "lastModifiedDateTime") ? undefined : new Date(json["lastModifiedDateTime"]),
    infrastruktureinrichtung: InfrastruktureinrichtungDtoFromJSON(json["infrastruktureinrichtung"]),
    anzahlKindergartenPlaetze: json["anzahlKindergartenPlaetze"],
    anzahlKindergartenGruppen: json["anzahlKindergartenGruppen"],
    wohnungsnaheKindergartenPlaetze: !exists(json, "wohnungsnaheKindergartenPlaetze")
      ? undefined
      : json["wohnungsnaheKindergartenPlaetze"],
  };
}

export function KindergartenDtoToJSON(value?: KindergartenDto | null): any {
  if (value === undefined) {
    return undefined;
  }
  if (value === null) {
    return null;
  }
  return {
    id: value.id,
    version: value.version,
    createdDateTime: value.createdDateTime === undefined ? undefined : value.createdDateTime.toISOString(),
    lastModifiedDateTime:
      value.lastModifiedDateTime === undefined ? undefined : value.lastModifiedDateTime.toISOString(),
    infrastruktureinrichtung: InfrastruktureinrichtungDtoToJSON(value.infrastruktureinrichtung),
    anzahlKindergartenPlaetze: value.anzahlKindergartenPlaetze,
    anzahlKindergartenGruppen: value.anzahlKindergartenGruppen,
    wohnungsnaheKindergartenPlaetze: value.wohnungsnaheKindergartenPlaetze,
  };
}
