/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.1.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EntityModelGlobalCounter } from './EntityModelGlobalCounter';
import {
    EntityModelGlobalCounterFromJSON,
    EntityModelGlobalCounterFromJSONTyped,
    EntityModelGlobalCounterToJSON,
} from './EntityModelGlobalCounter';

/**
 * 
 * @export
 * @interface PagedModelEntityModelGlobalCounterEmbedded
 */
export interface PagedModelEntityModelGlobalCounterEmbedded {
    /**
     * 
     * @type {Array<EntityModelGlobalCounter>}
     * @memberof PagedModelEntityModelGlobalCounterEmbedded
     */
    globalCounters?: Array<EntityModelGlobalCounter>;
}

/**
 * Check if a given object implements the PagedModelEntityModelGlobalCounterEmbedded interface.
 */
export function instanceOfPagedModelEntityModelGlobalCounterEmbedded(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PagedModelEntityModelGlobalCounterEmbeddedFromJSON(json: any): PagedModelEntityModelGlobalCounterEmbedded {
    return PagedModelEntityModelGlobalCounterEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelGlobalCounterEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelGlobalCounterEmbedded {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'globalCounters': !exists(json, 'globalCounters') ? undefined : ((json['globalCounters'] as Array<any>).map(EntityModelGlobalCounterFromJSON)),
    };
}

export function PagedModelEntityModelGlobalCounterEmbeddedToJSON(value?: PagedModelEntityModelGlobalCounterEmbedded | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'globalCounters': value.globalCounters === undefined ? undefined : ((value.globalCounters as Array<any>).map(EntityModelGlobalCounterToJSON)),
    };
}

