/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { EntityModelFoerdermixStamm } from './EntityModelFoerdermixStamm';
import {
    EntityModelFoerdermixStammFromJSON,
    EntityModelFoerdermixStammFromJSONTyped,
    EntityModelFoerdermixStammToJSON,
} from './EntityModelFoerdermixStamm';

/**
 * 
 * @export
 * @interface PagedModelEntityModelFoerdermixStammEmbedded
 */
export interface PagedModelEntityModelFoerdermixStammEmbedded {
    /**
     * 
     * @type {Array<EntityModelFoerdermixStamm>}
     * @memberof PagedModelEntityModelFoerdermixStammEmbedded
     */
    foerdermixStamms?: Array<EntityModelFoerdermixStamm>;
}

/**
 * Check if a given object implements the PagedModelEntityModelFoerdermixStammEmbedded interface.
 */
export function instanceOfPagedModelEntityModelFoerdermixStammEmbedded(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function PagedModelEntityModelFoerdermixStammEmbeddedFromJSON(json: any): PagedModelEntityModelFoerdermixStammEmbedded {
    return PagedModelEntityModelFoerdermixStammEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelFoerdermixStammEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelFoerdermixStammEmbedded {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'foerdermixStamms': !exists(json, 'foerdermixStamms') ? undefined : ((json['foerdermixStamms'] as Array<any>).map(EntityModelFoerdermixStammFromJSON)),
    };
}

export function PagedModelEntityModelFoerdermixStammEmbeddedToJSON(value?: PagedModelEntityModelFoerdermixStammEmbedded | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'foerdermixStamms': value.foerdermixStamms === undefined ? undefined : ((value.foerdermixStamms as Array<any>).map(EntityModelFoerdermixStammToJSON)),
    };
}

