/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 2.0.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import {
    BaugenehmigungsverfahrenInBearbeitungSachbearbeitungDto,
    BaugenehmigungsverfahrenInBearbeitungSachbearbeitungDtoFromJSON,
    BaugenehmigungsverfahrenInBearbeitungSachbearbeitungDtoFromJSONTyped,
    BaugenehmigungsverfahrenInBearbeitungSachbearbeitungDtoToJSON,
} from './BaugenehmigungsverfahrenInBearbeitungSachbearbeitungDto';
import {
    BauleitplanverfahrenInBearbeitungSachbearbeitungDto,
    BauleitplanverfahrenInBearbeitungSachbearbeitungDtoFromJSON,
    BauleitplanverfahrenInBearbeitungSachbearbeitungDtoFromJSONTyped,
    BauleitplanverfahrenInBearbeitungSachbearbeitungDtoToJSON,
} from './BauleitplanverfahrenInBearbeitungSachbearbeitungDto';
import {
    WeiteresVerfahrenInBearbeitungSachbearbeitungDto,
    WeiteresVerfahrenInBearbeitungSachbearbeitungDtoFromJSON,
    WeiteresVerfahrenInBearbeitungSachbearbeitungDtoFromJSONTyped,
    WeiteresVerfahrenInBearbeitungSachbearbeitungDtoToJSON,
} from './WeiteresVerfahrenInBearbeitungSachbearbeitungDto';

/**
 * @type PatchInBearbeitungSachbearbeitungRequest
 * 
 * @export
 */
export type PatchInBearbeitungSachbearbeitungRequest = BaugenehmigungsverfahrenInBearbeitungSachbearbeitungDto | BauleitplanverfahrenInBearbeitungSachbearbeitungDto | WeiteresVerfahrenInBearbeitungSachbearbeitungDto;

export function PatchInBearbeitungSachbearbeitungRequestFromJSON(json: any): PatchInBearbeitungSachbearbeitungRequest {
    return PatchInBearbeitungSachbearbeitungRequestFromJSONTyped(json, false);
}

export function PatchInBearbeitungSachbearbeitungRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatchInBearbeitungSachbearbeitungRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return { ...BaugenehmigungsverfahrenInBearbeitungSachbearbeitungDtoFromJSONTyped(json, true), ...BauleitplanverfahrenInBearbeitungSachbearbeitungDtoFromJSONTyped(json, true), ...WeiteresVerfahrenInBearbeitungSachbearbeitungDtoFromJSONTyped(json, true) };
}

export function PatchInBearbeitungSachbearbeitungRequestToJSON(value?: PatchInBearbeitungSachbearbeitungRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return { ...BaugenehmigungsverfahrenInBearbeitungSachbearbeitungDtoToJSON(value), ...BauleitplanverfahrenInBearbeitungSachbearbeitungDtoToJSON(value), ...WeiteresVerfahrenInBearbeitungSachbearbeitungDtoToJSON(value) };
}

