/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PointGeometryDto
 */
export interface PointGeometryDto {
    /**
     * 
     * @type {string}
     * @memberof PointGeometryDto
     */
    type: string;
    /**
     * Die Punktkoordinate ([x,y] bzw. [longitude, latitude]) im Standard EPSG:4326 (WGS84).
     * @type {Array<number>}
     * @memberof PointGeometryDto
     */
    coordinates: Array<number>;
}

/**
 * Check if a given object implements the PointGeometryDto interface.
 */
export function instanceOfPointGeometryDto(value: object): value is PointGeometryDto {
    if (!('type' in value) || value['type'] === undefined) return false;
    if (!('coordinates' in value) || value['coordinates'] === undefined) return false;
    return true;
}

export function PointGeometryDtoFromJSON(json: any): PointGeometryDto {
    return PointGeometryDtoFromJSONTyped(json, false);
}

export function PointGeometryDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): PointGeometryDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'],
        'coordinates': json['coordinates'],
    };
}

export function PointGeometryDtoToJSON(json: any): PointGeometryDto {
    return PointGeometryDtoToJSONTyped(json, false);
}

export function PointGeometryDtoToJSONTyped(value?: PointGeometryDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'coordinates': value['coordinates'],
    };
}

