/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Serivce für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SachbearbeitungAbfragevarianteOffenInBearbeitungDto
 */
export interface SachbearbeitungAbfragevarianteOffenInBearbeitungDto {
    /**
     * 
     * @type {string}
     * @memberof SachbearbeitungAbfragevarianteOffenInBearbeitungDto
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof SachbearbeitungAbfragevarianteOffenInBearbeitungDto
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof SachbearbeitungAbfragevarianteOffenInBearbeitungDto
     */
    createdDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof SachbearbeitungAbfragevarianteOffenInBearbeitungDto
     */
    lastModifiedDateTime?: Date;
    /**
     * 
     * @type {boolean}
     * @memberof SachbearbeitungAbfragevarianteOffenInBearbeitungDto
     */
    relevant?: boolean;
}

export function SachbearbeitungAbfragevarianteOffenInBearbeitungDtoFromJSON(json: any): SachbearbeitungAbfragevarianteOffenInBearbeitungDto {
    return SachbearbeitungAbfragevarianteOffenInBearbeitungDtoFromJSONTyped(json, false);
}

export function SachbearbeitungAbfragevarianteOffenInBearbeitungDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): SachbearbeitungAbfragevarianteOffenInBearbeitungDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'createdDateTime': !exists(json, 'createdDateTime') ? undefined : (new Date(json['createdDateTime'])),
        'lastModifiedDateTime': !exists(json, 'lastModifiedDateTime') ? undefined : (new Date(json['lastModifiedDateTime'])),
        'relevant': !exists(json, 'relevant') ? undefined : json['relevant'],
    };
}

export function SachbearbeitungAbfragevarianteOffenInBearbeitungDtoToJSON(value?: SachbearbeitungAbfragevarianteOffenInBearbeitungDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'version': value.version,
        'createdDateTime': value.createdDateTime === undefined ? undefined : (value.createdDateTime.toISOString()),
        'lastModifiedDateTime': value.lastModifiedDateTime === undefined ? undefined : (value.lastModifiedDateTime.toISOString()),
        'relevant': value.relevant,
    };
}

