/* tslint:disable */
/* eslint-disable */
/**
 * OpenAPI definition
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    MultiPolygonGeometryModel,
    MultiPolygonGeometryModelFromJSON,
    MultiPolygonGeometryModelFromJSONTyped,
    MultiPolygonGeometryModelToJSON,
} from './MultiPolygonGeometryModel';

/**
 * 
 * @export
 * @interface StadtbezirkModel
 */
export interface StadtbezirkModel {
    /**
     * 
     * @type {string}
     * @memberof StadtbezirkModel
     */
    nummer?: string;
    /**
     * 
     * @type {string}
     * @memberof StadtbezirkModel
     */
    name?: string;
    /**
     * 
     * @type {MultiPolygonGeometryModel}
     * @memberof StadtbezirkModel
     */
    multiPolygon?: MultiPolygonGeometryModel;
}

export function StadtbezirkModelFromJSON(json: any): StadtbezirkModel {
    return StadtbezirkModelFromJSONTyped(json, false);
}

export function StadtbezirkModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): StadtbezirkModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'nummer': !exists(json, 'nummer') ? undefined : json['nummer'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'multiPolygon': !exists(json, 'multiPolygon') ? undefined : MultiPolygonGeometryModelFromJSON(json['multiPolygon']),
    };
}

export function StadtbezirkModelToJSON(value?: StadtbezirkModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'nummer': value.nummer,
        'name': value.name,
        'multiPolygon': MultiPolygonGeometryModelToJSON(value.multiPolygon),
    };
}

