/* tslint:disable */
/* eslint-disable */
/**
 * ISI GEODATA EAI
 * ISI GEODATA EAI - Service zum Abfragen von Geoinformationen
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BebauungsplanUmgriffDto
 */
export interface BebauungsplanUmgriffDto {
    /**
     * 
     * @type {number}
     * @memberof BebauungsplanUmgriffDto
     */
    objectId?: number;
    /**
     * 
     * @type {number}
     * @memberof BebauungsplanUmgriffDto
     */
    ebene?: number;
    /**
     * 
     * @type {string}
     * @memberof BebauungsplanUmgriffDto
     */
    nrVa?: string;
    /**
     * 
     * @type {string}
     * @memberof BebauungsplanUmgriffDto
     */
    nrPlan?: string;
    /**
     * 
     * @type {string}
     * @memberof BebauungsplanUmgriffDto
     */
    nr?: string;
    /**
     * 
     * @type {number}
     * @memberof BebauungsplanUmgriffDto
     */
    flaecheQm?: number;
    /**
     * 
     * @type {string}
     * @memberof BebauungsplanUmgriffDto
     */
    art?: string;
    /**
     * 
     * @type {string}
     * @memberof BebauungsplanUmgriffDto
     */
    artBedeutung?: string;
    /**
     * 
     * @type {string}
     * @memberof BebauungsplanUmgriffDto
     */
    ebeneBedeutung?: string;
}

/**
 * Check if a given object implements the BebauungsplanUmgriffDto interface.
 */
export function instanceOfBebauungsplanUmgriffDto(value: object): value is BebauungsplanUmgriffDto {
    return true;
}

export function BebauungsplanUmgriffDtoFromJSON(json: any): BebauungsplanUmgriffDto {
    return BebauungsplanUmgriffDtoFromJSONTyped(json, false);
}

export function BebauungsplanUmgriffDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BebauungsplanUmgriffDto {
    if (json == null) {
        return json;
    }
    return {
        
        'objectId': json['objectId'] == null ? undefined : json['objectId'],
        'ebene': json['ebene'] == null ? undefined : json['ebene'],
        'nrVa': json['nrVa'] == null ? undefined : json['nrVa'],
        'nrPlan': json['nrPlan'] == null ? undefined : json['nrPlan'],
        'nr': json['nr'] == null ? undefined : json['nr'],
        'flaecheQm': json['flaecheQm'] == null ? undefined : json['flaecheQm'],
        'art': json['art'] == null ? undefined : json['art'],
        'artBedeutung': json['artBedeutung'] == null ? undefined : json['artBedeutung'],
        'ebeneBedeutung': json['ebeneBedeutung'] == null ? undefined : json['ebeneBedeutung'],
    };
}

export function BebauungsplanUmgriffDtoToJSON(json: any): BebauungsplanUmgriffDto {
    return BebauungsplanUmgriffDtoToJSONTyped(json, false);
}

export function BebauungsplanUmgriffDtoToJSONTyped(value?: BebauungsplanUmgriffDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objectId': value['objectId'],
        'ebene': value['ebene'],
        'nrVa': value['nrVa'],
        'nrPlan': value['nrPlan'],
        'nr': value['nr'],
        'flaecheQm': value['flaecheQm'],
        'art': value['art'],
        'artBedeutung': value['artBedeutung'],
        'ebeneBedeutung': value['ebeneBedeutung'],
    };
}

