/* tslint:disable */
/* eslint-disable */
/**
 * ISI GEODATA EAI
 * ISI GEODATA EAI - Service zum Abfragen von Geoinformationen
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KitaplanungsbereichDto } from './KitaplanungsbereichDto';
import {
    KitaplanungsbereichDtoFromJSON,
    KitaplanungsbereichDtoFromJSONTyped,
    KitaplanungsbereichDtoToJSON,
    KitaplanungsbereichDtoToJSONTyped,
} from './KitaplanungsbereichDto';
import type { FeatureDtoViertelDtoGeometry } from './FeatureDtoViertelDtoGeometry';
import {
    FeatureDtoViertelDtoGeometryFromJSON,
    FeatureDtoViertelDtoGeometryFromJSONTyped,
    FeatureDtoViertelDtoGeometryToJSON,
    FeatureDtoViertelDtoGeometryToJSONTyped,
} from './FeatureDtoViertelDtoGeometry';

/**
 * 
 * @export
 * @interface FeatureDtoKitaplanungsbereichDto
 */
export interface FeatureDtoKitaplanungsbereichDto {
    /**
     * 
     * @type {string}
     * @memberof FeatureDtoKitaplanungsbereichDto
     */
    type?: string;
    /**
     * 
     * @type {FeatureDtoViertelDtoGeometry}
     * @memberof FeatureDtoKitaplanungsbereichDto
     */
    geometry?: FeatureDtoViertelDtoGeometry;
    /**
     * 
     * @type {KitaplanungsbereichDto}
     * @memberof FeatureDtoKitaplanungsbereichDto
     */
    properties?: KitaplanungsbereichDto;
}

/**
 * Check if a given object implements the FeatureDtoKitaplanungsbereichDto interface.
 */
export function instanceOfFeatureDtoKitaplanungsbereichDto(value: object): value is FeatureDtoKitaplanungsbereichDto {
    return true;
}

export function FeatureDtoKitaplanungsbereichDtoFromJSON(json: any): FeatureDtoKitaplanungsbereichDto {
    return FeatureDtoKitaplanungsbereichDtoFromJSONTyped(json, false);
}

export function FeatureDtoKitaplanungsbereichDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureDtoKitaplanungsbereichDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'geometry': json['geometry'] == null ? undefined : FeatureDtoViertelDtoGeometryFromJSON(json['geometry']),
        'properties': json['properties'] == null ? undefined : KitaplanungsbereichDtoFromJSON(json['properties']),
    };
}

export function FeatureDtoKitaplanungsbereichDtoToJSON(json: any): FeatureDtoKitaplanungsbereichDto {
    return FeatureDtoKitaplanungsbereichDtoToJSONTyped(json, false);
}

export function FeatureDtoKitaplanungsbereichDtoToJSONTyped(value?: FeatureDtoKitaplanungsbereichDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'geometry': FeatureDtoViertelDtoGeometryToJSON(value['geometry']),
        'properties': KitaplanungsbereichDtoToJSON(value['properties']),
    };
}

