/* tslint:disable */
/* eslint-disable */
/**
 * ISI GEODATA EAI
 * ISI GEODATA EAI - Service zum Abfragen von Geoinformationen
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeatureDtoBebauungsplanUmgriffDto } from './FeatureDtoBebauungsplanUmgriffDto';
import {
    FeatureDtoBebauungsplanUmgriffDtoFromJSON,
    FeatureDtoBebauungsplanUmgriffDtoFromJSONTyped,
    FeatureDtoBebauungsplanUmgriffDtoToJSON,
    FeatureDtoBebauungsplanUmgriffDtoToJSONTyped,
} from './FeatureDtoBebauungsplanUmgriffDto';

/**
 * 
 * @export
 * @interface FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDto
 */
export interface FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDto {
    /**
     * 
     */
    type?: string;
    /**
     * 
     */
    features?: Array<FeatureDtoBebauungsplanUmgriffDto>;
}

/**
 * Check if a given object implements the FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDto interface.
 */
export function instanceOfFeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDto(value: object): value is FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDto {
    return true;
}

export function FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDtoFromJSON(json: any): FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDto {
    return FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDtoFromJSONTyped(json, false);
}

export function FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'features': json['features'] == null ? undefined : ((json['features'] as Array<any>).map(FeatureDtoBebauungsplanUmgriffDtoFromJSON)),
    };
}

export function FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDtoToJSON(json: any): FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDto {
    return FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDtoToJSONTyped(json, false);
}

export function FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDtoToJSONTyped(value?: FeatureCollectionDtoFeatureDtoBebauungsplanUmgriffDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'features': value['features'] == null ? undefined : ((value['features'] as Array<any>).map(FeatureDtoBebauungsplanUmgriffDtoToJSON)),
    };
}

