/* tslint:disable */
/* eslint-disable */
/**
 * ISI GEODATA EAI
 * ISI GEODATA EAI - Service zum Abfragen von Geoinformationen
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GemarkungDto
 */
export interface GemarkungDto {
    /**
     * 
     * @type {number}
     * @memberof GemarkungDto
     */
    objectId?: number;
    /**
     * 
     * @type {string}
     * @memberof GemarkungDto
     */
    oid1?: string;
    /**
     * 
     * @type {number}
     * @memberof GemarkungDto
     */
    gemarkung?: number;
    /**
     * 
     * @type {string}
     * @memberof GemarkungDto
     */
    gemarkungName?: string;
}

/**
 * Check if a given object implements the GemarkungDto interface.
 */
export function instanceOfGemarkungDto(value: object): value is GemarkungDto {
    return true;
}

export function GemarkungDtoFromJSON(json: any): GemarkungDto {
    return GemarkungDtoFromJSONTyped(json, false);
}

export function GemarkungDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GemarkungDto {
    if (json == null) {
        return json;
    }
    return {
        
        'objectId': json['objectId'] == null ? undefined : json['objectId'],
        'oid1': json['oid1'] == null ? undefined : json['oid1'],
        'gemarkung': json['gemarkung'] == null ? undefined : json['gemarkung'],
        'gemarkungName': json['gemarkungName'] == null ? undefined : json['gemarkungName'],
    };
}

export function GemarkungDtoToJSON(json: any): GemarkungDto {
    return GemarkungDtoToJSONTyped(json, false);
}

export function GemarkungDtoToJSONTyped(value?: GemarkungDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objectId': value['objectId'],
        'oid1': value['oid1'],
        'gemarkung': value['gemarkung'],
        'gemarkungName': value['gemarkungName'],
    };
}

