/* tslint:disable */
/* eslint-disable */
/**
 * ISI GEODATA EAI
 * ISI GEODATA EAI - Service zum Abfragen von Geoinformationen
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ViertelDto
 */
export interface ViertelDto {
    /**
     * 
     */
    objectId?: number;
    /**
     * 
     */
    viertelNummer?: string;
    /**
     * 
     */
    flaecheQm?: number;
    /**
     * 
     */
    ycoordinate?: number;
    /**
     * 
     */
    xcoordinate?: number;
}

/**
 * Check if a given object implements the ViertelDto interface.
 */
export function instanceOfViertelDto(value: object): value is ViertelDto {
    return true;
}

export function ViertelDtoFromJSON(json: any): ViertelDto {
    return ViertelDtoFromJSONTyped(json, false);
}

export function ViertelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ViertelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'objectId': json['objectId'] == null ? undefined : json['objectId'],
        'viertelNummer': json['viertelNummer'] == null ? undefined : json['viertelNummer'],
        'flaecheQm': json['flaecheQm'] == null ? undefined : json['flaecheQm'],
        'ycoordinate': json['ycoordinate'] == null ? undefined : json['ycoordinate'],
        'xcoordinate': json['xcoordinate'] == null ? undefined : json['xcoordinate'],
    };
}

export function ViertelDtoToJSON(json: any): ViertelDto {
    return ViertelDtoToJSONTyped(json, false);
}

export function ViertelDtoToJSONTyped(value?: ViertelDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objectId': value['objectId'],
        'viertelNummer': value['viertelNummer'],
        'flaecheQm': value['flaecheQm'],
        'ycoordinate': value['ycoordinate'],
        'xcoordinate': value['xcoordinate'],
    };
}

