spring:
  application.name: @project.artifactId@
  banner.location: banner.txt
  main:
    web-application-type: reactive
  jackson:
    serialization:
      indent-output: on
  session:
    timeout: 36000  # in seconds; Goal: same lifetime as SSO Session (e.g. 10 hours)
  zipkin:
    enabled: false
    sleuth:
      reactor:
        instrumentation-type:  # https://github.com/spring-cloud/spring-cloud-gateway/pull/2106

server:
  port: 8080
  error:
    include-exception: false
    include-stacktrace: never
    include-message: always
    whitelabel:
      enabled: false

management:
  endpoints:
    enabled-by-default: false
    web:
      cors:
        allowedOrigins:
          - "http://localhost:8081"
          - "http://127.0.0.1:8081"
        allowedMethods: "*"
        allowedHeaders: "*"
        allowCredentials: on
        maxAge: 3600
      exposure:
        include: health, info, prometheus
      path-mapping:
        prometheus: metrics
  endpoint:
    health:
      enabled: on
      probes:
        enabled: true
    info:
      enabled: on
    prometheus:
      enabled: on
  info:
    env:
      enabled: true

info.application.name: ${spring.application.name}
info.application.version: @project.version@
info.application.commitHash: ${buildNumber}

services:
  - displayName: Frontend
    infoPath: /actuator/info
    scmUrl: https://github.com/it-at-m/isi-frontend/network
    appendCommitHash: false
  - displayName: Backend
    infoPath: /api/isi-backend-service/actuator/info
    scmUrl: https://github.com/it-at-m/isi-backend/network
    appendCommitHash: false
  - displayName: WFS-EAI
    infoPath: /api/isi-wfs-eai/actuator/info
    scmUrl: https://git.muenchen.de/isi/isi-wfs-eai/-/network/main?utf8=%E2%9C%93&extended_sha1=
    appendCommitHash: true
  - displayName: MAstER-EAI
    infoPath: api/isi-master-eai/actuator/info
    scmUrl: https://git.muenchen.de/isi-master-eai/-/network/main?utf8=%E2%9C%93&extended_sha1=
    appendCommitHash: true
  - displayName: Dokument-EAI
    infoPath: /api/isi-document-storage/actuator/info
    scmUrl: https://git.muenchen.de/isi/isi-document-storage/-/network/main?utf8=%E2%9C%93&extended_sha1=
    appendCommitHash: true
