/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AbfrageRequestBody,
    AbfrageRequestBodyFromJSON,
    AbfrageRequestBodyToJSON,
} from '../models/AbfrageRequestBody';
import {
    type EntityModelAbfrage,
    EntityModelAbfrageFromJSON,
    EntityModelAbfrageToJSON,
} from '../models/EntityModelAbfrage';
import {
    type PagedModelEntityModelAbfrage,
    PagedModelEntityModelAbfrageFromJSON,
    PagedModelEntityModelAbfrageToJSON,
} from '../models/PagedModelEntityModelAbfrage';

export interface DeleteItemResourceAbfrageDeleteRequest {
    id: string;
}

export interface GetCollectionResourceAbfrageGetRequest {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourceAbfrageGetRequest {
    id: string;
}

export interface PatchItemResourceAbfragePatchRequest {
    id: string;
    abfrageRequestBody: AbfrageRequestBody;
}

export interface PostCollectionResourceAbfragePostRequest {
    abfrageRequestBody: AbfrageRequestBody;
}

export interface PutItemResourceAbfragePutRequest {
    id: string;
    abfrageRequestBody: AbfrageRequestBody;
}

/**
 * 
 */
export class AbfrageEntityControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteItemResourceAbfrageDelete without sending the request
     */
    async deleteItemResourceAbfrageDeleteRequestOpts(requestParameters: DeleteItemResourceAbfrageDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourceAbfrageDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/abfrages/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * delete-abfrage
     */
    async deleteItemResourceAbfrageDeleteRaw(requestParameters: DeleteItemResourceAbfrageDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteItemResourceAbfrageDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-abfrage
     */
    async deleteItemResourceAbfrageDelete(requestParameters: DeleteItemResourceAbfrageDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourceAbfrageDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getCollectionResourceAbfrageGet without sending the request
     */
    async getCollectionResourceAbfrageGetRequestOpts(requestParameters: GetCollectionResourceAbfrageGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/abfrages`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get-abfrage
     */
    async getCollectionResourceAbfrageGetRaw(requestParameters: GetCollectionResourceAbfrageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelAbfrage>> {
        const requestOptions = await this.getCollectionResourceAbfrageGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelAbfrageFromJSON(jsonValue));
    }

    /**
     * get-abfrage
     */
    async getCollectionResourceAbfrageGet(requestParameters: GetCollectionResourceAbfrageGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelAbfrage> {
        const response = await this.getCollectionResourceAbfrageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getItemResourceAbfrageGet without sending the request
     */
    async getItemResourceAbfrageGetRequestOpts(requestParameters: GetItemResourceAbfrageGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourceAbfrageGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/abfrages/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get-abfrage
     */
    async getItemResourceAbfrageGetRaw(requestParameters: GetItemResourceAbfrageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelAbfrage>> {
        const requestOptions = await this.getItemResourceAbfrageGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelAbfrageFromJSON(jsonValue));
    }

    /**
     * get-abfrage
     */
    async getItemResourceAbfrageGet(requestParameters: GetItemResourceAbfrageGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelAbfrage> {
        const response = await this.getItemResourceAbfrageGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchItemResourceAbfragePatch without sending the request
     */
    async patchItemResourceAbfragePatchRequestOpts(requestParameters: PatchItemResourceAbfragePatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourceAbfragePatch().'
            );
        }

        if (requestParameters['abfrageRequestBody'] == null) {
            throw new runtime.RequiredError(
                'abfrageRequestBody',
                'Required parameter "abfrageRequestBody" was null or undefined when calling patchItemResourceAbfragePatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/abfrages/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: AbfrageRequestBodyToJSON(requestParameters['abfrageRequestBody']),
        };
    }

    /**
     * patch-abfrage
     */
    async patchItemResourceAbfragePatchRaw(requestParameters: PatchItemResourceAbfragePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelAbfrage>> {
        const requestOptions = await this.patchItemResourceAbfragePatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelAbfrageFromJSON(jsonValue));
    }

    /**
     * patch-abfrage
     */
    async patchItemResourceAbfragePatch(requestParameters: PatchItemResourceAbfragePatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelAbfrage | null | undefined > {
        const response = await this.patchItemResourceAbfragePatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * Creates request options for postCollectionResourceAbfragePost without sending the request
     */
    async postCollectionResourceAbfragePostRequestOpts(requestParameters: PostCollectionResourceAbfragePostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['abfrageRequestBody'] == null) {
            throw new runtime.RequiredError(
                'abfrageRequestBody',
                'Required parameter "abfrageRequestBody" was null or undefined when calling postCollectionResourceAbfragePost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/abfrages`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AbfrageRequestBodyToJSON(requestParameters['abfrageRequestBody']),
        };
    }

    /**
     * create-abfrage
     */
    async postCollectionResourceAbfragePostRaw(requestParameters: PostCollectionResourceAbfragePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelAbfrage>> {
        const requestOptions = await this.postCollectionResourceAbfragePostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelAbfrageFromJSON(jsonValue));
    }

    /**
     * create-abfrage
     */
    async postCollectionResourceAbfragePost(requestParameters: PostCollectionResourceAbfragePostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelAbfrage> {
        const response = await this.postCollectionResourceAbfragePostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putItemResourceAbfragePut without sending the request
     */
    async putItemResourceAbfragePutRequestOpts(requestParameters: PutItemResourceAbfragePutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourceAbfragePut().'
            );
        }

        if (requestParameters['abfrageRequestBody'] == null) {
            throw new runtime.RequiredError(
                'abfrageRequestBody',
                'Required parameter "abfrageRequestBody" was null or undefined when calling putItemResourceAbfragePut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/abfrages/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: AbfrageRequestBodyToJSON(requestParameters['abfrageRequestBody']),
        };
    }

    /**
     * update-abfrage
     */
    async putItemResourceAbfragePutRaw(requestParameters: PutItemResourceAbfragePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelAbfrage>> {
        const requestOptions = await this.putItemResourceAbfragePutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelAbfrageFromJSON(jsonValue));
    }

    /**
     * update-abfrage
     */
    async putItemResourceAbfragePut(requestParameters: PutItemResourceAbfragePutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelAbfrage | null | undefined > {
        const response = await this.putItemResourceAbfragePutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
