/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CollectionModelDokument,
  CollectionModelObject,
} from '../models/index';
import {
    CollectionModelDokumentFromJSON,
    CollectionModelDokumentToJSON,
    CollectionModelObjectFromJSON,
    CollectionModelObjectToJSON,
} from '../models/index';

export interface CreatePropertyReferenceAbfragevariantebauleitplanverfahrenPatchRequest {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface CreatePropertyReferenceAbfragevariantebauleitplanverfahrenPutRequest {
    id: string;
    collectionModelObject: CollectionModelObject;
}

export interface DeletePropertyReferenceAbfragevariantebauleitplanverfahrenDeleteRequest {
    id: string;
}

export interface DeletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDeleteRequest {
    id: string;
    propertyId: string;
}

export interface FollowPropertyReferenceAbfragevariantebauleitplanverfahrenGetRequest {
    id: string;
}

export interface FollowPropertyReferenceAbfragevariantebauleitplanverfahrenGet1Request {
    id: string;
    propertyId: string;
}

/**
 * 
 */
export class AbfragevarianteBauleitplanverfahrenPropertyReferenceControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for createPropertyReferenceAbfragevariantebauleitplanverfahrenPatch without sending the request
     */
    async createPropertyReferenceAbfragevariantebauleitplanverfahrenPatchRequestOpts(requestParameters: CreatePropertyReferenceAbfragevariantebauleitplanverfahrenPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceAbfragevariantebauleitplanverfahrenPatch().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceAbfragevariantebauleitplanverfahrenPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/abfragevarianteBauleitplanverfahrens/{id}/dokumente`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        };
    }

    /**
     * patch-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async createPropertyReferenceAbfragevariantebauleitplanverfahrenPatchRaw(requestParameters: CreatePropertyReferenceAbfragevariantebauleitplanverfahrenPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelDokument>> {
        const requestOptions = await this.createPropertyReferenceAbfragevariantebauleitplanverfahrenPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelDokumentFromJSON(jsonValue));
    }

    /**
     * patch-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async createPropertyReferenceAbfragevariantebauleitplanverfahrenPatch(requestParameters: CreatePropertyReferenceAbfragevariantebauleitplanverfahrenPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelDokument | null | undefined > {
        const response = await this.createPropertyReferenceAbfragevariantebauleitplanverfahrenPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * Creates request options for createPropertyReferenceAbfragevariantebauleitplanverfahrenPut without sending the request
     */
    async createPropertyReferenceAbfragevariantebauleitplanverfahrenPutRequestOpts(requestParameters: CreatePropertyReferenceAbfragevariantebauleitplanverfahrenPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling createPropertyReferenceAbfragevariantebauleitplanverfahrenPut().'
            );
        }

        if (requestParameters['collectionModelObject'] == null) {
            throw new runtime.RequiredError(
                'collectionModelObject',
                'Required parameter "collectionModelObject" was null or undefined when calling createPropertyReferenceAbfragevariantebauleitplanverfahrenPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/abfragevarianteBauleitplanverfahrens/{id}/dokumente`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: CollectionModelObjectToJSON(requestParameters['collectionModelObject']),
        };
    }

    /**
     * update-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async createPropertyReferenceAbfragevariantebauleitplanverfahrenPutRaw(requestParameters: CreatePropertyReferenceAbfragevariantebauleitplanverfahrenPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelDokument>> {
        const requestOptions = await this.createPropertyReferenceAbfragevariantebauleitplanverfahrenPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelDokumentFromJSON(jsonValue));
    }

    /**
     * update-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async createPropertyReferenceAbfragevariantebauleitplanverfahrenPut(requestParameters: CreatePropertyReferenceAbfragevariantebauleitplanverfahrenPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelDokument | null | undefined > {
        const response = await this.createPropertyReferenceAbfragevariantebauleitplanverfahrenPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * Creates request options for deletePropertyReferenceAbfragevariantebauleitplanverfahrenDelete without sending the request
     */
    async deletePropertyReferenceAbfragevariantebauleitplanverfahrenDeleteRequestOpts(requestParameters: DeletePropertyReferenceAbfragevariantebauleitplanverfahrenDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceAbfragevariantebauleitplanverfahrenDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/abfragevarianteBauleitplanverfahrens/{id}/dokumente`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * delete-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async deletePropertyReferenceAbfragevariantebauleitplanverfahrenDeleteRaw(requestParameters: DeletePropertyReferenceAbfragevariantebauleitplanverfahrenDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deletePropertyReferenceAbfragevariantebauleitplanverfahrenDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async deletePropertyReferenceAbfragevariantebauleitplanverfahrenDelete(requestParameters: DeletePropertyReferenceAbfragevariantebauleitplanverfahrenDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceAbfragevariantebauleitplanverfahrenDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for deletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDelete without sending the request
     */
    async deletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDeleteRequestOpts(requestParameters: DeletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDelete().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling deletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/abfragevarianteBauleitplanverfahrens/{id}/dokumente/{propertyId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * delete-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async deletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDeleteRaw(requestParameters: DeletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async deletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDelete(requestParameters: DeletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePropertyReferenceIdAbfragevariantebauleitplanverfahrenDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for followPropertyReferenceAbfragevariantebauleitplanverfahrenGet without sending the request
     */
    async followPropertyReferenceAbfragevariantebauleitplanverfahrenGetRequestOpts(requestParameters: FollowPropertyReferenceAbfragevariantebauleitplanverfahrenGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceAbfragevariantebauleitplanverfahrenGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/abfragevarianteBauleitplanverfahrens/{id}/dokumente`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async followPropertyReferenceAbfragevariantebauleitplanverfahrenGetRaw(requestParameters: FollowPropertyReferenceAbfragevariantebauleitplanverfahrenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelDokument>> {
        const requestOptions = await this.followPropertyReferenceAbfragevariantebauleitplanverfahrenGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelDokumentFromJSON(jsonValue));
    }

    /**
     * get-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async followPropertyReferenceAbfragevariantebauleitplanverfahrenGet(requestParameters: FollowPropertyReferenceAbfragevariantebauleitplanverfahrenGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelDokument> {
        const response = await this.followPropertyReferenceAbfragevariantebauleitplanverfahrenGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for followPropertyReferenceAbfragevariantebauleitplanverfahrenGet1 without sending the request
     */
    async followPropertyReferenceAbfragevariantebauleitplanverfahrenGet1RequestOpts(requestParameters: FollowPropertyReferenceAbfragevariantebauleitplanverfahrenGet1Request): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling followPropertyReferenceAbfragevariantebauleitplanverfahrenGet1().'
            );
        }

        if (requestParameters['propertyId'] == null) {
            throw new runtime.RequiredError(
                'propertyId',
                'Required parameter "propertyId" was null or undefined when calling followPropertyReferenceAbfragevariantebauleitplanverfahrenGet1().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/abfragevarianteBauleitplanverfahrens/{id}/dokumente/{propertyId}`;
        urlPath = urlPath.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters['id'])));
        urlPath = urlPath.replace(`{${"propertyId"}}`, encodeURIComponent(String(requestParameters['propertyId'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async followPropertyReferenceAbfragevariantebauleitplanverfahrenGet1Raw(requestParameters: FollowPropertyReferenceAbfragevariantebauleitplanverfahrenGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CollectionModelDokument>> {
        const requestOptions = await this.followPropertyReferenceAbfragevariantebauleitplanverfahrenGet1RequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CollectionModelDokumentFromJSON(jsonValue));
    }

    /**
     * get-dokument-by-abfragevariantebauleitplanverfahren-Id
     */
    async followPropertyReferenceAbfragevariantebauleitplanverfahrenGet1(requestParameters: FollowPropertyReferenceAbfragevariantebauleitplanverfahrenGet1Request, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CollectionModelDokument> {
        const response = await this.followPropertyReferenceAbfragevariantebauleitplanverfahrenGet1Raw(requestParameters, initOverrides);
        return await response.value();
    }

}
