/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type AbfrageSearchResultDto,
    AbfrageSearchResultDtoFromJSON,
    AbfrageSearchResultDtoToJSON,
} from '../models/AbfrageSearchResultDto';
import {
    type BauvorhabenDto,
    BauvorhabenDtoFromJSON,
    BauvorhabenDtoToJSON,
} from '../models/BauvorhabenDto';
import {
    type InformationResponseDto,
    InformationResponseDtoFromJSON,
    InformationResponseDtoToJSON,
} from '../models/InformationResponseDto';
import {
    type InfrastruktureinrichtungSearchResultDto,
    InfrastruktureinrichtungSearchResultDtoFromJSON,
    InfrastruktureinrichtungSearchResultDtoToJSON,
} from '../models/InfrastruktureinrichtungSearchResultDto';

export interface CreateBauvorhabenRequest {
    /**
     * 
     */
    bauvorhabenDto: BauvorhabenDto;
    /**
     * 
     */
    abfrageId?: string;
}

export interface DeleteBauvorhabenRequest {
    /**
     * 
     */
    id: string;
}

export interface GetBauvorhabenByIdRequest {
    /**
     * 
     */
    id: string;
}

export interface GetReferencedAbfrageRequest {
    /**
     * 
     */
    id: string;
}

export interface GetReferencedInfrastruktureinrichtungRequest {
    /**
     * 
     */
    id: string;
}

export interface PutChangeRelevanteAbfragevarianteRequest {
    /**
     * 
     */
    abfragevarianteId: string;
}

export interface UpdateBauvorhabenRequest {
    /**
     * 
     */
    bauvorhabenDto: BauvorhabenDto;
}

/**
 * 
 */
export class BauvorhabenApi extends runtime.BaseAPI {

    /**
     * Creates request options for createBauvorhaben without sending the request
     */
    async createBauvorhabenRequestOpts(requestParameters: CreateBauvorhabenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bauvorhabenDto'] == null) {
            throw new runtime.RequiredError(
                'bauvorhabenDto',
                'Required parameter "bauvorhabenDto" was null or undefined when calling createBauvorhaben().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['abfrageId'] != null) {
            queryParameters['abfrageId'] = requestParameters['abfrageId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/bauvorhaben`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: BauvorhabenDtoToJSON(requestParameters['bauvorhabenDto']),
        };
    }

    /**
     * Anlegen eines neuen Bauvorhabens
     */
    async createBauvorhabenRaw(requestParameters: CreateBauvorhabenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BauvorhabenDto>> {
        const requestOptions = await this.createBauvorhabenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BauvorhabenDtoFromJSON(jsonValue));
    }

    /**
     * Anlegen eines neuen Bauvorhabens
     */
    async createBauvorhaben(requestParameters: CreateBauvorhabenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BauvorhabenDto> {
        const response = await this.createBauvorhabenRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for deleteBauvorhaben without sending the request
     */
    async deleteBauvorhabenRequestOpts(requestParameters: DeleteBauvorhabenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteBauvorhaben().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bauvorhaben/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Löschen eines Bauvorhabens
     */
    async deleteBauvorhabenRaw(requestParameters: DeleteBauvorhabenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteBauvorhabenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Löschen eines Bauvorhabens
     */
    async deleteBauvorhaben(requestParameters: DeleteBauvorhabenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteBauvorhabenRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getBauvorhabenById without sending the request
     */
    async getBauvorhabenByIdRequestOpts(requestParameters: GetBauvorhabenByIdRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getBauvorhabenById().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bauvorhaben/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Lesen eines Bauvorhabens
     */
    async getBauvorhabenByIdRaw(requestParameters: GetBauvorhabenByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BauvorhabenDto>> {
        const requestOptions = await this.getBauvorhabenByIdRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BauvorhabenDtoFromJSON(jsonValue));
    }

    /**
     * Lesen eines Bauvorhabens
     */
    async getBauvorhabenById(requestParameters: GetBauvorhabenByIdRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BauvorhabenDto> {
        const response = await this.getBauvorhabenByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getReferencedAbfrage without sending the request
     */
    async getReferencedAbfrageRequestOpts(requestParameters: GetReferencedAbfrageRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getReferencedAbfrage().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bauvorhaben/referenced/abfragen/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Das Ergebnis wird anhand des Erstellungsdatums aufsteigend sortiert.
     * Lade alle Abfragen die einem Bauvorhaben angehören
     */
    async getReferencedAbfrageRaw(requestParameters: GetReferencedAbfrageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AbfrageSearchResultDto>>> {
        const requestOptions = await this.getReferencedAbfrageRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AbfrageSearchResultDtoFromJSON));
    }

    /**
     * Das Ergebnis wird anhand des Erstellungsdatums aufsteigend sortiert.
     * Lade alle Abfragen die einem Bauvorhaben angehören
     */
    async getReferencedAbfrage(requestParameters: GetReferencedAbfrageRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AbfrageSearchResultDto>> {
        const response = await this.getReferencedAbfrageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getReferencedInfrastruktureinrichtung without sending the request
     */
    async getReferencedInfrastruktureinrichtungRequestOpts(requestParameters: GetReferencedInfrastruktureinrichtungRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getReferencedInfrastruktureinrichtung().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bauvorhaben/referenced/infrastruktureinrichtung/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Das Ergebnis wird anhand des InfrastruktureinrichtungTyps und innerhalb des Types alphabetisch sortiert
     * Lade alle Infrastruktureinrichtungen die einem Bauvorhaben angehören
     */
    async getReferencedInfrastruktureinrichtungRaw(requestParameters: GetReferencedInfrastruktureinrichtungRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<InfrastruktureinrichtungSearchResultDto>>> {
        const requestOptions = await this.getReferencedInfrastruktureinrichtungRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InfrastruktureinrichtungSearchResultDtoFromJSON));
    }

    /**
     * Das Ergebnis wird anhand des InfrastruktureinrichtungTyps und innerhalb des Types alphabetisch sortiert
     * Lade alle Infrastruktureinrichtungen die einem Bauvorhaben angehören
     */
    async getReferencedInfrastruktureinrichtung(requestParameters: GetReferencedInfrastruktureinrichtungRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<InfrastruktureinrichtungSearchResultDto>> {
        const response = await this.getReferencedInfrastruktureinrichtungRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putChangeRelevanteAbfragevariante without sending the request
     */
    async putChangeRelevanteAbfragevarianteRequestOpts(requestParameters: PutChangeRelevanteAbfragevarianteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['abfragevarianteId'] == null) {
            throw new runtime.RequiredError(
                'abfragevarianteId',
                'Required parameter "abfragevarianteId" was null or undefined when calling putChangeRelevanteAbfragevariante().'
            );
        }

        const queryParameters: any = {};

        if (requestParameters['abfragevarianteId'] != null) {
            queryParameters['abfragevariante-id'] = requestParameters['abfragevarianteId'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/bauvorhaben/change-relevante-abfragevariante`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * Setzt die übergebene Abfragevariante als relevante Abfrage beim Bauvorhaben, welches mit der Abfrage der Abfragevariante verknüpft ist.Ist die Abfragevariante bereits als relevant markiert, wird die relevante Abfragevariante des Bauvorhabens entfernt.Eine Relevantsetzung kann nur vorgenommen werden, wenn die Abfrage ein Bauvorhaben referenziert,die Abfrage im Status {@link StatusAbfrage#START_BEARBEITUNG} istund noch keine andere Abfrage als relevant markiert wurde.
     */
    async putChangeRelevanteAbfragevarianteRaw(requestParameters: PutChangeRelevanteAbfragevarianteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BauvorhabenDto>> {
        const requestOptions = await this.putChangeRelevanteAbfragevarianteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BauvorhabenDtoFromJSON(jsonValue));
    }

    /**
     * Setzt die übergebene Abfragevariante als relevante Abfrage beim Bauvorhaben, welches mit der Abfrage der Abfragevariante verknüpft ist.Ist die Abfragevariante bereits als relevant markiert, wird die relevante Abfragevariante des Bauvorhabens entfernt.Eine Relevantsetzung kann nur vorgenommen werden, wenn die Abfrage ein Bauvorhaben referenziert,die Abfrage im Status {@link StatusAbfrage#START_BEARBEITUNG} istund noch keine andere Abfrage als relevant markiert wurde.
     */
    async putChangeRelevanteAbfragevariante(requestParameters: PutChangeRelevanteAbfragevarianteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BauvorhabenDto> {
        const response = await this.putChangeRelevanteAbfragevarianteRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for updateBauvorhaben without sending the request
     */
    async updateBauvorhabenRequestOpts(requestParameters: UpdateBauvorhabenRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['bauvorhabenDto'] == null) {
            throw new runtime.RequiredError(
                'bauvorhabenDto',
                'Required parameter "bauvorhabenDto" was null or undefined when calling updateBauvorhaben().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/bauvorhaben`;

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: BauvorhabenDtoToJSON(requestParameters['bauvorhabenDto']),
        };
    }

    /**
     * Aktualisierung eines Bauvorhabens
     */
    async updateBauvorhabenRaw(requestParameters: UpdateBauvorhabenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<BauvorhabenDto>> {
        const requestOptions = await this.updateBauvorhabenRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => BauvorhabenDtoFromJSON(jsonValue));
    }

    /**
     * Aktualisierung eines Bauvorhabens
     */
    async updateBauvorhaben(requestParameters: UpdateBauvorhabenRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<BauvorhabenDto> {
        const response = await this.updateBauvorhabenRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
