/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  EntityModelGlobalCounter,
} from '../models/index';
import {
    EntityModelGlobalCounterFromJSON,
    EntityModelGlobalCounterToJSON,
} from '../models/index';

export interface ExecuteSearchGlobalcounterGetRequest {
    counterType?: ExecuteSearchGlobalcounterGetCounterTypeEnum;
}

/**
 * 
 */
export class GlobalCounterSearchControllerApi extends runtime.BaseAPI {

    /**
     */
    async executeSearchGlobalcounterGetRaw(requestParameters: ExecuteSearchGlobalcounterGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelGlobalCounter>> {
        const queryParameters: any = {};

        if (requestParameters['counterType'] != null) {
            queryParameters['counterType'] = requestParameters['counterType'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/globalCounters/search/findByCounterType`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelGlobalCounterFromJSON(jsonValue));
    }

    /**
     */
    async executeSearchGlobalcounterGet(requestParameters: ExecuteSearchGlobalcounterGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelGlobalCounter> {
        const response = await this.executeSearchGlobalcounterGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}

/**
 * @export
 */
export const ExecuteSearchGlobalcounterGetCounterTypeEnum = {
    NummerBauvorhaben: 'NUMMER_BAUVORHABEN'
} as const;
export type ExecuteSearchGlobalcounterGetCounterTypeEnum = typeof ExecuteSearchGlobalcounterGetCounterTypeEnum[keyof typeof ExecuteSearchGlobalcounterGetCounterTypeEnum];
