/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime';
import {
    type EntityModelPersonalFilter,
    EntityModelPersonalFilterFromJSON,
    EntityModelPersonalFilterToJSON,
} from '../models/EntityModelPersonalFilter';
import {
    type PagedModelEntityModelPersonalFilter,
    PagedModelEntityModelPersonalFilterFromJSON,
    PagedModelEntityModelPersonalFilterToJSON,
} from '../models/PagedModelEntityModelPersonalFilter';
import {
    type PersonalFilterRequestBody,
    PersonalFilterRequestBodyFromJSON,
    PersonalFilterRequestBodyToJSON,
} from '../models/PersonalFilterRequestBody';

export interface DeleteItemResourcePersonalfilterDeleteRequest {
    id: string;
}

export interface GetCollectionResourcePersonalfilterGetRequest {
    page?: number;
    size?: number;
    sort?: Array<string>;
}

export interface GetItemResourcePersonalfilterGetRequest {
    id: string;
}

export interface PatchItemResourcePersonalfilterPatchRequest {
    id: string;
    personalFilterRequestBody: PersonalFilterRequestBody;
}

export interface PostCollectionResourcePersonalfilterPostRequest {
    personalFilterRequestBody: PersonalFilterRequestBody;
}

export interface PutItemResourcePersonalfilterPutRequest {
    id: string;
    personalFilterRequestBody: PersonalFilterRequestBody;
}

/**
 * 
 */
export class PersonalFilterEntityControllerApi extends runtime.BaseAPI {

    /**
     * Creates request options for deleteItemResourcePersonalfilterDelete without sending the request
     */
    async deleteItemResourcePersonalfilterDeleteRequestOpts(requestParameters: DeleteItemResourcePersonalfilterDeleteRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling deleteItemResourcePersonalfilterDelete().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/personalFilters/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * delete-personalfilter
     */
    async deleteItemResourcePersonalfilterDeleteRaw(requestParameters: DeleteItemResourcePersonalfilterDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const requestOptions = await this.deleteItemResourcePersonalfilterDeleteRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * delete-personalfilter
     */
    async deleteItemResourcePersonalfilterDelete(requestParameters: DeleteItemResourcePersonalfilterDeleteRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deleteItemResourcePersonalfilterDeleteRaw(requestParameters, initOverrides);
    }

    /**
     * Creates request options for getCollectionResourcePersonalfilterGet without sending the request
     */
    async getCollectionResourcePersonalfilterGetRequestOpts(requestParameters: GetCollectionResourcePersonalfilterGetRequest): Promise<runtime.RequestOpts> {
        const queryParameters: any = {};

        if (requestParameters['page'] != null) {
            queryParameters['page'] = requestParameters['page'];
        }

        if (requestParameters['size'] != null) {
            queryParameters['size'] = requestParameters['size'];
        }

        if (requestParameters['sort'] != null) {
            queryParameters['sort'] = requestParameters['sort'];
        }

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/personalFilters`;

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get-personalfilter
     */
    async getCollectionResourcePersonalfilterGetRaw(requestParameters: GetCollectionResourcePersonalfilterGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<PagedModelEntityModelPersonalFilter>> {
        const requestOptions = await this.getCollectionResourcePersonalfilterGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PagedModelEntityModelPersonalFilterFromJSON(jsonValue));
    }

    /**
     * get-personalfilter
     */
    async getCollectionResourcePersonalfilterGet(requestParameters: GetCollectionResourcePersonalfilterGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<PagedModelEntityModelPersonalFilter> {
        const response = await this.getCollectionResourcePersonalfilterGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for getItemResourcePersonalfilterGet without sending the request
     */
    async getItemResourcePersonalfilterGetRequestOpts(requestParameters: GetItemResourcePersonalfilterGetRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling getItemResourcePersonalfilterGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/personalFilters/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        };
    }

    /**
     * get-personalfilter
     */
    async getItemResourcePersonalfilterGetRaw(requestParameters: GetItemResourcePersonalfilterGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelPersonalFilter>> {
        const requestOptions = await this.getItemResourcePersonalfilterGetRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelPersonalFilterFromJSON(jsonValue));
    }

    /**
     * get-personalfilter
     */
    async getItemResourcePersonalfilterGet(requestParameters: GetItemResourcePersonalfilterGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelPersonalFilter> {
        const response = await this.getItemResourcePersonalfilterGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for patchItemResourcePersonalfilterPatch without sending the request
     */
    async patchItemResourcePersonalfilterPatchRequestOpts(requestParameters: PatchItemResourcePersonalfilterPatchRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling patchItemResourcePersonalfilterPatch().'
            );
        }

        if (requestParameters['personalFilterRequestBody'] == null) {
            throw new runtime.RequiredError(
                'personalFilterRequestBody',
                'Required parameter "personalFilterRequestBody" was null or undefined when calling patchItemResourcePersonalfilterPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/personalFilters/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: PersonalFilterRequestBodyToJSON(requestParameters['personalFilterRequestBody']),
        };
    }

    /**
     * patch-personalfilter
     */
    async patchItemResourcePersonalfilterPatchRaw(requestParameters: PatchItemResourcePersonalfilterPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelPersonalFilter>> {
        const requestOptions = await this.patchItemResourcePersonalfilterPatchRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelPersonalFilterFromJSON(jsonValue));
    }

    /**
     * patch-personalfilter
     */
    async patchItemResourcePersonalfilterPatch(requestParameters: PatchItemResourcePersonalfilterPatchRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelPersonalFilter | null | undefined > {
        const response = await this.patchItemResourcePersonalfilterPatchRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

    /**
     * Creates request options for postCollectionResourcePersonalfilterPost without sending the request
     */
    async postCollectionResourcePersonalfilterPostRequestOpts(requestParameters: PostCollectionResourcePersonalfilterPostRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['personalFilterRequestBody'] == null) {
            throw new runtime.RequiredError(
                'personalFilterRequestBody',
                'Required parameter "personalFilterRequestBody" was null or undefined when calling postCollectionResourcePersonalfilterPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/personalFilters`;

        return {
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PersonalFilterRequestBodyToJSON(requestParameters['personalFilterRequestBody']),
        };
    }

    /**
     * create-personalfilter
     */
    async postCollectionResourcePersonalfilterPostRaw(requestParameters: PostCollectionResourcePersonalfilterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelPersonalFilter>> {
        const requestOptions = await this.postCollectionResourcePersonalfilterPostRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelPersonalFilterFromJSON(jsonValue));
    }

    /**
     * create-personalfilter
     */
    async postCollectionResourcePersonalfilterPost(requestParameters: PostCollectionResourcePersonalfilterPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelPersonalFilter> {
        const response = await this.postCollectionResourcePersonalfilterPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Creates request options for putItemResourcePersonalfilterPut without sending the request
     */
    async putItemResourcePersonalfilterPutRequestOpts(requestParameters: PutItemResourcePersonalfilterPutRequest): Promise<runtime.RequestOpts> {
        if (requestParameters['id'] == null) {
            throw new runtime.RequiredError(
                'id',
                'Required parameter "id" was null or undefined when calling putItemResourcePersonalfilterPut().'
            );
        }

        if (requestParameters['personalFilterRequestBody'] == null) {
            throw new runtime.RequiredError(
                'personalFilterRequestBody',
                'Required parameter "personalFilterRequestBody" was null or undefined when calling putItemResourcePersonalfilterPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/personalFilters/{id}`;
        urlPath = urlPath.replace('{id}', encodeURIComponent(String(requestParameters['id'])));

        return {
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PersonalFilterRequestBodyToJSON(requestParameters['personalFilterRequestBody']),
        };
    }

    /**
     * update-personalfilter
     */
    async putItemResourcePersonalfilterPutRaw(requestParameters: PutItemResourcePersonalfilterPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<EntityModelPersonalFilter>> {
        const requestOptions = await this.putItemResourcePersonalfilterPutRequestOpts(requestParameters);
        const response = await this.request(requestOptions, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => EntityModelPersonalFilterFromJSON(jsonValue));
    }

    /**
     * update-personalfilter
     */
    async putItemResourcePersonalfilterPut(requestParameters: PutItemResourcePersonalfilterPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<EntityModelPersonalFilter | null | undefined > {
        const response = await this.putItemResourcePersonalfilterPutRaw(requestParameters, initOverrides);
        switch (response.raw.status) {
            case 200:
                return await response.value();
            case 201:
                return await response.value();
            case 204:
                return null;
            default:
                return await response.value();
        }
    }

}
