/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { BauratendateiInputDto } from './BauratendateiInputDto';
import {
    BauratendateiInputDtoFromJSON,
    BauratendateiInputDtoFromJSONTyped,
    BauratendateiInputDtoToJSON,
    BauratendateiInputDtoToJSONTyped,
} from './BauratendateiInputDto';
import type { DokumentDto } from './DokumentDto';
import {
    DokumentDtoFromJSON,
    DokumentDtoFromJSONTyped,
    DokumentDtoToJSON,
    DokumentDtoToJSONTyped,
} from './DokumentDto';

/**
 * 
 * @export
 * @interface AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDto
 */
export interface AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDto {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    version?: number;
    /**
     * 
     */
    artAbfragevariante?: AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoArtAbfragevarianteEnum;
    /**
     * 
     */
    sobonOrientierungswertJahrPlanungsursaechlich: AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoSobonOrientierungswertJahrPlanungsursaechlichEnum;
    /**
     * 
     */
    stammdatenGueltigAb: Date;
    /**
     * 
     */
    anmerkung?: string;
    /**
     * 
     */
    hasBauratendateiInput?: boolean;
    /**
     * 
     */
    anmerkungBauratendateiInput?: string;
    /**
     * 
     */
    bauratendateiInputBasis?: BauratendateiInputDto;
    /**
     * 
     */
    bauratendateiInput?: Array<BauratendateiInputDto>;
    /**
     * 
     */
    dokumente?: Array<DokumentDto>;
}


/**
 * @export
 */
export const AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoArtAbfragevarianteEnum = {
    Unspecified: 'UNSPECIFIED',
    Bauleitplanverfahren: 'BAULEITPLANVERFAHREN',
    Baugenehmigungsverfahren: 'BAUGENEHMIGUNGSVERFAHREN',
    WeiteresVerfahren: 'WEITERES_VERFAHREN',
} as const;
export type AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoArtAbfragevarianteEnum = typeof AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoArtAbfragevarianteEnum[keyof typeof AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoArtAbfragevarianteEnum];

/**
 * @export
 */
export const AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoSobonOrientierungswertJahrPlanungsursaechlichEnum = {
    Unspecified: 'UNSPECIFIED',
    Jahr2014: 'JAHR_2014',
    Jahr2017: 'JAHR_2017',
    Jahr2022: 'JAHR_2022',
    Jahr2024: 'JAHR_2024',
    Jahr202434: 'JAHR_2024_34',
    Standortabfrage: 'STANDORTABFRAGE',
} as const;
export type AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoSobonOrientierungswertJahrPlanungsursaechlichEnum = typeof AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoSobonOrientierungswertJahrPlanungsursaechlichEnum[keyof typeof AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoSobonOrientierungswertJahrPlanungsursaechlichEnum];


/**
 * Check if a given object implements the AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDto interface.
 */
export function instanceOfAbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDto(value: object): value is AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDto {
    if (!('sobonOrientierungswertJahrPlanungsursaechlich' in value) || value['sobonOrientierungswertJahrPlanungsursaechlich'] === undefined) return false;
    if (!('stammdatenGueltigAb' in value) || value['stammdatenGueltigAb'] === undefined) return false;
    return true;
}

export function AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoFromJSON(json: any): AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDto {
    return AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoFromJSONTyped(json, false);
}

export function AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'version': json['version'] == null ? undefined : json['version'],
        'artAbfragevariante': json['artAbfragevariante'] == null ? undefined : json['artAbfragevariante'],
        'sobonOrientierungswertJahrPlanungsursaechlich': json['sobonOrientierungswertJahrPlanungsursaechlich'],
        'stammdatenGueltigAb': (json['stammdatenGueltigAb'] == null ? json['stammdatenGueltigAb'] : parseDate(json['stammdatenGueltigAb'])),
        'anmerkung': json['anmerkung'] == null ? undefined : json['anmerkung'],
        'hasBauratendateiInput': json['hasBauratendateiInput'] == null ? undefined : json['hasBauratendateiInput'],
        'anmerkungBauratendateiInput': json['anmerkungBauratendateiInput'] == null ? undefined : json['anmerkungBauratendateiInput'],
        'bauratendateiInputBasis': json['bauratendateiInputBasis'] == null ? undefined : BauratendateiInputDtoFromJSON(json['bauratendateiInputBasis']),
        'bauratendateiInput': json['bauratendateiInput'] == null ? undefined : ((json['bauratendateiInput'] as Array<any>).map(BauratendateiInputDtoFromJSON)),
        'dokumente': json['dokumente'] == null ? undefined : ((json['dokumente'] as Array<any>).map(DokumentDtoFromJSON)),
    };
}

export function AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoToJSON(json: any): AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDto {
    return AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoToJSONTyped(json, false);
}

export function AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDtoToJSONTyped(value?: AbfragevarianteBaugenehmigungsverfahrenSachbearbeitungStartBearbeitungDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'version': value['version'],
        'artAbfragevariante': value['artAbfragevariante'],
        'sobonOrientierungswertJahrPlanungsursaechlich': value['sobonOrientierungswertJahrPlanungsursaechlich'],
        'stammdatenGueltigAb': value['stammdatenGueltigAb'] == null ? value['stammdatenGueltigAb'] : serializeDate(value['stammdatenGueltigAb']),
        'anmerkung': value['anmerkung'],
        'hasBauratendateiInput': value['hasBauratendateiInput'],
        'anmerkungBauratendateiInput': value['anmerkungBauratendateiInput'],
        'bauratendateiInputBasis': BauratendateiInputDtoToJSON(value['bauratendateiInputBasis']),
        'bauratendateiInput': value['bauratendateiInput'] == null ? undefined : ((value['bauratendateiInput'] as Array<any>).map(BauratendateiInputDtoToJSON)),
        'dokumente': value['dokumente'] == null ? undefined : ((value['dokumente'] as Array<any>).map(DokumentDtoToJSON)),
    };
}

