/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues, parseDate, parseDateTime, serializeDate, serializeDateTime } from '../runtime';
import type { SobonBerechnungDto } from './SobonBerechnungDto';
import {
    SobonBerechnungDtoFromJSON,
    SobonBerechnungDtoFromJSONTyped,
    SobonBerechnungDtoToJSON,
    SobonBerechnungDtoToJSONTyped,
} from './SobonBerechnungDto';
import type { BauratendateiInputDto } from './BauratendateiInputDto';
import {
    BauratendateiInputDtoFromJSON,
    BauratendateiInputDtoFromJSONTyped,
    BauratendateiInputDtoToJSON,
    BauratendateiInputDtoToJSONTyped,
} from './BauratendateiInputDto';
import type { BauabschnittDto } from './BauabschnittDto';
import {
    BauabschnittDtoFromJSON,
    BauabschnittDtoFromJSONTyped,
    BauabschnittDtoToJSON,
    BauabschnittDtoToJSONTyped,
} from './BauabschnittDto';
import type { DokumentDto } from './DokumentDto';
import {
    DokumentDtoFromJSON,
    DokumentDtoFromJSONTyped,
    DokumentDtoToJSON,
    DokumentDtoToJSONTyped,
} from './DokumentDto';

/**
 * 
 * @export
 * @interface AbfragevarianteWeiteresVerfahrenStartBearbeitungDto
 */
export interface AbfragevarianteWeiteresVerfahrenStartBearbeitungDto {
    /**
     * 
     */
    id?: string;
    /**
     * 
     */
    version?: number;
    /**
     * 
     */
    artAbfragevariante?: AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoArtAbfragevarianteEnum;
    /**
     * 
     */
    abfragevariantenNr: number;
    /**
     * 
     */
    name: string;
    /**
     * 
     */
    satzungsbeschluss?: Date;
    /**
     * 
     */
    wesentlicheRechtsgrundlage: Array<AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoWesentlicheRechtsgrundlageEnum>;
    /**
     * 
     */
    wesentlicheRechtsgrundlageFreieEingabe?: string;
    /**
     * 
     */
    wesentlicheRechtsgrundlageAngabenZurBefreiung?: string;
    /**
     * 
     */
    realisierungVon: number;
    /**
     * 
     */
    gfWohnenGesamt?: number;
    /**
     * 
     */
    gfWohnenBaurechtlichGenehmigt?: number;
    /**
     * 
     */
    gfWohnenBaurechtlichFestgesetzt?: number;
    /**
     * 
     */
    gfWohnenSobonUrsaechlich?: number;
    /**
     * 
     */
    gfWohnenBestandswohnbaurecht?: number;
    /**
     * 
     */
    gfWohnenSonderwohnformen: boolean;
    /**
     * 
     */
    gfWohnenStudentischesWohnen?: number;
    /**
     * 
     */
    gfWohnenSeniorinnenWohnen?: number;
    /**
     * 
     */
    gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen?: number;
    /**
     * 
     */
    gfAnmerkung?: string;
    /**
     * 
     */
    weGesamt?: number;
    /**
     * 
     */
    weBaurechtlichGenehmigt?: number;
    /**
     * 
     */
    weBaurechtlichFestgesetzt?: number;
    /**
     * 
     */
    weSonderwohnformen: boolean;
    /**
     * 
     */
    weStudentischesWohnen?: number;
    /**
     * 
     */
    weSeniorinnenWohnen?: number;
    /**
     * 
     */
    weWeiteresNichtInfrastrukturrelevantesWohnen?: number;
    /**
     * 
     */
    weAnmerkung?: string;
    /**
     * 
     */
    bauabschnitte?: Array<BauabschnittDto>;
    /**
     * 
     */
    sobonOrientierungswertJahrPlanungsursaechlich: AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoSobonOrientierungswertJahrPlanungsursaechlichEnum;
    /**
     * 
     */
    sobonBerechnung?: SobonBerechnungDto;
    /**
     * 
     */
    stammdatenGueltigAb: Date;
    /**
     * 
     */
    anmerkung?: string;
    /**
     * 
     */
    hasBauratendateiInput?: boolean;
    /**
     * 
     */
    anmerkungBauratendateiInput?: string;
    /**
     * 
     */
    bauratendateiInputBasis?: BauratendateiInputDto;
    /**
     * 
     */
    bauratendateiInput?: Array<BauratendateiInputDto>;
    /**
     * 
     */
    dokumente?: Array<DokumentDto>;
}


/**
 * @export
 */
export const AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoArtAbfragevarianteEnum = {
    Unspecified: 'UNSPECIFIED',
    Bauleitplanverfahren: 'BAULEITPLANVERFAHREN',
    Baugenehmigungsverfahren: 'BAUGENEHMIGUNGSVERFAHREN',
    WeiteresVerfahren: 'WEITERES_VERFAHREN',
} as const;
export type AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoArtAbfragevarianteEnum = typeof AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoArtAbfragevarianteEnum[keyof typeof AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoArtAbfragevarianteEnum];

/**
 * @export
 */
export const AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoWesentlicheRechtsgrundlageEnum = {
    BeplanterBereichParagraph30: 'BEPLANTER_BEREICH_PARAGRAPH_30',
    Innenbereich: 'INNENBEREICH',
    Aussenbereich: 'AUSSENBEREICH',
    BebauungsplanZurWohnraumversorgungParagraph9Ivm34: 'BEBAUUNGSPLAN_ZUR_WOHNRAUMVERSORGUNG_PARAGRAPH_9_IVM_34',
    BeplanterBereichParagraph30MitBefreiungParagraph31: 'BEPLANTER_BEREICH_PARAGRAPH_30_MIT_BEFREIUNG_PARAGRAPH_31',
    FreieEingabe: 'FREIE_EINGABE',
    EinfacherBebauungsplan: 'EINFACHER_BEBAUUNGSPLAN',
    QualifizierterBebauungsplan: 'QUALIFIZIERTER_BEBAUUNGSPLAN',
    VorhabensbezogenerBebauungsplan: 'VORHABENSBEZOGENER_BEBAUUNGSPLAN',
    BebauungsplanZurWohnraumversorgung: 'BEBAUUNGSPLAN_ZUR_WOHNRAUMVERSORGUNG',
    Befreiung: 'BEFREIUNG',
} as const;
export type AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoWesentlicheRechtsgrundlageEnum = typeof AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoWesentlicheRechtsgrundlageEnum[keyof typeof AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoWesentlicheRechtsgrundlageEnum];

/**
 * @export
 */
export const AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoSobonOrientierungswertJahrPlanungsursaechlichEnum = {
    Unspecified: 'UNSPECIFIED',
    Jahr2014: 'JAHR_2014',
    Jahr2017: 'JAHR_2017',
    Jahr2022: 'JAHR_2022',
    Jahr2024: 'JAHR_2024',
    Jahr202434: 'JAHR_2024_34',
    Standortabfrage: 'STANDORTABFRAGE',
} as const;
export type AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoSobonOrientierungswertJahrPlanungsursaechlichEnum = typeof AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoSobonOrientierungswertJahrPlanungsursaechlichEnum[keyof typeof AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoSobonOrientierungswertJahrPlanungsursaechlichEnum];


/**
 * Check if a given object implements the AbfragevarianteWeiteresVerfahrenStartBearbeitungDto interface.
 */
export function instanceOfAbfragevarianteWeiteresVerfahrenStartBearbeitungDto(value: object): value is AbfragevarianteWeiteresVerfahrenStartBearbeitungDto {
    if (!('abfragevariantenNr' in value) || value['abfragevariantenNr'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('wesentlicheRechtsgrundlage' in value) || value['wesentlicheRechtsgrundlage'] === undefined) return false;
    if (!('realisierungVon' in value) || value['realisierungVon'] === undefined) return false;
    if (!('gfWohnenSonderwohnformen' in value) || value['gfWohnenSonderwohnformen'] === undefined) return false;
    if (!('weSonderwohnformen' in value) || value['weSonderwohnformen'] === undefined) return false;
    if (!('sobonOrientierungswertJahrPlanungsursaechlich' in value) || value['sobonOrientierungswertJahrPlanungsursaechlich'] === undefined) return false;
    if (!('stammdatenGueltigAb' in value) || value['stammdatenGueltigAb'] === undefined) return false;
    return true;
}

export function AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoFromJSON(json: any): AbfragevarianteWeiteresVerfahrenStartBearbeitungDto {
    return AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoFromJSONTyped(json, false);
}

export function AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): AbfragevarianteWeiteresVerfahrenStartBearbeitungDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'version': json['version'] == null ? undefined : json['version'],
        'artAbfragevariante': json['artAbfragevariante'] == null ? undefined : json['artAbfragevariante'],
        'abfragevariantenNr': json['abfragevariantenNr'],
        'name': json['name'],
        'satzungsbeschluss': json['satzungsbeschluss'] == null ? undefined : (parseDate(json['satzungsbeschluss'])),
        'wesentlicheRechtsgrundlage': json['wesentlicheRechtsgrundlage'],
        'wesentlicheRechtsgrundlageFreieEingabe': json['wesentlicheRechtsgrundlageFreieEingabe'] == null ? undefined : json['wesentlicheRechtsgrundlageFreieEingabe'],
        'wesentlicheRechtsgrundlageAngabenZurBefreiung': json['wesentlicheRechtsgrundlageAngabenZurBefreiung'] == null ? undefined : json['wesentlicheRechtsgrundlageAngabenZurBefreiung'],
        'realisierungVon': json['realisierungVon'],
        'gfWohnenGesamt': json['gfWohnenGesamt'] == null ? undefined : json['gfWohnenGesamt'],
        'gfWohnenBaurechtlichGenehmigt': json['gfWohnenBaurechtlichGenehmigt'] == null ? undefined : json['gfWohnenBaurechtlichGenehmigt'],
        'gfWohnenBaurechtlichFestgesetzt': json['gfWohnenBaurechtlichFestgesetzt'] == null ? undefined : json['gfWohnenBaurechtlichFestgesetzt'],
        'gfWohnenSobonUrsaechlich': json['gfWohnenSobonUrsaechlich'] == null ? undefined : json['gfWohnenSobonUrsaechlich'],
        'gfWohnenBestandswohnbaurecht': json['gfWohnenBestandswohnbaurecht'] == null ? undefined : json['gfWohnenBestandswohnbaurecht'],
        'gfWohnenSonderwohnformen': json['gfWohnenSonderwohnformen'],
        'gfWohnenStudentischesWohnen': json['gfWohnenStudentischesWohnen'] == null ? undefined : json['gfWohnenStudentischesWohnen'],
        'gfWohnenSeniorinnenWohnen': json['gfWohnenSeniorinnenWohnen'] == null ? undefined : json['gfWohnenSeniorinnenWohnen'],
        'gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen': json['gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen'] == null ? undefined : json['gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen'],
        'gfAnmerkung': json['gfAnmerkung'] == null ? undefined : json['gfAnmerkung'],
        'weGesamt': json['weGesamt'] == null ? undefined : json['weGesamt'],
        'weBaurechtlichGenehmigt': json['weBaurechtlichGenehmigt'] == null ? undefined : json['weBaurechtlichGenehmigt'],
        'weBaurechtlichFestgesetzt': json['weBaurechtlichFestgesetzt'] == null ? undefined : json['weBaurechtlichFestgesetzt'],
        'weSonderwohnformen': json['weSonderwohnformen'],
        'weStudentischesWohnen': json['weStudentischesWohnen'] == null ? undefined : json['weStudentischesWohnen'],
        'weSeniorinnenWohnen': json['weSeniorinnenWohnen'] == null ? undefined : json['weSeniorinnenWohnen'],
        'weWeiteresNichtInfrastrukturrelevantesWohnen': json['weWeiteresNichtInfrastrukturrelevantesWohnen'] == null ? undefined : json['weWeiteresNichtInfrastrukturrelevantesWohnen'],
        'weAnmerkung': json['weAnmerkung'] == null ? undefined : json['weAnmerkung'],
        'bauabschnitte': json['bauabschnitte'] == null ? undefined : ((json['bauabschnitte'] as Array<any>).map(BauabschnittDtoFromJSON)),
        'sobonOrientierungswertJahrPlanungsursaechlich': json['sobonOrientierungswertJahrPlanungsursaechlich'],
        'sobonBerechnung': json['sobonBerechnung'] == null ? undefined : SobonBerechnungDtoFromJSON(json['sobonBerechnung']),
        'stammdatenGueltigAb': (json['stammdatenGueltigAb'] == null ? json['stammdatenGueltigAb'] : parseDate(json['stammdatenGueltigAb'])),
        'anmerkung': json['anmerkung'] == null ? undefined : json['anmerkung'],
        'hasBauratendateiInput': json['hasBauratendateiInput'] == null ? undefined : json['hasBauratendateiInput'],
        'anmerkungBauratendateiInput': json['anmerkungBauratendateiInput'] == null ? undefined : json['anmerkungBauratendateiInput'],
        'bauratendateiInputBasis': json['bauratendateiInputBasis'] == null ? undefined : BauratendateiInputDtoFromJSON(json['bauratendateiInputBasis']),
        'bauratendateiInput': json['bauratendateiInput'] == null ? undefined : ((json['bauratendateiInput'] as Array<any>).map(BauratendateiInputDtoFromJSON)),
        'dokumente': json['dokumente'] == null ? undefined : ((json['dokumente'] as Array<any>).map(DokumentDtoFromJSON)),
    };
}

export function AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoToJSON(json: any): AbfragevarianteWeiteresVerfahrenStartBearbeitungDto {
    return AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoToJSONTyped(json, false);
}

export function AbfragevarianteWeiteresVerfahrenStartBearbeitungDtoToJSONTyped(value?: AbfragevarianteWeiteresVerfahrenStartBearbeitungDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'version': value['version'],
        'artAbfragevariante': value['artAbfragevariante'],
        'abfragevariantenNr': value['abfragevariantenNr'],
        'name': value['name'],
        'satzungsbeschluss': value['satzungsbeschluss'] == null ? value['satzungsbeschluss'] : serializeDate(value['satzungsbeschluss']),
        'wesentlicheRechtsgrundlage': value['wesentlicheRechtsgrundlage'],
        'wesentlicheRechtsgrundlageFreieEingabe': value['wesentlicheRechtsgrundlageFreieEingabe'],
        'wesentlicheRechtsgrundlageAngabenZurBefreiung': value['wesentlicheRechtsgrundlageAngabenZurBefreiung'],
        'realisierungVon': value['realisierungVon'],
        'gfWohnenGesamt': value['gfWohnenGesamt'],
        'gfWohnenBaurechtlichGenehmigt': value['gfWohnenBaurechtlichGenehmigt'],
        'gfWohnenBaurechtlichFestgesetzt': value['gfWohnenBaurechtlichFestgesetzt'],
        'gfWohnenSobonUrsaechlich': value['gfWohnenSobonUrsaechlich'],
        'gfWohnenBestandswohnbaurecht': value['gfWohnenBestandswohnbaurecht'],
        'gfWohnenSonderwohnformen': value['gfWohnenSonderwohnformen'],
        'gfWohnenStudentischesWohnen': value['gfWohnenStudentischesWohnen'],
        'gfWohnenSeniorinnenWohnen': value['gfWohnenSeniorinnenWohnen'],
        'gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen': value['gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen'],
        'gfAnmerkung': value['gfAnmerkung'],
        'weGesamt': value['weGesamt'],
        'weBaurechtlichGenehmigt': value['weBaurechtlichGenehmigt'],
        'weBaurechtlichFestgesetzt': value['weBaurechtlichFestgesetzt'],
        'weSonderwohnformen': value['weSonderwohnformen'],
        'weStudentischesWohnen': value['weStudentischesWohnen'],
        'weSeniorinnenWohnen': value['weSeniorinnenWohnen'],
        'weWeiteresNichtInfrastrukturrelevantesWohnen': value['weWeiteresNichtInfrastrukturrelevantesWohnen'],
        'weAnmerkung': value['weAnmerkung'],
        'bauabschnitte': value['bauabschnitte'] == null ? undefined : ((value['bauabschnitte'] as Array<any>).map(BauabschnittDtoToJSON)),
        'sobonOrientierungswertJahrPlanungsursaechlich': value['sobonOrientierungswertJahrPlanungsursaechlich'],
        'sobonBerechnung': SobonBerechnungDtoToJSON(value['sobonBerechnung']),
        'stammdatenGueltigAb': value['stammdatenGueltigAb'] == null ? value['stammdatenGueltigAb'] : serializeDate(value['stammdatenGueltigAb']),
        'anmerkung': value['anmerkung'],
        'hasBauratendateiInput': value['hasBauratendateiInput'],
        'anmerkungBauratendateiInput': value['anmerkungBauratendateiInput'],
        'bauratendateiInputBasis': BauratendateiInputDtoToJSON(value['bauratendateiInputBasis']),
        'bauratendateiInput': value['bauratendateiInput'] == null ? undefined : ((value['bauratendateiInput'] as Array<any>).map(BauratendateiInputDtoToJSON)),
        'dokumente': value['dokumente'] == null ? undefined : ((value['dokumente'] as Array<any>).map(DokumentDtoToJSON)),
    };
}

