/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { Baurate } from './Baurate';
import {
    BaurateFromJSON,
    BaurateFromJSONTyped,
    BaurateToJSON,
} from './Baurate';

/**
 * 
 * @export
 * @interface Baugebiet
 */
export interface Baugebiet {
    /**
     * 
     * @type {string}
     * @memberof Baugebiet
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof Baugebiet
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof Baugebiet
     */
    createdDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof Baugebiet
     */
    lastModifiedDateTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof Baugebiet
     */
    bezeichnung?: string;
    /**
     * 
     * @type {string}
     * @memberof Baugebiet
     */
    artBaulicheNutzung?: BaugebietArtBaulicheNutzungEnum;
    /**
     * 
     * @type {string}
     * @memberof Baugebiet
     */
    artBaulicheNutzungFreieEingabe?: string;
    /**
     * 
     * @type {number}
     * @memberof Baugebiet
     */
    realisierungVon?: number;
    /**
     * 
     * @type {number}
     * @memberof Baugebiet
     */
    gfWohnenGeplant?: number;
    /**
     * 
     * @type {number}
     * @memberof Baugebiet
     */
    gfWohnenBaurechtlichGenehmigt?: number;
    /**
     * 
     * @type {number}
     * @memberof Baugebiet
     */
    gfWohnenBaurechtlichFestgesetzt?: number;
    /**
     * 
     * @type {number}
     * @memberof Baugebiet
     */
    weGeplant?: number;
    /**
     * 
     * @type {number}
     * @memberof Baugebiet
     */
    weBaurechtlichGenehmigt?: number;
    /**
     * 
     * @type {number}
     * @memberof Baugebiet
     */
    weBaurechtlichFestgesetzt?: number;
    /**
     * 
     * @type {Array<Baurate>}
     * @memberof Baugebiet
     */
    bauraten?: Array<Baurate>;
    /**
     * 
     * @type {boolean}
     * @memberof Baugebiet
     */
    technical?: boolean;
}


/**
 * @export
 */
export const BaugebietArtBaulicheNutzungEnum = {
    Unspecified: 'UNSPECIFIED',
    Wr: 'WR',
    Wa: 'WA',
    Mu: 'MU',
    Mk: 'MK',
    Mi: 'MI',
    Ge: 'GE',
    FreieEingabe: 'FREIE_EINGABE'
} as const;
export type BaugebietArtBaulicheNutzungEnum = typeof BaugebietArtBaulicheNutzungEnum[keyof typeof BaugebietArtBaulicheNutzungEnum];


/**
 * Check if a given object implements the Baugebiet interface.
 */
export function instanceOfBaugebiet(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function BaugebietFromJSON(json: any): Baugebiet {
    return BaugebietFromJSONTyped(json, false);
}

export function BaugebietFromJSONTyped(json: any, ignoreDiscriminator: boolean): Baugebiet {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'version': !exists(json, 'version') ? undefined : json['version'],
        'createdDateTime': !exists(json, 'createdDateTime') ? undefined : (new Date(json['createdDateTime'])),
        'lastModifiedDateTime': !exists(json, 'lastModifiedDateTime') ? undefined : (new Date(json['lastModifiedDateTime'])),
        'bezeichnung': !exists(json, 'bezeichnung') ? undefined : json['bezeichnung'],
        'artBaulicheNutzung': !exists(json, 'artBaulicheNutzung') ? undefined : json['artBaulicheNutzung'],
        'artBaulicheNutzungFreieEingabe': !exists(json, 'artBaulicheNutzungFreieEingabe') ? undefined : json['artBaulicheNutzungFreieEingabe'],
        'realisierungVon': !exists(json, 'realisierungVon') ? undefined : json['realisierungVon'],
        'gfWohnenGeplant': !exists(json, 'gfWohnenGeplant') ? undefined : json['gfWohnenGeplant'],
        'gfWohnenBaurechtlichGenehmigt': !exists(json, 'gfWohnenBaurechtlichGenehmigt') ? undefined : json['gfWohnenBaurechtlichGenehmigt'],
        'gfWohnenBaurechtlichFestgesetzt': !exists(json, 'gfWohnenBaurechtlichFestgesetzt') ? undefined : json['gfWohnenBaurechtlichFestgesetzt'],
        'weGeplant': !exists(json, 'weGeplant') ? undefined : json['weGeplant'],
        'weBaurechtlichGenehmigt': !exists(json, 'weBaurechtlichGenehmigt') ? undefined : json['weBaurechtlichGenehmigt'],
        'weBaurechtlichFestgesetzt': !exists(json, 'weBaurechtlichFestgesetzt') ? undefined : json['weBaurechtlichFestgesetzt'],
        'bauraten': !exists(json, 'bauraten') ? undefined : ((json['bauraten'] as Array<any>).map(BaurateFromJSON)),
        'technical': !exists(json, 'technical') ? undefined : json['technical'],
    };
}

export function BaugebietToJSON(value?: Baugebiet | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'version': value.version,
        'createdDateTime': value.createdDateTime === undefined ? undefined : (value.createdDateTime.toISOString()),
        'lastModifiedDateTime': value.lastModifiedDateTime === undefined ? undefined : (value.lastModifiedDateTime.toISOString()),
        'bezeichnung': value.bezeichnung,
        'artBaulicheNutzung': value.artBaulicheNutzung,
        'artBaulicheNutzungFreieEingabe': value.artBaulicheNutzungFreieEingabe,
        'realisierungVon': value.realisierungVon,
        'gfWohnenGeplant': value.gfWohnenGeplant,
        'gfWohnenBaurechtlichGenehmigt': value.gfWohnenBaurechtlichGenehmigt,
        'gfWohnenBaurechtlichFestgesetzt': value.gfWohnenBaurechtlichFestgesetzt,
        'weGeplant': value.weGeplant,
        'weBaurechtlichGenehmigt': value.weBaurechtlichGenehmigt,
        'weBaurechtlichFestgesetzt': value.weBaurechtlichFestgesetzt,
        'bauraten': value.bauraten === undefined ? undefined : ((value.bauraten as Array<any>).map(BaurateToJSON)),
        'technical': value.technical,
    };
}

