/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { VerortungMultiPolygonDto } from './VerortungMultiPolygonDto';
import {
    VerortungMultiPolygonDtoFromJSON,
    VerortungMultiPolygonDtoFromJSONTyped,
    VerortungMultiPolygonDtoToJSON,
    VerortungMultiPolygonDtoToJSONTyped,
} from './VerortungMultiPolygonDto';
import type { AbfragevarianteBauleitplanverfahrenAngelegtDto } from './AbfragevarianteBauleitplanverfahrenAngelegtDto';
import {
    AbfragevarianteBauleitplanverfahrenAngelegtDtoFromJSON,
    AbfragevarianteBauleitplanverfahrenAngelegtDtoFromJSONTyped,
    AbfragevarianteBauleitplanverfahrenAngelegtDtoToJSON,
    AbfragevarianteBauleitplanverfahrenAngelegtDtoToJSONTyped,
} from './AbfragevarianteBauleitplanverfahrenAngelegtDto';
import type { AbfrageAngelegtDto } from './AbfrageAngelegtDto';
import {
    AbfrageAngelegtDtoFromJSON,
    AbfrageAngelegtDtoFromJSONTyped,
    AbfrageAngelegtDtoToJSON,
    AbfrageAngelegtDtoToJSONTyped,
} from './AbfrageAngelegtDto';
import type { UncertainBoolean } from './UncertainBoolean';
import {
    UncertainBooleanFromJSON,
    UncertainBooleanFromJSONTyped,
    UncertainBooleanToJSON,
    UncertainBooleanToJSONTyped,
} from './UncertainBoolean';
import type { DokumentDto } from './DokumentDto';
import {
    DokumentDtoFromJSON,
    DokumentDtoFromJSONTyped,
    DokumentDtoToJSON,
    DokumentDtoToJSONTyped,
} from './DokumentDto';
import type { AdresseDto } from './AdresseDto';
import {
    AdresseDtoFromJSON,
    AdresseDtoFromJSONTyped,
    AdresseDtoToJSON,
    AdresseDtoToJSONTyped,
} from './AdresseDto';

/**
 * 
 * @export
 * @interface BauleitplanverfahrenAngelegtDto
 */
export interface BauleitplanverfahrenAngelegtDto extends AbfrageAngelegtDto {
    /**
     * 
     * @type {string}
     * @memberof BauleitplanverfahrenAngelegtDto
     */
    bebauungsplannummer?: string;
    /**
     * 
     * @type {UncertainBoolean}
     * @memberof BauleitplanverfahrenAngelegtDto
     */
    sobonRelevant: UncertainBoolean;
    /**
     * 
     * @type {BauleitplanverfahrenAngelegtDtoSobonJahrEnum}
     * @memberof BauleitplanverfahrenAngelegtDto
     */
    sobonJahr?: BauleitplanverfahrenAngelegtDtoSobonJahrEnum;
    /**
     * 
     * @type {BauleitplanverfahrenAngelegtDtoVerfahrensstandEnum}
     * @memberof BauleitplanverfahrenAngelegtDto
     */
    verfahrensstand: BauleitplanverfahrenAngelegtDtoVerfahrensstandEnum;
    /**
     * 
     * @type {string}
     * @memberof BauleitplanverfahrenAngelegtDto
     */
    verfahrensstandFreieEingabe?: string;
    /**
     * 
     * @type {AdresseDto}
     * @memberof BauleitplanverfahrenAngelegtDto
     */
    adresse?: AdresseDto;
    /**
     * 
     * @type {VerortungMultiPolygonDto}
     * @memberof BauleitplanverfahrenAngelegtDto
     */
    verortung?: VerortungMultiPolygonDto;
    /**
     * 
     * @type {Array<DokumentDto>}
     * @memberof BauleitplanverfahrenAngelegtDto
     */
    dokumente?: Array<DokumentDto>;
    /**
     * 
     * @type {Date}
     * @memberof BauleitplanverfahrenAngelegtDto
     */
    fristBearbeitung: Date;
    /**
     * 
     * @type {UncertainBoolean}
     * @memberof BauleitplanverfahrenAngelegtDto
     */
    mitzeichnungBeschlussentwurf: UncertainBoolean;
    /**
     * 
     * @type {Array<AbfragevarianteBauleitplanverfahrenAngelegtDto>}
     * @memberof BauleitplanverfahrenAngelegtDto
     */
    abfragevariantenBauleitplanverfahren: Array<AbfragevarianteBauleitplanverfahrenAngelegtDto>;
}


/**
 * @export
 */
export const BauleitplanverfahrenAngelegtDtoSobonJahrEnum = {
    Jahr1995: 'JAHR_1995',
    Jahr1997: 'JAHR_1997',
    Jahr2001: 'JAHR_2001',
    Jahr2006: 'JAHR_2006',
    Jahr2012: 'JAHR_2012',
    Jahr2017: 'JAHR_2017',
    Jahr2017Plus: 'JAHR_2017_PLUS',
    Jahr2021: 'JAHR_2021'
} as const;
export type BauleitplanverfahrenAngelegtDtoSobonJahrEnum = typeof BauleitplanverfahrenAngelegtDtoSobonJahrEnum[keyof typeof BauleitplanverfahrenAngelegtDtoSobonJahrEnum];

/**
 * @export
 */
export const BauleitplanverfahrenAngelegtDtoVerfahrensstandEnum = {
    Unspecified: 'UNSPECIFIED',
    SimuliertVorbereitungAufstellungsbeschluss: 'SIMULIERT_VORBEREITUNG_AUFSTELLUNGSBESCHLUSS',
    SimuliertVorbereitungWettbewerbauslobung: 'SIMULIERT_VORBEREITUNG_WETTBEWERBAUSLOBUNG',
    VorbereitungFruehzeitigeBeteiligung: 'VORBEREITUNG_FRUEHZEITIGE_BETEILIGUNG',
    VorbereitungBilligungsbeschlussStaedtebaulicherVertrag: 'VORBEREITUNG_BILLIGUNGSBESCHLUSS_STAEDTEBAULICHER_VERTRAG',
    VorbereitungSatzungsbeschluss: 'VORBEREITUNG_SATZUNGSBESCHLUSS',
    InkraftgetretenVeroeffentlichungAmtsblatt: 'INKRAFTGETRETEN_VEROEFFENTLICHUNG_AMTSBLATT',
    InkraftgetretenFoerdermixplan: 'INKRAFTGETRETEN_FOERDERMIXPLAN',
    VorbereitungEckdatenbeschluss: 'VORBEREITUNG_ECKDATENBESCHLUSS',
    VorbereitungWettbewerbauslobung: 'VORBEREITUNG_WETTBEWERBAUSLOBUNG',
    VorliegenderSatzungsbeschluss: 'VORLIEGENDER_SATZUNGSBESCHLUSS',
    VorbereitungAufstellungsbeschluss: 'VORBEREITUNG_AUFSTELLUNGSBESCHLUSS',
    RechtsverbindlichkeitAmtsblatt: 'RECHTSVERBINDLICHKEIT_AMTSBLATT',
    Aufteilungsplan: 'AUFTEILUNGSPLAN',
    VorbereitungVorbescheid: 'VORBEREITUNG_VORBESCHEID',
    VorbereitungBaugenehmigung: 'VORBEREITUNG_BAUGENEHMIGUNG',
    VorabfrageOhneKonkretenStand: 'VORABFRAGE_OHNE_KONKRETEN_STAND',
    Strukturkonzept: 'STRUKTURKONZEPT',
    Rahmenplanung: 'RAHMENPLANUNG',
    Potentialuntersuchung: 'POTENTIALUNTERSUCHUNG',
    StaedtebaulicheSanierungsmassnahme: 'STAEDTEBAULICHE_SANIERUNGSMASSNAHME',
    StaedtebaulicheEntwicklungsmassnahme: 'STAEDTEBAULICHE_ENTWICKLUNGSMASSNAHME',
    FreieEingabe: 'FREIE_EINGABE',
    Standortabfrage: 'STANDORTABFRAGE'
} as const;
export type BauleitplanverfahrenAngelegtDtoVerfahrensstandEnum = typeof BauleitplanverfahrenAngelegtDtoVerfahrensstandEnum[keyof typeof BauleitplanverfahrenAngelegtDtoVerfahrensstandEnum];


/**
 * Check if a given object implements the BauleitplanverfahrenAngelegtDto interface.
 */
export function instanceOfBauleitplanverfahrenAngelegtDto(value: object): value is BauleitplanverfahrenAngelegtDto {
    if (!('sobonRelevant' in value) || value['sobonRelevant'] === undefined) return false;
    if (!('verfahrensstand' in value) || value['verfahrensstand'] === undefined) return false;
    if (!('fristBearbeitung' in value) || value['fristBearbeitung'] === undefined) return false;
    if (!('mitzeichnungBeschlussentwurf' in value) || value['mitzeichnungBeschlussentwurf'] === undefined) return false;
    if (!('abfragevariantenBauleitplanverfahren' in value) || value['abfragevariantenBauleitplanverfahren'] === undefined) return false;
    return true;
}

export function BauleitplanverfahrenAngelegtDtoFromJSON(json: any): BauleitplanverfahrenAngelegtDto {
    return BauleitplanverfahrenAngelegtDtoFromJSONTyped(json, false);
}

export function BauleitplanverfahrenAngelegtDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): BauleitplanverfahrenAngelegtDto {
    if (json == null) {
        return json;
    }
    if (!ignoreDiscriminator) {
        if (json['artAbfrage'] === 'BAULEITPLANVERFAHREN') {
            return BauleitplanverfahrenAngelegtDtoFromJSONTyped(json, true);
        }

    }
    return {
        ...AbfrageAngelegtDtoFromJSONTyped(json, true),
        'bebauungsplannummer': json['bebauungsplannummer'] == null ? undefined : json['bebauungsplannummer'],
        'sobonRelevant': UncertainBooleanFromJSON(json['sobonRelevant']),
        'sobonJahr': json['sobonJahr'] == null ? undefined : json['sobonJahr'],
        'verfahrensstand': json['verfahrensstand'],
        'verfahrensstandFreieEingabe': json['verfahrensstandFreieEingabe'] == null ? undefined : json['verfahrensstandFreieEingabe'],
        'adresse': json['adresse'] == null ? undefined : AdresseDtoFromJSON(json['adresse']),
        'verortung': json['verortung'] == null ? undefined : VerortungMultiPolygonDtoFromJSON(json['verortung']),
        'dokumente': json['dokumente'] == null ? undefined : ((json['dokumente'] as Array<any>).map(DokumentDtoFromJSON)),
        'fristBearbeitung': (new Date(json['fristBearbeitung'])),
        'mitzeichnungBeschlussentwurf': UncertainBooleanFromJSON(json['mitzeichnungBeschlussentwurf']),
        'abfragevariantenBauleitplanverfahren': ((json['abfragevariantenBauleitplanverfahren'] as Array<any>).map(AbfragevarianteBauleitplanverfahrenAngelegtDtoFromJSON)),
    };
}

export function BauleitplanverfahrenAngelegtDtoToJSON(json: any): BauleitplanverfahrenAngelegtDto {
    return BauleitplanverfahrenAngelegtDtoToJSONTyped(json, false);
}

export function BauleitplanverfahrenAngelegtDtoToJSONTyped(value?: BauleitplanverfahrenAngelegtDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    if (!ignoreDiscriminator) {
        switch (value['artAbfrage']) {
            default:
                return value;
        }
    }

    return {
        ...AbfrageAngelegtDtoToJSONTyped(value, true),
        'bebauungsplannummer': value['bebauungsplannummer'],
        'sobonRelevant': UncertainBooleanToJSON(value['sobonRelevant']),
        'sobonJahr': value['sobonJahr'],
        'verfahrensstand': value['verfahrensstand'],
        'verfahrensstandFreieEingabe': value['verfahrensstandFreieEingabe'],
        'adresse': AdresseDtoToJSON(value['adresse']),
        'verortung': VerortungMultiPolygonDtoToJSON(value['verortung']),
        'dokumente': value['dokumente'] == null ? undefined : ((value['dokumente'] as Array<any>).map(DokumentDtoToJSON)),
        'fristBearbeitung': value['fristBearbeitung'].toISOString().substring(0,10),
        'mitzeichnungBeschlussentwurf': UncertainBooleanToJSON(value['mitzeichnungBeschlussentwurf']),
        'abfragevariantenBauleitplanverfahren': ((value['abfragevariantenBauleitplanverfahren'] as Array<any>).map(AbfragevarianteBauleitplanverfahrenAngelegtDtoToJSON)),
    };
}

