/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface EntityModelAbfragevariante
 */
export interface EntityModelAbfragevariante {
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevariante
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof EntityModelAbfragevariante
     */
    createdDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EntityModelAbfragevariante
     */
    lastModifiedDateTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevariante
     */
    abfragevariantenNr?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevariante
     */
    name?: string;
    /**
     * 
     * @type {EntityModelAbfragevarianteArtAbfragevarianteEnum}
     * @memberof EntityModelAbfragevariante
     */
    artAbfragevariante?: EntityModelAbfragevarianteArtAbfragevarianteEnum;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof EntityModelAbfragevariante
     */
    links?: { [key: string]: Link; };
}


/**
 * @export
 */
export const EntityModelAbfragevarianteArtAbfragevarianteEnum = {
    Unspecified: 'UNSPECIFIED',
    Bauleitplanverfahren: 'BAULEITPLANVERFAHREN',
    Baugenehmigungsverfahren: 'BAUGENEHMIGUNGSVERFAHREN',
    WeiteresVerfahren: 'WEITERES_VERFAHREN'
} as const;
export type EntityModelAbfragevarianteArtAbfragevarianteEnum = typeof EntityModelAbfragevarianteArtAbfragevarianteEnum[keyof typeof EntityModelAbfragevarianteArtAbfragevarianteEnum];


/**
 * Check if a given object implements the EntityModelAbfragevariante interface.
 */
export function instanceOfEntityModelAbfragevariante(value: object): value is EntityModelAbfragevariante {
    return true;
}

export function EntityModelAbfragevarianteFromJSON(json: any): EntityModelAbfragevariante {
    return EntityModelAbfragevarianteFromJSONTyped(json, false);
}

export function EntityModelAbfragevarianteFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityModelAbfragevariante {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'createdDateTime': json['createdDateTime'] == null ? undefined : (new Date(json['createdDateTime'])),
        'lastModifiedDateTime': json['lastModifiedDateTime'] == null ? undefined : (new Date(json['lastModifiedDateTime'])),
        'abfragevariantenNr': json['abfragevariantenNr'] == null ? undefined : json['abfragevariantenNr'],
        'name': json['name'] == null ? undefined : json['name'],
        'artAbfragevariante': json['artAbfragevariante'] == null ? undefined : json['artAbfragevariante'],
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function EntityModelAbfragevarianteToJSON(json: any): EntityModelAbfragevariante {
    return EntityModelAbfragevarianteToJSONTyped(json, false);
}

export function EntityModelAbfragevarianteToJSONTyped(value?: EntityModelAbfragevariante | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'createdDateTime': value['createdDateTime'] == null ? value['createdDateTime'] : value['createdDateTime'].toISOString(),
        'lastModifiedDateTime': value['lastModifiedDateTime'] == null ? value['lastModifiedDateTime'] : value['lastModifiedDateTime'].toISOString(),
        'abfragevariantenNr': value['abfragevariantenNr'],
        'name': value['name'],
        'artAbfragevariante': value['artAbfragevariante'],
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

