/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { Bedarfsmeldung } from './Bedarfsmeldung';
import {
    BedarfsmeldungFromJSON,
    BedarfsmeldungFromJSONTyped,
    BedarfsmeldungToJSON,
    BedarfsmeldungToJSONTyped,
} from './Bedarfsmeldung';
import type { Bauabschnitt } from './Bauabschnitt';
import {
    BauabschnittFromJSON,
    BauabschnittFromJSONTyped,
    BauabschnittToJSON,
    BauabschnittToJSONTyped,
} from './Bauabschnitt';
import type { BauratendateiInput } from './BauratendateiInput';
import {
    BauratendateiInputFromJSON,
    BauratendateiInputFromJSONTyped,
    BauratendateiInputToJSON,
    BauratendateiInputToJSONTyped,
} from './BauratendateiInput';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface EntityModelAbfragevarianteBaugenehmigungsverfahren
 */
export interface EntityModelAbfragevarianteBaugenehmigungsverfahren {
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    createdDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    lastModifiedDateTime?: Date;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    abfragevariantenNr?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    name?: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    wesentlicheRechtsgrundlage?: Array<EntityModelAbfragevarianteBaugenehmigungsverfahrenWesentlicheRechtsgrundlageEnum>;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    wesentlicheRechtsgrundlageFreieEingabe?: string;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    realisierungVon?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    gfWohnenGesamt?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    gfWohnenBaurechtlichGenehmigt?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    gfWohnenBaurechtlichFestgesetzt?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    gfWohnenBestandswohnbaurecht?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    gfWohnenSonderwohnformen?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    gfWohnenStudentischesWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    gfWohnenSeniorinnenWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    gfWohnenGenossenschaftlichesWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    gfAnmerkung?: string;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    weGesamt?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    weBaurechtlichGenehmigt?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    weBaurechtlichFestgesetzt?: number;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    weSonderwohnformen?: boolean;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    weStudentischesWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    weSeniorinnenWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    weGenossenschaftlichesWohnen?: number;
    /**
     * 
     * @type {number}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    weWeiteresNichtInfrastrukturrelevantesWohnen?: number;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    weAnmerkung?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    sobonOrientierungswertJahrPlanungsursaechlich?: EntityModelAbfragevarianteBaugenehmigungsverfahrenSobonOrientierungswertJahrPlanungsursaechlichEnum;
    /**
     * 
     * @type {Date}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    stammdatenGueltigAb?: Date;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    anmerkung?: string;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    hasBauratendateiInput?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    anmerkungBauratendateiInput?: string;
    /**
     * 
     * @type {BauratendateiInput}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    bauratendateiInputBasis?: BauratendateiInput;
    /**
     * 
     * @type {Array<BauratendateiInput>}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    bauratendateiInput?: Array<BauratendateiInput>;
    /**
     * 
     * @type {Array<Bedarfsmeldung>}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    bedarfsmeldungFachreferate?: Array<Bedarfsmeldung>;
    /**
     * 
     * @type {Array<Bedarfsmeldung>}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    bedarfsmeldungAbfrageersteller?: Array<Bedarfsmeldung>;
    /**
     * 
     * @type {Array<Bauabschnitt>}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    bauabschnitte?: Array<Bauabschnitt>;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    ausgeloesterBedarfImBaugebietBeruecksichtigenKita?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    ausgeloesterBedarfMitversorgungImBplanKita?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    ausgeloesterBedarfMitversorgungInBestEinrichtungenKita?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauKita?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    ausgeloesterBedarfImBaugebietBeruecksichtigenSchule?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    ausgeloesterBedarfMitversorgungImBplanSchule?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    ausgeloesterBedarfMitversorgungInBestEinrichtungenSchule?: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauSchule?: boolean;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    anmerkungFachreferate?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    anmerkungAbfrageersteller?: string;
    /**
     * 
     * @type {string}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    artAbfragevariante?: EntityModelAbfragevarianteBaugenehmigungsverfahrenArtAbfragevarianteEnum;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof EntityModelAbfragevarianteBaugenehmigungsverfahren
     */
    links?: { [key: string]: Link; };
}


/**
 * @export
 */
export const EntityModelAbfragevarianteBaugenehmigungsverfahrenWesentlicheRechtsgrundlageEnum = {
    QualifizierterBebauungsplan: 'QUALIFIZIERTER_BEBAUUNGSPLAN',
    VorhabensbezogenerBebauungsplan: 'VORHABENSBEZOGENER_BEBAUUNGSPLAN',
    EinfacherBebauungsplanParagraph30: 'EINFACHER_BEBAUUNGSPLAN_PARAGRAPH_30',
    EinfacherBebauungsplanParagraph30Ivm3435: 'EINFACHER_BEBAUUNGSPLAN_PARAGRAPH_30_IVM_34_35',
    SektoralerBebauungsplanParagraph9: 'SEKTORALER_BEBAUUNGSPLAN_PARAGRAPH_9',
    SektoralerBebauungsplanParagraph30Ivm3435: 'SEKTORALER_BEBAUUNGSPLAN_PARAGRAPH_30_IVM_34_35',
    Innenbereich: 'INNENBEREICH',
    Aussenbereich: 'AUSSENBEREICH',
    Befreiung: 'BEFREIUNG',
    FreieEingabe: 'FREIE_EINGABE'
} as const;
export type EntityModelAbfragevarianteBaugenehmigungsverfahrenWesentlicheRechtsgrundlageEnum = typeof EntityModelAbfragevarianteBaugenehmigungsverfahrenWesentlicheRechtsgrundlageEnum[keyof typeof EntityModelAbfragevarianteBaugenehmigungsverfahrenWesentlicheRechtsgrundlageEnum];

/**
 * @export
 */
export const EntityModelAbfragevarianteBaugenehmigungsverfahrenSobonOrientierungswertJahrPlanungsursaechlichEnum = {
    Unspecified: 'UNSPECIFIED',
    Jahr2014: 'JAHR_2014',
    Jahr2017: 'JAHR_2017',
    Jahr2022: 'JAHR_2022',
    Jahr2024: 'JAHR_2024',
    Jahr202434: 'JAHR_2024_34',
    Standortabfrage: 'STANDORTABFRAGE'
} as const;
export type EntityModelAbfragevarianteBaugenehmigungsverfahrenSobonOrientierungswertJahrPlanungsursaechlichEnum = typeof EntityModelAbfragevarianteBaugenehmigungsverfahrenSobonOrientierungswertJahrPlanungsursaechlichEnum[keyof typeof EntityModelAbfragevarianteBaugenehmigungsverfahrenSobonOrientierungswertJahrPlanungsursaechlichEnum];

/**
 * @export
 */
export const EntityModelAbfragevarianteBaugenehmigungsverfahrenArtAbfragevarianteEnum = {
    Unspecified: 'UNSPECIFIED',
    Bauleitplanverfahren: 'BAULEITPLANVERFAHREN',
    Baugenehmigungsverfahren: 'BAUGENEHMIGUNGSVERFAHREN',
    WeiteresVerfahren: 'WEITERES_VERFAHREN'
} as const;
export type EntityModelAbfragevarianteBaugenehmigungsverfahrenArtAbfragevarianteEnum = typeof EntityModelAbfragevarianteBaugenehmigungsverfahrenArtAbfragevarianteEnum[keyof typeof EntityModelAbfragevarianteBaugenehmigungsverfahrenArtAbfragevarianteEnum];


/**
 * Check if a given object implements the EntityModelAbfragevarianteBaugenehmigungsverfahren interface.
 */
export function instanceOfEntityModelAbfragevarianteBaugenehmigungsverfahren(value: object): value is EntityModelAbfragevarianteBaugenehmigungsverfahren {
    return true;
}

export function EntityModelAbfragevarianteBaugenehmigungsverfahrenFromJSON(json: any): EntityModelAbfragevarianteBaugenehmigungsverfahren {
    return EntityModelAbfragevarianteBaugenehmigungsverfahrenFromJSONTyped(json, false);
}

export function EntityModelAbfragevarianteBaugenehmigungsverfahrenFromJSONTyped(json: any, ignoreDiscriminator: boolean): EntityModelAbfragevarianteBaugenehmigungsverfahren {
    if (json == null) {
        return json;
    }
    return {
        
        'version': json['version'] == null ? undefined : json['version'],
        'createdDateTime': json['createdDateTime'] == null ? undefined : (new Date(json['createdDateTime'])),
        'lastModifiedDateTime': json['lastModifiedDateTime'] == null ? undefined : (new Date(json['lastModifiedDateTime'])),
        'abfragevariantenNr': json['abfragevariantenNr'] == null ? undefined : json['abfragevariantenNr'],
        'name': json['name'] == null ? undefined : json['name'],
        'wesentlicheRechtsgrundlage': json['wesentlicheRechtsgrundlage'] == null ? undefined : json['wesentlicheRechtsgrundlage'],
        'wesentlicheRechtsgrundlageFreieEingabe': json['wesentlicheRechtsgrundlageFreieEingabe'] == null ? undefined : json['wesentlicheRechtsgrundlageFreieEingabe'],
        'realisierungVon': json['realisierungVon'] == null ? undefined : json['realisierungVon'],
        'gfWohnenGesamt': json['gfWohnenGesamt'] == null ? undefined : json['gfWohnenGesamt'],
        'gfWohnenBaurechtlichGenehmigt': json['gfWohnenBaurechtlichGenehmigt'] == null ? undefined : json['gfWohnenBaurechtlichGenehmigt'],
        'gfWohnenBaurechtlichFestgesetzt': json['gfWohnenBaurechtlichFestgesetzt'] == null ? undefined : json['gfWohnenBaurechtlichFestgesetzt'],
        'gfWohnenBestandswohnbaurecht': json['gfWohnenBestandswohnbaurecht'] == null ? undefined : json['gfWohnenBestandswohnbaurecht'],
        'gfWohnenSonderwohnformen': json['gfWohnenSonderwohnformen'] == null ? undefined : json['gfWohnenSonderwohnformen'],
        'gfWohnenStudentischesWohnen': json['gfWohnenStudentischesWohnen'] == null ? undefined : json['gfWohnenStudentischesWohnen'],
        'gfWohnenSeniorinnenWohnen': json['gfWohnenSeniorinnenWohnen'] == null ? undefined : json['gfWohnenSeniorinnenWohnen'],
        'gfWohnenGenossenschaftlichesWohnen': json['gfWohnenGenossenschaftlichesWohnen'] == null ? undefined : json['gfWohnenGenossenschaftlichesWohnen'],
        'gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen': json['gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen'] == null ? undefined : json['gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen'],
        'gfAnmerkung': json['gfAnmerkung'] == null ? undefined : json['gfAnmerkung'],
        'weGesamt': json['weGesamt'] == null ? undefined : json['weGesamt'],
        'weBaurechtlichGenehmigt': json['weBaurechtlichGenehmigt'] == null ? undefined : json['weBaurechtlichGenehmigt'],
        'weBaurechtlichFestgesetzt': json['weBaurechtlichFestgesetzt'] == null ? undefined : json['weBaurechtlichFestgesetzt'],
        'weSonderwohnformen': json['weSonderwohnformen'] == null ? undefined : json['weSonderwohnformen'],
        'weStudentischesWohnen': json['weStudentischesWohnen'] == null ? undefined : json['weStudentischesWohnen'],
        'weSeniorinnenWohnen': json['weSeniorinnenWohnen'] == null ? undefined : json['weSeniorinnenWohnen'],
        'weGenossenschaftlichesWohnen': json['weGenossenschaftlichesWohnen'] == null ? undefined : json['weGenossenschaftlichesWohnen'],
        'weWeiteresNichtInfrastrukturrelevantesWohnen': json['weWeiteresNichtInfrastrukturrelevantesWohnen'] == null ? undefined : json['weWeiteresNichtInfrastrukturrelevantesWohnen'],
        'weAnmerkung': json['weAnmerkung'] == null ? undefined : json['weAnmerkung'],
        'sobonOrientierungswertJahrPlanungsursaechlich': json['sobonOrientierungswertJahrPlanungsursaechlich'] == null ? undefined : json['sobonOrientierungswertJahrPlanungsursaechlich'],
        'stammdatenGueltigAb': json['stammdatenGueltigAb'] == null ? undefined : (new Date(json['stammdatenGueltigAb'])),
        'anmerkung': json['anmerkung'] == null ? undefined : json['anmerkung'],
        'hasBauratendateiInput': json['hasBauratendateiInput'] == null ? undefined : json['hasBauratendateiInput'],
        'anmerkungBauratendateiInput': json['anmerkungBauratendateiInput'] == null ? undefined : json['anmerkungBauratendateiInput'],
        'bauratendateiInputBasis': json['bauratendateiInputBasis'] == null ? undefined : BauratendateiInputFromJSON(json['bauratendateiInputBasis']),
        'bauratendateiInput': json['bauratendateiInput'] == null ? undefined : ((json['bauratendateiInput'] as Array<any>).map(BauratendateiInputFromJSON)),
        'bedarfsmeldungFachreferate': json['bedarfsmeldungFachreferate'] == null ? undefined : ((json['bedarfsmeldungFachreferate'] as Array<any>).map(BedarfsmeldungFromJSON)),
        'bedarfsmeldungAbfrageersteller': json['bedarfsmeldungAbfrageersteller'] == null ? undefined : ((json['bedarfsmeldungAbfrageersteller'] as Array<any>).map(BedarfsmeldungFromJSON)),
        'bauabschnitte': json['bauabschnitte'] == null ? undefined : ((json['bauabschnitte'] as Array<any>).map(BauabschnittFromJSON)),
        'ausgeloesterBedarfImBaugebietBeruecksichtigenKita': json['ausgeloesterBedarfImBaugebietBeruecksichtigenKita'] == null ? undefined : json['ausgeloesterBedarfImBaugebietBeruecksichtigenKita'],
        'ausgeloesterBedarfMitversorgungImBplanKita': json['ausgeloesterBedarfMitversorgungImBplanKita'] == null ? undefined : json['ausgeloesterBedarfMitversorgungImBplanKita'],
        'ausgeloesterBedarfMitversorgungInBestEinrichtungenKita': json['ausgeloesterBedarfMitversorgungInBestEinrichtungenKita'] == null ? undefined : json['ausgeloesterBedarfMitversorgungInBestEinrichtungenKita'],
        'ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauKita': json['ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauKita'] == null ? undefined : json['ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauKita'],
        'ausgeloesterBedarfImBaugebietBeruecksichtigenSchule': json['ausgeloesterBedarfImBaugebietBeruecksichtigenSchule'] == null ? undefined : json['ausgeloesterBedarfImBaugebietBeruecksichtigenSchule'],
        'ausgeloesterBedarfMitversorgungImBplanSchule': json['ausgeloesterBedarfMitversorgungImBplanSchule'] == null ? undefined : json['ausgeloesterBedarfMitversorgungImBplanSchule'],
        'ausgeloesterBedarfMitversorgungInBestEinrichtungenSchule': json['ausgeloesterBedarfMitversorgungInBestEinrichtungenSchule'] == null ? undefined : json['ausgeloesterBedarfMitversorgungInBestEinrichtungenSchule'],
        'ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauSchule': json['ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauSchule'] == null ? undefined : json['ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauSchule'],
        'anmerkungFachreferate': json['anmerkungFachreferate'] == null ? undefined : json['anmerkungFachreferate'],
        'anmerkungAbfrageersteller': json['anmerkungAbfrageersteller'] == null ? undefined : json['anmerkungAbfrageersteller'],
        'artAbfragevariante': json['artAbfragevariante'] == null ? undefined : json['artAbfragevariante'],
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
    };
}

export function EntityModelAbfragevarianteBaugenehmigungsverfahrenToJSON(json: any): EntityModelAbfragevarianteBaugenehmigungsverfahren {
    return EntityModelAbfragevarianteBaugenehmigungsverfahrenToJSONTyped(json, false);
}

export function EntityModelAbfragevarianteBaugenehmigungsverfahrenToJSONTyped(value?: EntityModelAbfragevarianteBaugenehmigungsverfahren | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'version': value['version'],
        'createdDateTime': value['createdDateTime'] == null ? value['createdDateTime'] : value['createdDateTime'].toISOString(),
        'lastModifiedDateTime': value['lastModifiedDateTime'] == null ? value['lastModifiedDateTime'] : value['lastModifiedDateTime'].toISOString(),
        'abfragevariantenNr': value['abfragevariantenNr'],
        'name': value['name'],
        'wesentlicheRechtsgrundlage': value['wesentlicheRechtsgrundlage'],
        'wesentlicheRechtsgrundlageFreieEingabe': value['wesentlicheRechtsgrundlageFreieEingabe'],
        'realisierungVon': value['realisierungVon'],
        'gfWohnenGesamt': value['gfWohnenGesamt'],
        'gfWohnenBaurechtlichGenehmigt': value['gfWohnenBaurechtlichGenehmigt'],
        'gfWohnenBaurechtlichFestgesetzt': value['gfWohnenBaurechtlichFestgesetzt'],
        'gfWohnenBestandswohnbaurecht': value['gfWohnenBestandswohnbaurecht'],
        'gfWohnenSonderwohnformen': value['gfWohnenSonderwohnformen'],
        'gfWohnenStudentischesWohnen': value['gfWohnenStudentischesWohnen'],
        'gfWohnenSeniorinnenWohnen': value['gfWohnenSeniorinnenWohnen'],
        'gfWohnenGenossenschaftlichesWohnen': value['gfWohnenGenossenschaftlichesWohnen'],
        'gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen': value['gfWohnenWeiteresNichtInfrastrukturrelevantesWohnen'],
        'gfAnmerkung': value['gfAnmerkung'],
        'weGesamt': value['weGesamt'],
        'weBaurechtlichGenehmigt': value['weBaurechtlichGenehmigt'],
        'weBaurechtlichFestgesetzt': value['weBaurechtlichFestgesetzt'],
        'weSonderwohnformen': value['weSonderwohnformen'],
        'weStudentischesWohnen': value['weStudentischesWohnen'],
        'weSeniorinnenWohnen': value['weSeniorinnenWohnen'],
        'weGenossenschaftlichesWohnen': value['weGenossenschaftlichesWohnen'],
        'weWeiteresNichtInfrastrukturrelevantesWohnen': value['weWeiteresNichtInfrastrukturrelevantesWohnen'],
        'weAnmerkung': value['weAnmerkung'],
        'sobonOrientierungswertJahrPlanungsursaechlich': value['sobonOrientierungswertJahrPlanungsursaechlich'],
        'stammdatenGueltigAb': value['stammdatenGueltigAb'] == null ? value['stammdatenGueltigAb'] : value['stammdatenGueltigAb'].toISOString().substring(0,10),
        'anmerkung': value['anmerkung'],
        'hasBauratendateiInput': value['hasBauratendateiInput'],
        'anmerkungBauratendateiInput': value['anmerkungBauratendateiInput'],
        'bauratendateiInputBasis': BauratendateiInputToJSON(value['bauratendateiInputBasis']),
        'bauratendateiInput': value['bauratendateiInput'] == null ? undefined : ((value['bauratendateiInput'] as Array<any>).map(BauratendateiInputToJSON)),
        'bedarfsmeldungFachreferate': value['bedarfsmeldungFachreferate'] == null ? undefined : ((value['bedarfsmeldungFachreferate'] as Array<any>).map(BedarfsmeldungToJSON)),
        'bedarfsmeldungAbfrageersteller': value['bedarfsmeldungAbfrageersteller'] == null ? undefined : ((value['bedarfsmeldungAbfrageersteller'] as Array<any>).map(BedarfsmeldungToJSON)),
        'bauabschnitte': value['bauabschnitte'] == null ? undefined : ((value['bauabschnitte'] as Array<any>).map(BauabschnittToJSON)),
        'ausgeloesterBedarfImBaugebietBeruecksichtigenKita': value['ausgeloesterBedarfImBaugebietBeruecksichtigenKita'],
        'ausgeloesterBedarfMitversorgungImBplanKita': value['ausgeloesterBedarfMitversorgungImBplanKita'],
        'ausgeloesterBedarfMitversorgungInBestEinrichtungenKita': value['ausgeloesterBedarfMitversorgungInBestEinrichtungenKita'],
        'ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauKita': value['ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauKita'],
        'ausgeloesterBedarfImBaugebietBeruecksichtigenSchule': value['ausgeloesterBedarfImBaugebietBeruecksichtigenSchule'],
        'ausgeloesterBedarfMitversorgungImBplanSchule': value['ausgeloesterBedarfMitversorgungImBplanSchule'],
        'ausgeloesterBedarfMitversorgungInBestEinrichtungenSchule': value['ausgeloesterBedarfMitversorgungInBestEinrichtungenSchule'],
        'ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauSchule': value['ausgeloesterBedarfMitversorgungInBestEinrichtungenNachAusbauSchule'],
        'anmerkungFachreferate': value['anmerkungFachreferate'],
        'anmerkungAbfrageersteller': value['anmerkungAbfrageersteller'],
        'artAbfragevariante': value['artAbfragevariante'],
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
    };
}

