/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Jahresrate
 */
export interface Jahresrate {
    /**
     * 
     * @type {number}
     * @memberof Jahresrate
     */
    jahr?: number;
    /**
     * 
     * @type {number}
     * @memberof Jahresrate
     */
    rate?: number;
}

/**
 * Check if a given object implements the Jahresrate interface.
 */
export function instanceOfJahresrate(value: object): value is Jahresrate {
    return true;
}

export function JahresrateFromJSON(json: any): Jahresrate {
    return JahresrateFromJSONTyped(json, false);
}

export function JahresrateFromJSONTyped(json: any, ignoreDiscriminator: boolean): Jahresrate {
    if (json == null) {
        return json;
    }
    return {
        
        'jahr': json['jahr'] == null ? undefined : json['jahr'],
        'rate': json['rate'] == null ? undefined : json['rate'],
    };
}

export function JahresrateToJSON(json: any): Jahresrate {
    return JahresrateToJSONTyped(json, false);
}

export function JahresrateToJSONTyped(value?: Jahresrate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'jahr': value['jahr'],
        'rate': value['rate'],
    };
}

