/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { BearbeitendePersonDto } from './BearbeitendePersonDto';
import {
    BearbeitendePersonDtoFromJSON,
    BearbeitendePersonDtoFromJSONTyped,
    BearbeitendePersonDtoToJSON,
    BearbeitendePersonDtoToJSONTyped,
} from './BearbeitendePersonDto';
import type { DokumentDto } from './DokumentDto';
import {
    DokumentDtoFromJSON,
    DokumentDtoFromJSONTyped,
    DokumentDtoToJSON,
    DokumentDtoToJSONTyped,
} from './DokumentDto';

/**
 * 
 * @export
 * @interface KommentarBauvorhabenDto
 */
export interface KommentarBauvorhabenDto {
    /**
     * 
     * @type {string}
     * @memberof KommentarBauvorhabenDto
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof KommentarBauvorhabenDto
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof KommentarBauvorhabenDto
     */
    createdDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof KommentarBauvorhabenDto
     */
    lastModifiedDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof KommentarBauvorhabenDto
     */
    erstellungsdatum?: Date;
    /**
     * 
     * @type {string}
     * @memberof KommentarBauvorhabenDto
     */
    text?: string;
    /**
     * 
     * @type {Array<DokumentDto>}
     * @memberof KommentarBauvorhabenDto
     */
    dokumente?: Array<DokumentDto>;
    /**
     * 
     * @type {BearbeitendePersonDto}
     * @memberof KommentarBauvorhabenDto
     */
    bearbeitendePerson?: BearbeitendePersonDto;
    /**
     * 
     * @type {string}
     * @memberof KommentarBauvorhabenDto
     */
    bauvorhaben?: string;
}

/**
 * Check if a given object implements the KommentarBauvorhabenDto interface.
 */
export function instanceOfKommentarBauvorhabenDto(value: object): value is KommentarBauvorhabenDto {
    return true;
}

export function KommentarBauvorhabenDtoFromJSON(json: any): KommentarBauvorhabenDto {
    return KommentarBauvorhabenDtoFromJSONTyped(json, false);
}

export function KommentarBauvorhabenDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): KommentarBauvorhabenDto {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'version': json['version'] == null ? undefined : json['version'],
        'createdDateTime': json['createdDateTime'] == null ? undefined : (new Date(json['createdDateTime'])),
        'lastModifiedDateTime': json['lastModifiedDateTime'] == null ? undefined : (new Date(json['lastModifiedDateTime'])),
        'erstellungsdatum': json['erstellungsdatum'] == null ? undefined : (new Date(json['erstellungsdatum'])),
        'text': json['text'] == null ? undefined : json['text'],
        'dokumente': json['dokumente'] == null ? undefined : ((json['dokumente'] as Array<any>).map(DokumentDtoFromJSON)),
        'bearbeitendePerson': json['bearbeitendePerson'] == null ? undefined : BearbeitendePersonDtoFromJSON(json['bearbeitendePerson']),
        'bauvorhaben': json['bauvorhaben'] == null ? undefined : json['bauvorhaben'],
    };
}

export function KommentarBauvorhabenDtoToJSON(json: any): KommentarBauvorhabenDto {
    return KommentarBauvorhabenDtoToJSONTyped(json, false);
}

export function KommentarBauvorhabenDtoToJSONTyped(value?: KommentarBauvorhabenDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'version': value['version'],
        'createdDateTime': value['createdDateTime'] == null ? value['createdDateTime'] : value['createdDateTime'].toISOString(),
        'lastModifiedDateTime': value['lastModifiedDateTime'] == null ? value['lastModifiedDateTime'] : value['lastModifiedDateTime'].toISOString(),
        'erstellungsdatum': value['erstellungsdatum'] == null ? value['erstellungsdatum'] : value['erstellungsdatum'].toISOString().substring(0,10),
        'text': value['text'],
        'dokumente': value['dokumente'] == null ? undefined : ((value['dokumente'] as Array<any>).map(DokumentDtoToJSON)),
        'bearbeitendePerson': BearbeitendePersonDtoToJSON(value['bearbeitendePerson']),
        'bauvorhaben': value['bauvorhaben'],
    };
}

