/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MultiPolygonGeometry
 */
export interface MultiPolygonGeometry {
    /**
     * 
     * @type {string}
     * @memberof MultiPolygonGeometry
     */
    type?: string;
    /**
     * 
     * @type {Array<Array<Array<Array<number>>>>}
     * @memberof MultiPolygonGeometry
     */
    coordinates?: Array<Array<Array<Array<number>>>>;
}

/**
 * Check if a given object implements the MultiPolygonGeometry interface.
 */
export function instanceOfMultiPolygonGeometry(value: object): value is MultiPolygonGeometry {
    return true;
}

export function MultiPolygonGeometryFromJSON(json: any): MultiPolygonGeometry {
    return MultiPolygonGeometryFromJSONTyped(json, false);
}

export function MultiPolygonGeometryFromJSONTyped(json: any, ignoreDiscriminator: boolean): MultiPolygonGeometry {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'coordinates': json['coordinates'] == null ? undefined : json['coordinates'],
    };
}

export function MultiPolygonGeometryToJSON(json: any): MultiPolygonGeometry {
    return MultiPolygonGeometryToJSONTyped(json, false);
}

export function MultiPolygonGeometryToJSONTyped(value?: MultiPolygonGeometry | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'coordinates': value['coordinates'],
    };
}

