/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { EntityModelVersorgungsquoteSobonHort } from './EntityModelVersorgungsquoteSobonHort';
import {
    EntityModelVersorgungsquoteSobonHortFromJSON,
    EntityModelVersorgungsquoteSobonHortFromJSONTyped,
    EntityModelVersorgungsquoteSobonHortToJSON,
    EntityModelVersorgungsquoteSobonHortToJSONTyped,
} from './EntityModelVersorgungsquoteSobonHort';

/**
 * 
 * @export
 * @interface PagedModelEntityModelVersorgungsquoteSobonHortEmbedded
 */
export interface PagedModelEntityModelVersorgungsquoteSobonHortEmbedded {
    /**
     * 
     * @type {Array<EntityModelVersorgungsquoteSobonHort>}
     * @memberof PagedModelEntityModelVersorgungsquoteSobonHortEmbedded
     */
    versorgungsquoteSobonHorts?: Array<EntityModelVersorgungsquoteSobonHort>;
}

/**
 * Check if a given object implements the PagedModelEntityModelVersorgungsquoteSobonHortEmbedded interface.
 */
export function instanceOfPagedModelEntityModelVersorgungsquoteSobonHortEmbedded(value: object): value is PagedModelEntityModelVersorgungsquoteSobonHortEmbedded {
    return true;
}

export function PagedModelEntityModelVersorgungsquoteSobonHortEmbeddedFromJSON(json: any): PagedModelEntityModelVersorgungsquoteSobonHortEmbedded {
    return PagedModelEntityModelVersorgungsquoteSobonHortEmbeddedFromJSONTyped(json, false);
}

export function PagedModelEntityModelVersorgungsquoteSobonHortEmbeddedFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelVersorgungsquoteSobonHortEmbedded {
    if (json == null) {
        return json;
    }
    return {
        
        'versorgungsquoteSobonHorts': json['versorgungsquoteSobonHorts'] == null ? undefined : ((json['versorgungsquoteSobonHorts'] as Array<any>).map(EntityModelVersorgungsquoteSobonHortFromJSON)),
    };
}

export function PagedModelEntityModelVersorgungsquoteSobonHortEmbeddedToJSON(json: any): PagedModelEntityModelVersorgungsquoteSobonHortEmbedded {
    return PagedModelEntityModelVersorgungsquoteSobonHortEmbeddedToJSONTyped(json, false);
}

export function PagedModelEntityModelVersorgungsquoteSobonHortEmbeddedToJSONTyped(value?: PagedModelEntityModelVersorgungsquoteSobonHortEmbedded | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'versorgungsquoteSobonHorts': value['versorgungsquoteSobonHorts'] == null ? undefined : ((value['versorgungsquoteSobonHorts'] as Array<any>).map(EntityModelVersorgungsquoteSobonHortToJSON)),
    };
}

