/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageMetadata } from './PageMetadata';
import {
    PageMetadataFromJSON,
    PageMetadataFromJSONTyped,
    PageMetadataToJSON,
    PageMetadataToJSONTyped,
} from './PageMetadata';
import type { PagedModelEntityModelIdealtypischeBaurateEmbedded } from './PagedModelEntityModelIdealtypischeBaurateEmbedded';
import {
    PagedModelEntityModelIdealtypischeBaurateEmbeddedFromJSON,
    PagedModelEntityModelIdealtypischeBaurateEmbeddedFromJSONTyped,
    PagedModelEntityModelIdealtypischeBaurateEmbeddedToJSON,
    PagedModelEntityModelIdealtypischeBaurateEmbeddedToJSONTyped,
} from './PagedModelEntityModelIdealtypischeBaurateEmbedded';
import type { Link } from './Link';
import {
    LinkFromJSON,
    LinkFromJSONTyped,
    LinkToJSON,
    LinkToJSONTyped,
} from './Link';

/**
 * 
 * @export
 * @interface PagedModelEntityModelIdealtypischeBaurate
 */
export interface PagedModelEntityModelIdealtypischeBaurate {
    /**
     * 
     * @type {PagedModelEntityModelIdealtypischeBaurateEmbedded}
     * @memberof PagedModelEntityModelIdealtypischeBaurate
     */
    embedded?: PagedModelEntityModelIdealtypischeBaurateEmbedded;
    /**
     * 
     * @type {{ [key: string]: Link; }}
     * @memberof PagedModelEntityModelIdealtypischeBaurate
     */
    links?: { [key: string]: Link; };
    /**
     * 
     * @type {PageMetadata}
     * @memberof PagedModelEntityModelIdealtypischeBaurate
     */
    page?: PageMetadata;
}

/**
 * Check if a given object implements the PagedModelEntityModelIdealtypischeBaurate interface.
 */
export function instanceOfPagedModelEntityModelIdealtypischeBaurate(value: object): value is PagedModelEntityModelIdealtypischeBaurate {
    return true;
}

export function PagedModelEntityModelIdealtypischeBaurateFromJSON(json: any): PagedModelEntityModelIdealtypischeBaurate {
    return PagedModelEntityModelIdealtypischeBaurateFromJSONTyped(json, false);
}

export function PagedModelEntityModelIdealtypischeBaurateFromJSONTyped(json: any, ignoreDiscriminator: boolean): PagedModelEntityModelIdealtypischeBaurate {
    if (json == null) {
        return json;
    }
    return {
        
        'embedded': json['_embedded'] == null ? undefined : PagedModelEntityModelIdealtypischeBaurateEmbeddedFromJSON(json['_embedded']),
        'links': json['_links'] == null ? undefined : (mapValues(json['_links'], LinkFromJSON)),
        'page': json['page'] == null ? undefined : PageMetadataFromJSON(json['page']),
    };
}

export function PagedModelEntityModelIdealtypischeBaurateToJSON(json: any): PagedModelEntityModelIdealtypischeBaurate {
    return PagedModelEntityModelIdealtypischeBaurateToJSONTyped(json, false);
}

export function PagedModelEntityModelIdealtypischeBaurateToJSONTyped(value?: PagedModelEntityModelIdealtypischeBaurate | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        '_embedded': PagedModelEntityModelIdealtypischeBaurateEmbeddedToJSON(value['embedded']),
        '_links': value['links'] == null ? undefined : (mapValues(value['links'], LinkToJSON)),
        'page': PageMetadataToJSON(value['page']),
    };
}

