/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FilterSettings } from './FilterSettings';
import {
    FilterSettingsFromJSON,
    FilterSettingsFromJSONTyped,
    FilterSettingsToJSON,
    FilterSettingsToJSONTyped,
} from './FilterSettings';

/**
 * 
 * @export
 * @interface PersonalFilterRequestBody
 */
export interface PersonalFilterRequestBody {
    /**
     * 
     * @type {string}
     * @memberof PersonalFilterRequestBody
     */
    id?: string;
    /**
     * 
     * @type {number}
     * @memberof PersonalFilterRequestBody
     */
    version?: number;
    /**
     * 
     * @type {Date}
     * @memberof PersonalFilterRequestBody
     */
    createdDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof PersonalFilterRequestBody
     */
    lastModifiedDateTime?: Date;
    /**
     * 
     * @type {string}
     * @memberof PersonalFilterRequestBody
     */
    personalID: string;
    /**
     * 
     * @type {string}
     * @memberof PersonalFilterRequestBody
     */
    filterName: string;
    /**
     * 
     * @type {FilterSettings}
     * @memberof PersonalFilterRequestBody
     */
    filterSettings: FilterSettings;
}

/**
 * Check if a given object implements the PersonalFilterRequestBody interface.
 */
export function instanceOfPersonalFilterRequestBody(value: object): value is PersonalFilterRequestBody {
    if (!('personalID' in value) || value['personalID'] === undefined) return false;
    if (!('filterName' in value) || value['filterName'] === undefined) return false;
    if (!('filterSettings' in value) || value['filterSettings'] === undefined) return false;
    return true;
}

export function PersonalFilterRequestBodyFromJSON(json: any): PersonalFilterRequestBody {
    return PersonalFilterRequestBodyFromJSONTyped(json, false);
}

export function PersonalFilterRequestBodyFromJSONTyped(json: any, ignoreDiscriminator: boolean): PersonalFilterRequestBody {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'] == null ? undefined : json['id'],
        'version': json['version'] == null ? undefined : json['version'],
        'createdDateTime': json['createdDateTime'] == null ? undefined : (new Date(json['createdDateTime'])),
        'lastModifiedDateTime': json['lastModifiedDateTime'] == null ? undefined : (new Date(json['lastModifiedDateTime'])),
        'personalID': json['personalID'],
        'filterName': json['filterName'],
        'filterSettings': FilterSettingsFromJSON(json['filterSettings']),
    };
}

export function PersonalFilterRequestBodyToJSON(json: any): PersonalFilterRequestBody {
    return PersonalFilterRequestBodyToJSONTyped(json, false);
}

export function PersonalFilterRequestBodyToJSONTyped(value?: PersonalFilterRequestBody | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'version': value['version'],
        'createdDateTime': value['createdDateTime'] == null ? value['createdDateTime'] : value['createdDateTime'].toISOString(),
        'lastModifiedDateTime': value['lastModifiedDateTime'] == null ? value['lastModifiedDateTime'] : value['lastModifiedDateTime'].toISOString(),
        'personalID': value['personalID'],
        'filterName': value['filterName'],
        'filterSettings': FilterSettingsToJSON(value['filterSettings']),
    };
}

