/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 2.1.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SchnellfilterVorgaenge } from './SchnellfilterVorgaenge';
import {
    SchnellfilterVorgaengeFromJSON,
    SchnellfilterVorgaengeFromJSONTyped,
    SchnellfilterVorgaengeToJSON,
    SchnellfilterVorgaengeToJSONTyped,
} from './SchnellfilterVorgaenge';

/**
 * 
 * @export
 * @interface StartseitenEinstellungDto
 */
export interface StartseitenEinstellungDto {
    /**
     * 
     */
    schnellfilter: SchnellfilterVorgaenge;
    /**
     * 
     */
    sortBy: StartseitenEinstellungDtoSortByEnum;
    /**
     * 
     */
    sortOrder: StartseitenEinstellungDtoSortOrderEnum;
}


/**
 * @export
 */
export const StartseitenEinstellungDtoSortByEnum = {
    Name: 'NAME',
    CreatedDateTime: 'CREATED_DATE_TIME',
    LastModifiedDateTime: 'LAST_MODIFIED_DATE_TIME',
    FristBearbeitung: 'FRIST_BEARBEITUNG',
} as const;
export type StartseitenEinstellungDtoSortByEnum = typeof StartseitenEinstellungDtoSortByEnum[keyof typeof StartseitenEinstellungDtoSortByEnum];

/**
 * @export
 */
export const StartseitenEinstellungDtoSortOrderEnum = {
    Asc: 'ASC',
    Desc: 'DESC',
} as const;
export type StartseitenEinstellungDtoSortOrderEnum = typeof StartseitenEinstellungDtoSortOrderEnum[keyof typeof StartseitenEinstellungDtoSortOrderEnum];


/**
 * Check if a given object implements the StartseitenEinstellungDto interface.
 */
export function instanceOfStartseitenEinstellungDto(value: object): value is StartseitenEinstellungDto {
    if (!('schnellfilter' in value) || value['schnellfilter'] === undefined) return false;
    if (!('sortBy' in value) || value['sortBy'] === undefined) return false;
    if (!('sortOrder' in value) || value['sortOrder'] === undefined) return false;
    return true;
}

export function StartseitenEinstellungDtoFromJSON(json: any): StartseitenEinstellungDto {
    return StartseitenEinstellungDtoFromJSONTyped(json, false);
}

export function StartseitenEinstellungDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): StartseitenEinstellungDto {
    if (json == null) {
        return json;
    }
    return {
        
        'schnellfilter': SchnellfilterVorgaengeFromJSON(json['schnellfilter']),
        'sortBy': json['sortBy'],
        'sortOrder': json['sortOrder'],
    };
}

export function StartseitenEinstellungDtoToJSON(json: any): StartseitenEinstellungDto {
    return StartseitenEinstellungDtoToJSONTyped(json, false);
}

export function StartseitenEinstellungDtoToJSONTyped(value?: StartseitenEinstellungDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'schnellfilter': SchnellfilterVorgaengeToJSON(value['schnellfilter']),
        'sortBy': value['sortBy'],
        'sortOrder': value['sortOrder'],
    };
}

