/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Service für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 1.6.0
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import type { GrundschuleDto } from './GrundschuleDto';
import {
    instanceOfGrundschuleDto,
    GrundschuleDtoFromJSON,
    GrundschuleDtoFromJSONTyped,
    GrundschuleDtoToJSON,
} from './GrundschuleDto';
import type { GsNachmittagBetreuungDto } from './GsNachmittagBetreuungDto';
import {
    instanceOfGsNachmittagBetreuungDto,
    GsNachmittagBetreuungDtoFromJSON,
    GsNachmittagBetreuungDtoFromJSONTyped,
    GsNachmittagBetreuungDtoToJSON,
} from './GsNachmittagBetreuungDto';
import type { HausFuerKinderDto } from './HausFuerKinderDto';
import {
    instanceOfHausFuerKinderDto,
    HausFuerKinderDtoFromJSON,
    HausFuerKinderDtoFromJSONTyped,
    HausFuerKinderDtoToJSON,
} from './HausFuerKinderDto';
import type { KindergartenDto } from './KindergartenDto';
import {
    instanceOfKindergartenDto,
    KindergartenDtoFromJSON,
    KindergartenDtoFromJSONTyped,
    KindergartenDtoToJSON,
} from './KindergartenDto';
import type { KinderkrippeDto } from './KinderkrippeDto';
import {
    instanceOfKinderkrippeDto,
    KinderkrippeDtoFromJSON,
    KinderkrippeDtoFromJSONTyped,
    KinderkrippeDtoToJSON,
} from './KinderkrippeDto';
import type { MittelschuleDto } from './MittelschuleDto';
import {
    instanceOfMittelschuleDto,
    MittelschuleDtoFromJSON,
    MittelschuleDtoFromJSONTyped,
    MittelschuleDtoToJSON,
} from './MittelschuleDto';

/**
 * @type UpdateInfrastruktureinrichtungRequest
 * 
 * @export
 */
export type UpdateInfrastruktureinrichtungRequest = { infrastruktureinrichtungTyp: 'GRUNDSCHULE' } & GrundschuleDto | { infrastruktureinrichtungTyp: 'GS_NACHMITTAG_BETREUUNG' } & GsNachmittagBetreuungDto | { infrastruktureinrichtungTyp: 'HAUS_FUER_KINDER' } & HausFuerKinderDto | { infrastruktureinrichtungTyp: 'KINDERGARTEN' } & KindergartenDto | { infrastruktureinrichtungTyp: 'KINDERKRIPPE' } & KinderkrippeDto | { infrastruktureinrichtungTyp: 'MITTELSCHULE' } & MittelschuleDto;

export function UpdateInfrastruktureinrichtungRequestFromJSON(json: any): UpdateInfrastruktureinrichtungRequest {
    return UpdateInfrastruktureinrichtungRequestFromJSONTyped(json, false);
}

export function UpdateInfrastruktureinrichtungRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateInfrastruktureinrichtungRequest {
    if (json == null) {
        return json;
    }
    switch (json['infrastruktureinrichtungTyp']) {
        case 'GRUNDSCHULE':
            return Object.assign({}, GrundschuleDtoFromJSONTyped(json, true), { infrastruktureinrichtungTyp: 'GRUNDSCHULE' } as const);
        case 'GS_NACHMITTAG_BETREUUNG':
            return Object.assign({}, GsNachmittagBetreuungDtoFromJSONTyped(json, true), { infrastruktureinrichtungTyp: 'GS_NACHMITTAG_BETREUUNG' } as const);
        case 'HAUS_FUER_KINDER':
            return Object.assign({}, HausFuerKinderDtoFromJSONTyped(json, true), { infrastruktureinrichtungTyp: 'HAUS_FUER_KINDER' } as const);
        case 'KINDERGARTEN':
            return Object.assign({}, KindergartenDtoFromJSONTyped(json, true), { infrastruktureinrichtungTyp: 'KINDERGARTEN' } as const);
        case 'KINDERKRIPPE':
            return Object.assign({}, KinderkrippeDtoFromJSONTyped(json, true), { infrastruktureinrichtungTyp: 'KINDERKRIPPE' } as const);
        case 'MITTELSCHULE':
            return Object.assign({}, MittelschuleDtoFromJSONTyped(json, true), { infrastruktureinrichtungTyp: 'MITTELSCHULE' } as const);
        default:
            return json;
    }
}

export function UpdateInfrastruktureinrichtungRequestToJSON(json: any): any {
    return UpdateInfrastruktureinrichtungRequestToJSONTyped(json, false);
}

export function UpdateInfrastruktureinrichtungRequestToJSONTyped(value?: UpdateInfrastruktureinrichtungRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }
    switch (value['infrastruktureinrichtungTyp']) {
        case 'GRUNDSCHULE':
            return Object.assign({}, GrundschuleDtoToJSON(value), { 'infrastruktureinrichtungTyp': 'GRUNDSCHULE' } as const);
        case 'GS_NACHMITTAG_BETREUUNG':
            return Object.assign({}, GsNachmittagBetreuungDtoToJSON(value), { 'infrastruktureinrichtungTyp': 'GS_NACHMITTAG_BETREUUNG' } as const);
        case 'HAUS_FUER_KINDER':
            return Object.assign({}, HausFuerKinderDtoToJSON(value), { 'infrastruktureinrichtungTyp': 'HAUS_FUER_KINDER' } as const);
        case 'KINDERGARTEN':
            return Object.assign({}, KindergartenDtoToJSON(value), { 'infrastruktureinrichtungTyp': 'KINDERGARTEN' } as const);
        case 'KINDERKRIPPE':
            return Object.assign({}, KinderkrippeDtoToJSON(value), { 'infrastruktureinrichtungTyp': 'KINDERKRIPPE' } as const);
        case 'MITTELSCHULE':
            return Object.assign({}, MittelschuleDtoToJSON(value), { 'infrastruktureinrichtungTyp': 'MITTELSCHULE' } as const);
        default:
            return value;
    }
}

