/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Serivce für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    InformationResponseDto,
    InformationResponseDtoFromJSON,
    InformationResponseDtoToJSON,
    InfrastrukturabfrageDto,
    InfrastrukturabfrageDtoFromJSON,
    InfrastrukturabfrageDtoToJSON,
} from '../models';

export interface CreateInfrastrukturabfrageRequest {
    infrastrukturabfrageDto: InfrastrukturabfrageDto;
}

export interface DeleteInfrastrukturabfrageByIdRequest {
    id: string;
}

export interface GetInfrastrukturabfrageByIdRequest {
    id: string;
}

export interface UpdateInfrastrukturabfrageRequest {
    infrastrukturabfrageDto: InfrastrukturabfrageDto;
}

/**
 * 
 */
export class AbfrageApi extends runtime.BaseAPI {

    /**
     * Anlegen einer neuen Infrastrukturabfrage
     */
    async createInfrastrukturabfrageRaw(requestParameters: CreateInfrastrukturabfrageRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<InfrastrukturabfrageDto>> {
        if (requestParameters.infrastrukturabfrageDto === null || requestParameters.infrastrukturabfrageDto === undefined) {
            throw new runtime.RequiredError('infrastrukturabfrageDto','Required parameter requestParameters.infrastrukturabfrageDto was null or undefined when calling createInfrastrukturabfrage.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/infrastruktur-abfrage`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: InfrastrukturabfrageDtoToJSON(requestParameters.infrastrukturabfrageDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InfrastrukturabfrageDtoFromJSON(jsonValue));
    }

    /**
     * Anlegen einer neuen Infrastrukturabfrage
     */
    async createInfrastrukturabfrage(requestParameters: CreateInfrastrukturabfrageRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<InfrastrukturabfrageDto> {
        const response = await this.createInfrastrukturabfrageRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Löschen einer Infrastrukturabfrage
     */
    async deleteInfrastrukturabfrageByIdRaw(requestParameters: DeleteInfrastrukturabfrageByIdRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling deleteInfrastrukturabfrageById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/infrastruktur-abfrage/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Löschen einer Infrastrukturabfrage
     */
    async deleteInfrastrukturabfrageById(requestParameters: DeleteInfrastrukturabfrageByIdRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<void> {
        await this.deleteInfrastrukturabfrageByIdRaw(requestParameters, initOverrides);
    }

    /**
     * Lesen einer Infrastrukturabfrage
     */
    async getInfrastrukturabfrageByIdRaw(requestParameters: GetInfrastrukturabfrageByIdRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<InfrastrukturabfrageDto>> {
        if (requestParameters.id === null || requestParameters.id === undefined) {
            throw new runtime.RequiredError('id','Required parameter requestParameters.id was null or undefined when calling getInfrastrukturabfrageById.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/infrastruktur-abfrage/{id}`.replace(`{${"id"}}`, encodeURIComponent(String(requestParameters.id))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InfrastrukturabfrageDtoFromJSON(jsonValue));
    }

    /**
     * Lesen einer Infrastrukturabfrage
     */
    async getInfrastrukturabfrageById(requestParameters: GetInfrastrukturabfrageByIdRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<InfrastrukturabfrageDto> {
        const response = await this.getInfrastrukturabfrageByIdRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Das Ergebnis wird nach Frist Stellungnahme absteigend sortiert
     * Lade alle Infrastrukturabfragen
     */
    async getInfrastrukturabfragenRaw(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<Array<InfrastrukturabfrageDto>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/infrastruktur-abfragen`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(InfrastrukturabfrageDtoFromJSON));
    }

    /**
     * Das Ergebnis wird nach Frist Stellungnahme absteigend sortiert
     * Lade alle Infrastrukturabfragen
     */
    async getInfrastrukturabfragen(initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<Array<InfrastrukturabfrageDto>> {
        const response = await this.getInfrastrukturabfragenRaw(initOverrides);
        return await response.value();
    }

    /**
     * Aktualisierung einer Infrastrukturabfrage
     */
    async updateInfrastrukturabfrageRaw(requestParameters: UpdateInfrastrukturabfrageRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<runtime.ApiResponse<InfrastrukturabfrageDto>> {
        if (requestParameters.infrastrukturabfrageDto === null || requestParameters.infrastrukturabfrageDto === undefined) {
            throw new runtime.RequiredError('infrastrukturabfrageDto','Required parameter requestParameters.infrastrukturabfrageDto was null or undefined when calling updateInfrastrukturabfrage.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/infrastruktur-abfrage`,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: InfrastrukturabfrageDtoToJSON(requestParameters.infrastrukturabfrageDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => InfrastrukturabfrageDtoFromJSON(jsonValue));
    }

    /**
     * Aktualisierung einer Infrastrukturabfrage
     */
    async updateInfrastrukturabfrage(requestParameters: UpdateInfrastrukturabfrageRequest, initOverrides?: RequestInit | runtime.InitOverideFunction): Promise<InfrastrukturabfrageDto> {
        const response = await this.updateInfrastrukturabfrageRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
