/* tslint:disable */
/* eslint-disable */
/**
 * ISI GEODATA EAI
 * ISI GEODATA EAI - Service zum Abfragen von Geoinformationen
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { FeatureDtoViertelDtoGeometry } from './FeatureDtoViertelDtoGeometry';
import {
    FeatureDtoViertelDtoGeometryFromJSON,
    FeatureDtoViertelDtoGeometryFromJSONTyped,
    FeatureDtoViertelDtoGeometryToJSON,
    FeatureDtoViertelDtoGeometryToJSONTyped,
} from './FeatureDtoViertelDtoGeometry';
import type { FlurstueckDto } from './FlurstueckDto';
import {
    FlurstueckDtoFromJSON,
    FlurstueckDtoFromJSONTyped,
    FlurstueckDtoToJSON,
    FlurstueckDtoToJSONTyped,
} from './FlurstueckDto';

/**
 * 
 * @export
 * @interface FeatureDtoFlurstueckDto
 */
export interface FeatureDtoFlurstueckDto {
    /**
     * 
     * @type {string}
     * @memberof FeatureDtoFlurstueckDto
     */
    type?: string;
    /**
     * 
     * @type {FeatureDtoViertelDtoGeometry}
     * @memberof FeatureDtoFlurstueckDto
     */
    geometry?: FeatureDtoViertelDtoGeometry;
    /**
     * 
     * @type {FlurstueckDto}
     * @memberof FeatureDtoFlurstueckDto
     */
    properties?: FlurstueckDto;
}

/**
 * Check if a given object implements the FeatureDtoFlurstueckDto interface.
 */
export function instanceOfFeatureDtoFlurstueckDto(value: object): value is FeatureDtoFlurstueckDto {
    return true;
}

export function FeatureDtoFlurstueckDtoFromJSON(json: any): FeatureDtoFlurstueckDto {
    return FeatureDtoFlurstueckDtoFromJSONTyped(json, false);
}

export function FeatureDtoFlurstueckDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureDtoFlurstueckDto {
    if (json == null) {
        return json;
    }
    return {
        
        'type': json['type'] == null ? undefined : json['type'],
        'geometry': json['geometry'] == null ? undefined : FeatureDtoViertelDtoGeometryFromJSON(json['geometry']),
        'properties': json['properties'] == null ? undefined : FlurstueckDtoFromJSON(json['properties']),
    };
}

export function FeatureDtoFlurstueckDtoToJSON(json: any): FeatureDtoFlurstueckDto {
    return FeatureDtoFlurstueckDtoToJSONTyped(json, false);
}

export function FeatureDtoFlurstueckDtoToJSONTyped(value?: FeatureDtoFlurstueckDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'type': value['type'],
        'geometry': FeatureDtoViertelDtoGeometryToJSON(value['geometry']),
        'properties': FlurstueckDtoToJSON(value['properties']),
    };
}

