/* tslint:disable */
/* eslint-disable */
/**
 * ISI GEODATA EAI
 * ISI GEODATA EAI - Service zum Abfragen von Geoinformationen
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FeatureDtoGemarkungDto } from './FeatureDtoGemarkungDto';
import {
    FeatureDtoGemarkungDtoFromJSON,
    FeatureDtoGemarkungDtoFromJSONTyped,
    FeatureDtoGemarkungDtoToJSON,
} from './FeatureDtoGemarkungDto';

/**
 * 
 * @export
 * @interface FeatureCollectionDtoFeatureDtoGemarkungDto
 */
export interface FeatureCollectionDtoFeatureDtoGemarkungDto {
    /**
     * 
     * @type {string}
     * @memberof FeatureCollectionDtoFeatureDtoGemarkungDto
     */
    type?: string;
    /**
     * 
     * @type {Array<FeatureDtoGemarkungDto>}
     * @memberof FeatureCollectionDtoFeatureDtoGemarkungDto
     */
    features?: Array<FeatureDtoGemarkungDto>;
}

/**
 * Check if a given object implements the FeatureCollectionDtoFeatureDtoGemarkungDto interface.
 */
export function instanceOfFeatureCollectionDtoFeatureDtoGemarkungDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeatureCollectionDtoFeatureDtoGemarkungDtoFromJSON(json: any): FeatureCollectionDtoFeatureDtoGemarkungDto {
    return FeatureCollectionDtoFeatureDtoGemarkungDtoFromJSONTyped(json, false);
}

export function FeatureCollectionDtoFeatureDtoGemarkungDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureCollectionDtoFeatureDtoGemarkungDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'features': !exists(json, 'features') ? undefined : ((json['features'] as Array<any>).map(FeatureDtoGemarkungDtoFromJSON)),
    };
}

export function FeatureCollectionDtoFeatureDtoGemarkungDtoToJSON(value?: FeatureCollectionDtoFeatureDtoGemarkungDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'features': value.features === undefined ? undefined : ((value.features as Array<any>).map(FeatureDtoGemarkungDtoToJSON)),
    };
}

