/* tslint:disable */
/* eslint-disable */
/**
 * ISI GEODATA EAI
 * ISI GEODATA EAI - Service zum Abfragen von Geoinformationen
 *
 * The version of the OpenAPI document: 1.4.0
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { FeatureDtoBezirksteilDto } from './FeatureDtoBezirksteilDto';
import {
    FeatureDtoBezirksteilDtoFromJSON,
    FeatureDtoBezirksteilDtoFromJSONTyped,
    FeatureDtoBezirksteilDtoToJSON,
} from './FeatureDtoBezirksteilDto';

/**
 * 
 * @export
 * @interface FeatureCollectionDtoFeatureDtoBezirksteilDto
 */
export interface FeatureCollectionDtoFeatureDtoBezirksteilDto {
    /**
     * 
     * @type {string}
     * @memberof FeatureCollectionDtoFeatureDtoBezirksteilDto
     */
    type?: string;
    /**
     * 
     * @type {Array<FeatureDtoBezirksteilDto>}
     * @memberof FeatureCollectionDtoFeatureDtoBezirksteilDto
     */
    features?: Array<FeatureDtoBezirksteilDto>;
}

/**
 * Check if a given object implements the FeatureCollectionDtoFeatureDtoBezirksteilDto interface.
 */
export function instanceOfFeatureCollectionDtoFeatureDtoBezirksteilDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function FeatureCollectionDtoFeatureDtoBezirksteilDtoFromJSON(json: any): FeatureCollectionDtoFeatureDtoBezirksteilDto {
    return FeatureCollectionDtoFeatureDtoBezirksteilDtoFromJSONTyped(json, false);
}

export function FeatureCollectionDtoFeatureDtoBezirksteilDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureCollectionDtoFeatureDtoBezirksteilDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'features': !exists(json, 'features') ? undefined : ((json['features'] as Array<any>).map(FeatureDtoBezirksteilDtoFromJSON)),
    };
}

export function FeatureCollectionDtoFeatureDtoBezirksteilDtoToJSON(value?: FeatureCollectionDtoFeatureDtoBezirksteilDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'features': value.features === undefined ? undefined : ((value.features as Array<any>).map(FeatureDtoBezirksteilDtoToJSON)),
    };
}

