/* tslint:disable */
/* eslint-disable */
/**
 * ISI GEODATA EAI
 * ISI GEODATA EAI - Service zum Abfragen von Geoinformationen
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    FeatureDtoSchulstandortDto,
    FeatureDtoSchulstandortDtoFromJSON,
    FeatureDtoSchulstandortDtoFromJSONTyped,
    FeatureDtoSchulstandortDtoToJSON,
} from './FeatureDtoSchulstandortDto';

/**
 * 
 * @export
 * @interface FeatureCollectionDtoFeatureDtoSchulstandortDto
 */
export interface FeatureCollectionDtoFeatureDtoSchulstandortDto {
    /**
     * 
     * @type {Array<FeatureDtoSchulstandortDto>}
     * @memberof FeatureCollectionDtoFeatureDtoSchulstandortDto
     */
    feature?: Array<FeatureDtoSchulstandortDto>;
}

export function FeatureCollectionDtoFeatureDtoSchulstandortDtoFromJSON(json: any): FeatureCollectionDtoFeatureDtoSchulstandortDto {
    return FeatureCollectionDtoFeatureDtoSchulstandortDtoFromJSONTyped(json, false);
}

export function FeatureCollectionDtoFeatureDtoSchulstandortDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): FeatureCollectionDtoFeatureDtoSchulstandortDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'feature': !exists(json, 'feature') ? undefined : ((json['feature'] as Array<any>).map(FeatureDtoSchulstandortDtoFromJSON)),
    };
}

export function FeatureCollectionDtoFeatureDtoSchulstandortDtoToJSON(value?: FeatureCollectionDtoFeatureDtoSchulstandortDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'feature': value.feature === undefined ? undefined : ((value.feature as Array<any>).map(FeatureDtoSchulstandortDtoToJSON)),
    };
}

