/* tslint:disable */
/* eslint-disable */
/**
 * ISI GEODATA EAI
 * ISI GEODATA EAI - Service zum Abfragen von Geoinformationen
 *
 * The version of the OpenAPI document: 1.5.0
 * Contact: unbekannt@muenchen.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GrundschulsprengelDto
 */
export interface GrundschulsprengelDto {
    /**
     * 
     * @type {number}
     * @memberof GrundschulsprengelDto
     */
    objectId?: number;
    /**
     * 
     * @type {number}
     * @memberof GrundschulsprengelDto
     */
    ebene?: number;
    /**
     * 
     * @type {number}
     * @memberof GrundschulsprengelDto
     */
    flaecheQm?: number;
    /**
     * 
     * @type {number}
     * @memberof GrundschulsprengelDto
     */
    schulnummer?: number;
    /**
     * 
     * @type {string}
     * @memberof GrundschulsprengelDto
     */
    verbundnummer?: string;
    /**
     * 
     * @type {string}
     * @memberof GrundschulsprengelDto
     */
    verbundname?: string;
    /**
     * 
     * @type {string}
     * @memberof GrundschulsprengelDto
     */
    ebeneBedeutung?: string;
    /**
     * 
     * @type {number}
     * @memberof GrundschulsprengelDto
     */
    xcoordinate?: number;
    /**
     * 
     * @type {number}
     * @memberof GrundschulsprengelDto
     */
    ycoordinate?: number;
}

/**
 * Check if a given object implements the GrundschulsprengelDto interface.
 */
export function instanceOfGrundschulsprengelDto(value: object): value is GrundschulsprengelDto {
    return true;
}

export function GrundschulsprengelDtoFromJSON(json: any): GrundschulsprengelDto {
    return GrundschulsprengelDtoFromJSONTyped(json, false);
}

export function GrundschulsprengelDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GrundschulsprengelDto {
    if (json == null) {
        return json;
    }
    return {
        
        'objectId': json['objectId'] == null ? undefined : json['objectId'],
        'ebene': json['ebene'] == null ? undefined : json['ebene'],
        'flaecheQm': json['flaecheQm'] == null ? undefined : json['flaecheQm'],
        'schulnummer': json['schulnummer'] == null ? undefined : json['schulnummer'],
        'verbundnummer': json['verbundnummer'] == null ? undefined : json['verbundnummer'],
        'verbundname': json['verbundname'] == null ? undefined : json['verbundname'],
        'ebeneBedeutung': json['ebeneBedeutung'] == null ? undefined : json['ebeneBedeutung'],
        'xcoordinate': json['xcoordinate'] == null ? undefined : json['xcoordinate'],
        'ycoordinate': json['ycoordinate'] == null ? undefined : json['ycoordinate'],
    };
}

export function GrundschulsprengelDtoToJSON(json: any): GrundschulsprengelDto {
    return GrundschulsprengelDtoToJSONTyped(json, false);
}

export function GrundschulsprengelDtoToJSONTyped(value?: GrundschulsprengelDto | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'objectId': value['objectId'],
        'ebene': value['ebene'],
        'flaecheQm': value['flaecheQm'],
        'schulnummer': value['schulnummer'],
        'verbundnummer': value['verbundnummer'],
        'verbundname': value['verbundname'],
        'ebeneBedeutung': value['ebeneBedeutung'],
        'xcoordinate': value['xcoordinate'],
        'ycoordinate': value['ycoordinate'],
    };
}

