server:
  port: 39146
spring:
  # Spring data rest
  data:
    rest:
      # Definition of page size for PagingAndSortingRepository
      max-page-size: 0x7fffffff
      default-page-size: 0x7fffffff
      return-body-on-update: true
      return-body-on-create: true

  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
  # Spring JPA
  h2.console.enabled: true
  jpa:
    database: H2
    hibernate:
      # always drop and create the db should be the best
      # configuration for local (development) mode. this
      # is also the default, that spring offers by convention.
      # but here explicite:
      ddl-auto: create-drop
    # Logging for database operation
    show-sql: true
    properties:
      hibernate:
        format_sql: true

io:
  muenchendigital:
    digiwf:
      s3:
        client:
          document-storage-url: http://localhost:8080
          file-expiration-time: 1 #minutes

# duplicate in application.yml
file:
  number.max: 20
  size.max: 52428800 # Bytes = 50 Mebibyte (MiB)
  extensions.allowed: .msg # Dateiendungen welche nicht über den MIME-Type ermittelt werden können. Werden benötigt für die backendseitige Validierung der Dateiendung.
  mimetypes.allowed: application/pdf,image/png