name: build and test

on: [push]

jobs:
  build-test-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Execute npm install, test, build
        working-directory: frontend
        run: |
          npm ci
          npm run build --if-present
          npm run test:unit
      - name: Check with eslint
        run: |
          npm install
          npm run check
      - name: Archive npm artifacts
        uses: actions/upload-artifact@v4
        with:
          name: npm-artifacts
          path: |
            frontend/dist
          retention-days: 10

  build-test-java:
    runs-on: ubuntu-latest
    needs: build-test-npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download npm articats
        uses: actions/download-artifact@v4
        with:
          name: npm-artifacts

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        # TODO: Tests vom API Gateway funktionieren nur mit dem SSO. Muss noch konfiguriert werden.
        run: mvn -B -Pgitlab-cicd verify -DskipTests -Dspring.security.logging.requests=all --file pom.xml
  #        run: mvn -B -s ./.m2/settings.xml -Pgitlab-cicd verify -Dspring.security.logging.requests=all --file pom.xml

  compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Advance Security Policy as Code
        uses: advanced-security/policy-as-code@v2.4.1
        with:
          policy: it-at-m/policy-as-code
          policy-path: default.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          argvs: "--disable-dependabot --disable-secret-scanning --disable-code-scanning --display"
