name: build and test

on: [push]

jobs:
  build-test-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
# TODO: package-lock.json einchecken
#          cache: 'npm'
#          cache-dependency-path: "./frontend/package-lock.json"
      - name: Execute npm install, test, build
        working-directory: frontend
        run: |
          npm install
          npm run lint
          npm run build --if-present
          
      - name: Archive npm artifacts
        uses: actions/upload-artifact@v3
        with:
          name: npm-artifacts
          path: |
            frontend/dist
            frontend/node_modules
          retention-days: 10

  build-test-java:
    runs-on: ubuntu-latest
    needs: build-test-npm
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download npm articats
        uses: actions/download-artifact@v3
        with:
          name: npm-artifacts
          
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: "11"
          distribution: "temurin"
          cache: maven

      - name: Build with Maven
        run: mvn -B -s ./.m2/settings.xml -Pgitlab-cicd verify -Dspring.security.logging.requests=all --file pom.xml
        
  compliance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Advance Security Policy as Code
        uses: advanced-security/policy-as-code@v2.4.1
        with:
          policy: it-at-m/policy-as-code
          policy-path: default.yaml
          token: ${{ secrets.GITHUB_TOKEN }}
          argvs: "--disable-dependabot --disable-secret-scanning --disable-code-scanning --display"
