name: Dependency Review
permissions:
  contents: read

on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dependency-review@992204b33cb6a9766bbc8bc57ccd1460c4bf1aa9 # v1.0.26