name: Dependency Review
permissions:
  contents: read

on:
  pull_request:

jobs:
  dependency-review:
    runs-on: ubuntu-latest
    steps:
      - uses: it-at-m/lhm_actions/action-templates/actions/action-dependency-review@e967c9de8fb0197faf7a294d153efa76de5cec27 # v1.6.0