/* tslint:disable */
/* eslint-disable */
/**
 * ISI Backend API
 * ISI Backend - Serivce für das Informationssystem für soziale Infrastrukturplanung
 *
 * The version of the OpenAPI document: 0.0.1-SNAPSHOT
 * Contact: noreply@mail.de
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    InfrastruktureinrichtungDto,
    InfrastruktureinrichtungDtoFromJSON,
    InfrastruktureinrichtungDtoFromJSONTyped,
    InfrastruktureinrichtungDtoToJSON,
} from './InfrastruktureinrichtungDto';

/**
 * 
 * @export
 * @interface GsNachmittagBetreuungDto
 */
export interface GsNachmittagBetreuungDto {
    /**
     * 
     * @type {string}
     * @memberof GsNachmittagBetreuungDto
     */
    id?: string;
    /**
     * 
     * @type {Date}
     * @memberof GsNachmittagBetreuungDto
     */
    createdDateTime?: Date;
    /**
     * 
     * @type {Date}
     * @memberof GsNachmittagBetreuungDto
     */
    lastModifiedDateTime?: Date;
    /**
     * 
     * @type {InfrastruktureinrichtungDto}
     * @memberof GsNachmittagBetreuungDto
     */
    infrastruktureinrichtung: InfrastruktureinrichtungDto;
    /**
     * 
     * @type {string}
     * @memberof GsNachmittagBetreuungDto
     */
    artGsNachmittagBetreuung?: GsNachmittagBetreuungDtoArtGsNachmittagBetreuungEnum;
}


/**
 * @export
 */
export const GsNachmittagBetreuungDtoArtGsNachmittagBetreuungEnum = {
    Hort: 'HORT',
    KooperativerGanztagFlexibleVariante: 'KOOPERATIVER_GANZTAG_FLEXIBLE_VARIANTE',
    KooperativerGanztagRhythmisierteVariante: 'KOOPERATIVER_GANZTAG_RHYTHMISIERTE_VARIANTE',
    Tagesheim: 'TAGESHEIM',
    Mittagsbetreuung: 'MITTAGSBETREUUNG'
} as const;
export type GsNachmittagBetreuungDtoArtGsNachmittagBetreuungEnum = typeof GsNachmittagBetreuungDtoArtGsNachmittagBetreuungEnum[keyof typeof GsNachmittagBetreuungDtoArtGsNachmittagBetreuungEnum];


export function GsNachmittagBetreuungDtoFromJSON(json: any): GsNachmittagBetreuungDto {
    return GsNachmittagBetreuungDtoFromJSONTyped(json, false);
}

export function GsNachmittagBetreuungDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): GsNachmittagBetreuungDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'createdDateTime': !exists(json, 'createdDateTime') ? undefined : (new Date(json['createdDateTime'])),
        'lastModifiedDateTime': !exists(json, 'lastModifiedDateTime') ? undefined : (new Date(json['lastModifiedDateTime'])),
        'infrastruktureinrichtung': InfrastruktureinrichtungDtoFromJSON(json['infrastruktureinrichtung']),
        'artGsNachmittagBetreuung': !exists(json, 'artGsNachmittagBetreuung') ? undefined : json['artGsNachmittagBetreuung'],
    };
}

export function GsNachmittagBetreuungDtoToJSON(value?: GsNachmittagBetreuungDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'createdDateTime': value.createdDateTime === undefined ? undefined : (value.createdDateTime.toISOString()),
        'lastModifiedDateTime': value.lastModifiedDateTime === undefined ? undefined : (value.lastModifiedDateTime.toISOString()),
        'infrastruktureinrichtung': InfrastruktureinrichtungDtoToJSON(value.infrastruktureinrichtung),
        'artGsNachmittagBetreuung': value.artGsNachmittagBetreuung,
    };
}

